[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  # Désactive le clonage des submodules privés (problème d'accès)
  NPM_FLAGS = "--ignore-scripts"
  GIT_SUBMODULE_STRATEGY = "none"
