export interface FauneEntry {
  id: string;
  categorie: string;
  sousCategorie: string;
  nomCreole: string;
  nomFrancais: string;
  nomScientifique: string;
  isResistanceSymbol: boolean;
  resistanceType?: string;
  resistanceDescription?: string;
  sacreSymbolique?: string;
  dimensionCulturelle: string;
  tags: string[];
}


// Données générées automatiquement depuis faune_guadeloupe_ref.md
// NE PAS MODIFIER MANUELLEMENT - Exécuter 'npm run faune:parse' pour mettre à jour
export const fauneData: FauneEntry[] = [
  {
  id: "fwou-fwou-kolibri-ort",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Fwou-fwou / Kolibri",
  nomFrancais: "Colibri huppé",
  nomScientifique: "Orthorhyncus cristatus",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Son nom vient directement des Arawaks et des Kalinagos. Dans l'imaginaire caribéen et amérindien, il symbolise la joie, la résilience et la beauté des choses éphémères. Apercevoir un colibri tôt le matin est signe de chance et d'inspiration. Pollinisateur sacré du jardin créole.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Son nom vient directement des Arawaks et des Kalinagos. Dans l'imaginaire caribéen et amérindien, il symbolise la joie, la résilience et la beauté des choses éphémères. Apercevoir un colibri tôt le matin est signe de chance et d'inspiration. Pollinisateur sacré du jardin créole.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "sacré-son-nom-vient-directement-des-arawaks-et-des-kalinagos.-dans-l'imaginaire-caribéen-et-amérindien,-il-symbolise-la-joie,-la-résilience-et-la-beauté-des-choses-éphémères.-apercevoir-un-colibri-tôt-le-matin-est-signe-de-chance-et-d'inspiration.-pollinisateur-sacré-du-jardin-créole."],
  },
  {
  id: "kolibri-mad-eul",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Kolibri madè",
  nomFrancais: "Colibri madère",
  nomScientifique: "Eulampis jugularis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Plus grand colibri de Guadeloupe (12 cm), à la gorge pourpre éclatante. Même symbolique que le frou-frou. Espèce protégée.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Plus grand colibri de Guadeloupe (12 cm), à la gorge pourpre éclatante. Même symbolique que le frou-frou. Espèce protégée.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "sacré-plus-grand-colibri-de-guadeloupe-(12-cm),-à-la-gorge-pourpre-éclatante.-même-symbolique-que-le-frou-frou.-espèce-protégée."],
  },
  {
  id: "kolibri-fal-vt-eul",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Kolibri fal vèt",
  nomFrancais: "Colibri falle-vert",
  nomScientifique: "Eulampis holosericeus",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Couleur changeante : vert au soleil, presque noir la nuit. Présence mystérieuse liée aux croyances créoles sur la transformation.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Couleur changeante : vert au soleil, presque noir la nuit. Présence mystérieuse liée aux croyances créoles sur la transformation.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "emblématique-couleur-changeante-:-vert-au-soleil,-presque-noir-la-nuit.-présence-mystérieuse-liée-aux-croyances-créoles-sur-la-transformation."],
  },
  {
  id: "sucrier-coe",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Sucrier",
  nomFrancais: "Sucrier à ventre jaune",
  nomScientifique: "Coereba flaveola",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Oiseau du quotidien dans tous les jardins créoles. Son chant annonce les changements de temps. Petit oiseau jaune discret, présent dans tous les jardins créoles de Guadeloupe.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "symbolique"],
  },
  {
  id: "soukougnan-myt",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "entité mythologique",
  nomCreole: "Soukougnan",
  nomFrancais: "Vampire créole",
  nomScientifique: "(mythologique)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ MYTHIQUE Créature du folklore antillais — vampire qui enlève sa peau humaine à la nuit tombée et l'accroche aux branches d'un fromager. Peut prendre l'apparence d'une boule de feu ou d'un oiseau noir. L'arbre fromager est surnommé « arbre aux soukougnan » et « arbre aux esclaves » : les esclaves récalcitrants y étaient suppliciés, attachés par des liens de cuir mouillés que le soleil rétrécissait, forçant les épines dans leur chair. Figure centrale de la nuit créole et de la peur de l'entre-deux-mondes.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ MYTHIQUE",
  dimensionCulturelle: "Créature du folklore antillais — vampire qui enlève sa peau humaine à la nuit tombée et l'accroche aux branches d'un fromager. Peut prendre l'apparence d'une boule de feu ou d'un oiseau noir. L'arbre fromager est surnommé « arbre aux soukougnan » et « arbre aux esclaves » : les esclaves récalcitrants y étaient suppliciés, attachés par des liens de cuir mouillés que le soleil rétrécissait, forçant les épines dans leur chair. Figure centrale de la nuit créole et de la peur de l'entre-deux-mondes.",
  tags: ["oiseaux sacrés", "entité mythologique", "resistance", "sacré", "sacré-mythique-créature-du-folklore-antillais-—-vampire-qui-enlève-sa-peau-humaine-à-la-nuit-tombée-et-l'accroche-aux-branches-d'un-fromager.-peut-prendre-l'apparence-d'une-boule-de-feu-ou-d'un-oiseau-noir.-l'arbre-fromager-est-surnommé-«-arbre-aux-soukougnan-»-et-«-arbre-aux-esclaves-»-:-les-esclaves-récalcitrants-y-étaient-suppliciés,-attachés-par-des-liens-de-cuir-mouillés-que-le-soleil-rétrécissait,-forçant-les-épines-dans-leur-chair.-figure-centrale-de-la-nuit-créole-et-de-la-peur-de-l'entre-deux-mondes."],
  },
  {
  id: "plikan-gran-plikan-pel",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Pélikan / Gran pélikan",
  nomFrancais: "Pélican brun",
  nomScientifique: "Pelecanus occidentalis",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Symbole de la pêche et des pêcheurs. Sa présence en masse annonce le beau temps et la bonne prise. Animal totem des communautés de pêcheurs de Guadeloupe.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "symbolique"],
  },
  {
  id: "urakan-frgate-fre",
  categorie: "ANIMAUX — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "oiseau / résistance",
  nomCreole: "Urakan / Frégate",
  nomFrancais: "Frégate superbe",
  nomScientifique: "Fregata magnificens",
  isResistanceSymbol: true,
  resistanceType: "LIBERTÉ",
  resistanceDescription: undefined,
  sacreSymbolique: "LIBERTÉ ABSOLUE",
  dimensionCulturelle: "Oiseau qui ne se pose presque jamais, vole pendant des jours sans toucher terre. Symbole du marronnage aérien, de la liberté absolue et de l'insoumission. Associé aux esprits qui ne peuvent être enchaînés.",
  tags: ["animaux — symboles de résistance", "oiseau / résistance", "resistance", "sacré", "liberté"],
  },
  {
  id: "pic-de-gwadloup-mel",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Pic de Gwadloup",
  nomFrancais: "Pic de Guadeloupe",
  nomScientifique: "Melanerpes herminieri",
  isResistanceSymbol: true,
  resistanceType: "Endémique sacré Oiseau endémique unique au monde. Espèce vulnérable. Dans la tradition créole, son tambourinage sur les arbres est un message des esprits de la forêt.",
  resistanceDescription: undefined,
  sacreSymbolique: "Endémique sacré",
  dimensionCulturelle: "Oiseau endémique unique au monde. Espèce vulnérable. Dans la tradition créole, son tambourinage sur les arbres est un message des esprits de la forêt.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "endémique-sacré-oiseau-endémique-unique-au-monde.-espèce-vulnérable.-dans-la-tradition-créole,-son-tambourinage-sur-les-arbres-est-un-message-des-esprits-de-la-forêt."],
  },
  {
  id: "yl-siffleur-montagne-sei",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Yòlò / Siffleur montagne",
  nomFrancais: "Siffleur des montagnes",
  nomScientifique: "Seiurus aurocapilla",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Oiseau des mornes et de la forêt haute. Son chant plaintif est associé dans la tradition créole à la présence des esprits des ancêtres marrons.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "symbolique"],
  },
  {
  id: "jakt-ama",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Jakòt",
  nomFrancais: "Perroquet de Guadeloupe",
  nomScientifique: "Amazona violacea (éteint)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ DISPARU Perroquet vert de Guadeloupe, disparu au XVIIIe siècle. Son nom créole « Jakòt » est d'origine africaine. Les Kalinagos en faisaient un animal totem et de compagnie sacrée. Sa disparition est vécue comme une perte spirituelle.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ DISPARU",
  dimensionCulturelle: "Perroquet vert de Guadeloupe, disparu au XVIIIe siècle. Son nom créole « Jakòt » est d'origine africaine. Les Kalinagos en faisaient un animal totem et de compagnie sacrée. Sa disparition est vécue comme une perte spirituelle.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "sacré-disparu-perroquet-vert-de-guadeloupe,-disparu-au-xviiie-siècle.-son-nom-créole-«-jakòt-»-est-d'origine-africaine.-les-kalinagos-en-faisaient-un-animal-totem-et-de-compagnie-sacrée.-sa-disparition-est-vécue-comme-une-perte-spirituelle."],
  },
  {
  id: "serpan-sym",
  categorie: "ANIMAUX DU QUIMBOIS",
  sousCategorie: "ritual / quimbois",
  nomCreole: "Serpan",
  nomFrancais: "Serpent (symbolique)",
  nomScientifique: "(symbolique)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ AMBIVALENT Absent de Guadeloupe mais fortement présent dans l'imaginaire spirituel africain importé par les esclaves. Le serpent est le médiateur entre les vivants et les esprits dans les traditions vaudou et créoles. Les gadèzafé utilisent des représentations de serpents dans leurs autels.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ AMBIVALENT",
  dimensionCulturelle: "Absent de Guadeloupe mais fortement présent dans l'imaginaire spirituel africain importé par les esclaves. Le serpent est le médiateur entre les vivants et les esprits dans les traditions vaudou et créoles. Les gadèzafé utilisent des représentations de serpents dans leurs autels.",
  tags: ["animaux du quimbois", "ritual / quimbois", "resistance", "sacré", "sacré-ambivalent-absent-de-guadeloupe-mais-fortement-présent-dans-l'imaginaire-spirituel-africain-importé-par-les-esclaves.-le-serpent-est-le-médiateur-entre-les-vivants-et-les-esprits-dans-les-traditions-vaudou-et-créoles.-les-gadèzafé-utilisent-des-représentations-de-serpents-dans-leurs-autels."],
  },
  {
  id: "merl-lafr-tur",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Merl lafòrè",
  nomFrancais: "Merle de forêt",
  nomScientifique: "Turdus lherminieri",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ ENDÉMIQUE Endémique de la forêt humide. Son chant est utilisé dans les rituels de quimbois pour appeler les ancêtres (Boucher 2008, MNHN). Statut UICN: EN.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ ENDÉMIQUE",
  dimensionCulturelle: "Endémique de la forêt humide. Son chant est utilisé dans les rituels de quimbois pour appeler les ancêtres (Boucher 2008, MNHN). Statut UICN: EN.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "sacré-endémique-endémique-de-la-forêt-humide.-son-chant-est-utilisé-dans-les-rituels-de-quimbois-pour-appeler-les-ancêtres-(boucher-2008,-mnhn).-statut-uicn:-en."],
  },
  {
  id: "ti-chant-set",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Ti chantè",
  nomFrancais: "Paruline caféiette",
  nomScientifique: "Setophaga plumbea",
  isResistanceSymbol: true,
  resistanceType: "Culturel Migratrice hivernale. Symbole de voyage et de liberté dans les chants traditionnels. Habitat: mangroves (Barraud 1994).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Migratrice hivernale. Symbole de voyage et de liberté dans les chants traditionnels. Habitat: mangroves (Barraud 1994).",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "culturel-migratrice-hivernale.-symbole-de-voyage-et-de-liberté-dans-les-chants-traditionnels.-habitat:-mangroves-(barraud-1994)."],
  },
  {
  id: "ramy-griv-pat",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Ramyé griv",
  nomFrancais: "Pigeon à cou rouge",
  nomScientifique: "Patagioenas squamosa",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ DISPARU Disparu au XIXe siècle. Sa viande était sacrée chez les Kalinagos. Dernières observations à la Soufrière (archives MNHN, 1890).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ DISPARU",
  dimensionCulturelle: "Disparu au XIXe siècle. Sa viande était sacrée chez les Kalinagos. Dernières observations à la Soufrière (archives MNHN, 1890).",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "sacré-disparu-disparu-au-xixe-siècle.-sa-viande-était-sacrée-chez-les-kalinagos.-dernières-observations-à-la-soufrière-(archives-mnhn,-1890)."],
  },
  {
  id: "chout-kabrit-tyt",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Chouèt kabrit",
  nomFrancais: "Effraie des Antilles",
  nomScientifique: "Tyto glaucops",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Endémique des Petites Antilles. Associée à la sagesse nocturne dans le quimbois. Niche dans les grottes (ONF 2020). Statut UICN: VU.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Endémique des Petites Antilles. Associée à la sagesse nocturne dans le quimbois. Niche dans les grottes (ONF 2020). Statut UICN: VU.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "emblématique-endémique-des-petites-antilles.-associée-à-la-sagesse-nocturne-dans-le-quimbois.-niche-dans-les-grottes-(onf-2020).-statut-uicn:-vu."],
  },
  {
  id: "dab-hibou-tyt",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Dab / Hibou",
  nomFrancais: "Effraie de la Martinique",
  nomScientifique: "Tyto furcata",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Introduite historiquement. Son cri est un présage dans les croyances afro-guadeloupéennes (archives coloniales, 1850).",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "symbolique"],
  },
  {
  id: "bwa-fouy-buse-but",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Bwa fouyé (buse)",
  nomFrancais: "Buse de la Guadeloupe",
  nomScientifique: "Buteo ridgwayi",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique des Petites Antilles. Symbole de puissance chez les Kalinagos. Chasse les serpents (Barraud 1994). Statut UICN: EN.",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique des Petites Antilles. Symbole de puissance chez les Kalinagos. Chasse les serpents (Barraud 1994). Statut UICN: EN.",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "culturel-endémique-des-petites-antilles.-symbole-de-puissance-chez-les-kalinagos.-chasse-les-serpents-(barraud-1994).-statut-uicn:-en."],
  },
  {
  id: "ibis-rouj-eud",
  categorie: "OISEAUX SACRÉS",
  sousCategorie: "oiseau",
  nomCreole: "Ibis rouj",
  nomFrancais: "Ibis rouge",
  nomScientifique: "Eudocimus ruber",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Visiteur occasionnel. Associé aux marécages et aux esprits de l'eau (*dlo*). Plumes utilisées en quimbois (Lorvelec et al. 2017).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Visiteur occasionnel. Associé aux marécages et aux esprits de l'eau (*dlo*). Plumes utilisées en quimbois (Lorvelec et al. 2017).",
  tags: ["oiseaux sacrés", "oiseau", "resistance", "sacré", "ambivalent-visiteur-occasionnel.-associé-aux-marécages-et-aux-esprits-de-l'eau-(*dlo*).-plumes-utilisées-en-quimbois-(lorvelec-et-al.-2017)."],
  },
  {
  id: "igwann-vt-igwann-pyi-igu",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Igwann vèt / Igwann péyi",
  nomFrancais: "Iguane vert",
  nomScientifique: "Iguana iguana",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Animal totem des Arawaks. Chassé pendant des siècles, aujourd'hui protégé. Sa peau et ses œufs étaient utilisés dans les rituels amérindiens. Les iguanes de Petite-Terre (par centaines) sont vénérés comme gardiens de l'île.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Animal totem des Arawaks. Chassé pendant des siècles, aujourd'hui protégé. Sa peau et ses œufs étaient utilisés dans les rituels amérindiens. Les iguanes de Petite-Terre (par centaines) sont vénérés comme gardiens de l'île.",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "sacré-animal-totem-des-arawaks.-chassé-pendant-des-siècles,-aujourd'hui-protégé.-sa-peau-et-ses-œufs-étaient-utilisés-dans-les-rituels-amérindiens.-les-iguanes-de-petite-terre-(par-centaines)-sont-vénérés-comme-gardiens-de-l'île."],
  },
  {
  id: "igwann-pyi-igu",
  categorie: "ANIMAUX — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "reptile / résistance",
  nomCreole: "Igwann péyi",
  nomFrancais: "Iguane des Petites Antilles",
  nomScientifique: "Iguana delicatissima",
  isResistanceSymbol: true,
  resistanceType: "TOTEM",
  resistanceDescription: undefined,
  sacreSymbolique: "TOTEM DE RÉSISTANCE",
  dimensionCulturelle: "Animal totem des Arawaks. Symbole de sagesse et de persévérance. Les esclaves marrons s'identifiaient à lui : immobile et invisible dans la forêt, il sait attendre, observer et survivre. Sa couleur qui se fond dans le décor est une métaphore du marronage.",
  tags: ["animaux — symboles de résistance", "reptile / résistance", "resistance", "sacré", "totem"],
  },
  {
  id: "zandoli-anoli-ano",
  categorie: "ANIMAUX — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "reptile / résistance",
  nomCreole: "Zandoli / Anoli",
  nomFrancais: "Anoli marbré",
  nomScientifique: "Anolis marmoratus",
  isResistanceSymbol: true,
  resistanceType: "TOTEM",
  resistanceDescription: undefined,
  sacreSymbolique: "TOTEM DE RÉSISTANCE",
  dimensionCulturelle: "Symbole de résilience et de liberté dans la culture créole. Présent sur chaque île avec une sous-espèce différente — il s'est adapté à chaque territoire comme les Guadeloupéens ont su s'adapter à chaque épreuve. Impossible à capturer durablement : il lâche sa queue et repart.",
  tags: ["animaux — symboles de résistance", "reptile / résistance", "resistance", "sacré", "totem"],
  },
  {
  id: "mabouya-the",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Mabouya",
  nomFrancais: "Mabouya / Gecko nocturne",
  nomScientifique: "Thecadactylus rapicauda",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Lézard nocturne des murs et des cases. Considéré à tort comme dangereux dans les croyances populaires. Dans le quimbois, il est à la fois craint et utilisé dans certains rituels nocturnes. Son nom « mabouya » désignait le dieu du mal chez les Kalinagos.",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Lézard nocturne des murs et des cases. Considéré à tort comme dangereux dans les croyances populaires. Dans le quimbois, il est à la fois craint et utilisé dans certains rituels nocturnes. Son nom « mabouya » désignait le dieu du mal chez les Kalinagos.",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "ambivalent-lézard-nocturne-des-murs-et-des-cases.-considéré-à-tort-comme-dangereux-dans-les-croyances-populaires.-dans-le-quimbois,-il-est-à-la-fois-craint-et-utilisé-dans-certains-rituels-nocturnes.-son-nom-«-mabouya-»-désignait-le-dieu-du-mal-chez-les-kalinagos."],
  },
  {
  id: "koures-couresse-als",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Koures / Couresse",
  nomFrancais: "Couresse de Guadeloupe",
  nomScientifique: "Alsophis antillensis",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Couleuvre inoffensive endémique. La couresse des Saintes est endémique de cet archipel uniquement. Dans la tradition créole, le serpent non-venimeux est un gardien du jardin et des réserves.",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "symbolique"],
  },
  {
  id: "kwikwi-amp",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Kwikwi",
  nomFrancais: "Amphisbaène",
  nomScientifique: "Amphisbaena martinicensis",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Reptile apode endémique. Sa présence dans les jardins est un signe de terre fertile (quimbois). Habitat: sols humides (Barraud 1994, MNHN).",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Reptile apode endémique. Sa présence dans les jardins est un signe de terre fertile (quimbois). Habitat: sols humides (Barraud 1994, MNHN).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "emblématique-reptile-apode-endémique.-sa-présence-dans-les-jardins-est-un-signe-de-terre-fertile-(quimbois).-habitat:-sols-humides-(barraud-1994,-mnhn)."],
  },
  {
  id: "lza-moun-gym",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Léza moun",
  nomFrancais: "Gymnophtalme d'Underwood",
  nomScientifique: "Gymnophtalmus underwoodi",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduit. Associé à la discrétion (marronnage). Habitat: zones rocheuses (Faune Guadeloupe 2022).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduit. Associé à la discrétion (marronnage). Habitat: zones rocheuses (Faune Guadeloupe 2022).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "ambivalent-introduit.-associé-à-la-discrétion-(marronnage).-habitat:-zones-rocheuses-(faune-guadeloupe-2022)."],
  },
  {
  id: "serpan-moun-chi",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Serpan moun",
  nomFrancais: "Boa de la Guadeloupe",
  nomScientifique: "Chilabothrus inornatus",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Endémique. Non venimeux. Associé à la force vitale (*ki*) dans les cosmogonies amérindiennes (Boucher 2008). Statut UICN: VU.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Endémique. Non venimeux. Associé à la force vitale (*ki*) dans les cosmogonies amérindiennes (Boucher 2008). Statut UICN: VU.",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "emblématique-endémique.-non-venimeux.-associé-à-la-force-vitale-(*ki*)-dans-les-cosmogonies-amérindiennes-(boucher-2008).-statut-uicn:-vu."],
  },
  {
  id: "geko-pi-sph",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Geko pi",
  nomFrancais: "Sphaérodactyle de Parker",
  nomScientifique: "Sphaerodactylus parkeri",
  isResistanceSymbol: true,
  resistanceType: "Culturel Mini-reptile endémique. Présent dans les maisons, considéré comme porte-bonheur (tradition créole).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Mini-reptile endémique. Présent dans les maisons, considéré comme porte-bonheur (tradition créole).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "culturel-mini-reptile-endémique.-présent-dans-les-maisons,-considéré-comme-porte-bonheur-(tradition-créole)."],
  },
  {
  id: "zandoli-gwo-ame",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Zandoli gwo",
  nomFrancais: "Ameiva de la Guadeloupe",
  nomScientifique: "Ameiva cinereus",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Chassé pour sa viande. Symbole de rapidité et de ruse (Lorvelec et al. 2017).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Chassé pour sa viande. Symbole de rapidité et de ruse (Lorvelec et al. 2017).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "culturel-endémique.-chassé-pour-sa-viande.-symbole-de-rapidité-et-de-ruse-(lorvelec-et-al.-2017)."],
  },
  {
  id: "tarente-hem",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Tarente",
  nomFrancais: "Tarente de Guadeloupe",
  nomScientifique: "Hemidactylus mabouia",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduite. Associée aux murs des cases créoles. Utilisée dans les sorts de protection (quimbois).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduite. Associée aux murs des cases créoles. Utilisée dans les sorts de protection (quimbois).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "ambivalent-introduite.-associée-aux-murs-des-cases-créoles.-utilisée-dans-les-sorts-de-protection-(quimbois)."],
  },
  {
  id: "krokod-cro",
  categorie: "REPTILES SACRÉS",
  sousCategorie: "reptile",
  nomCreole: "Krokod",
  nomFrancais: "Caïman de la Guadeloupe",
  nomScientifique: "Crocodylus acutus",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ DISPARU Disparu au XVIIIe siècle. Symbole de puissance dans les mythes kalinagos. Os utilisés comme talismans (archives MNHN).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ DISPARU",
  dimensionCulturelle: "Disparu au XVIIIe siècle. Symbole de puissance dans les mythes kalinagos. Os utilisés comme talismans (archives MNHN).",
  tags: ["reptiles sacrés", "reptile", "resistance", "sacré", "sacré-disparu-disparu-au-xviiie-siècle.-symbole-de-puissance-dans-les-mythes-kalinagos.-os-utilisés-comme-talismans-(archives-mnhn)."],
  },
  {
  id: "gouti-das",
  categorie: "ANIMAUX — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "mammifère / résistance",
  nomCreole: "Gouti",
  nomFrancais: "Agouti doré",
  nomScientifique: "Dasyprocta leporina",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE",
  resistanceDescription: undefined,
  sacreSymbolique: "RÉSISTANCE",
  dimensionCulturelle: "Introduit par les Arawaks eux-mêmes bien avant la colonisation. Survit dans la forêt malgré des siècles de chasse. Symbole de la continuité amérindienne et de la capacité à se nourrir en dehors du système colonial.",
  tags: ["animaux — symboles de résistance", "mammifère / résistance", "resistance", "sacré", "résistance"],
  },
  {
  id: "raton-laveur-racoon-pro",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Raton laveur / Racoon",
  nomFrancais: "Raton laveur de Guadeloupe",
  nomScientifique: "Procyon minor",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Symbole officiel du Parc National de la Guadeloupe. Animal nocturne intelligent. Sa présence est signe d'un écosystème forestier sain.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Symbole officiel du Parc National de la Guadeloupe. Animal nocturne intelligent. Sa présence est signe d'un écosystème forestier sain.",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "emblématique-symbole-officiel-du-parc-national-de-la-guadeloupe.-animal-nocturne-intelligent.-sa-présence-est-signe-d'un-écosystème-forestier-sain."],
  },
  {
  id: "guimbo-chauve-souris-13",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Guimbo / Chauve-souris",
  nomFrancais: "Chauves-souris",
  nomScientifique: "13 espèces (8 endémiques)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ AMBIVALENT Dans le quimbois, la chauve-souris est l'animal de la nuit, du passage entre deux mondes. Le gadèzafé utilise certains de ses organes dans ses préparations. Associée aux zombis et aux esprits errants dans les croyances créoles.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ AMBIVALENT",
  dimensionCulturelle: "Dans le quimbois, la chauve-souris est l'animal de la nuit, du passage entre deux mondes. Le gadèzafé utilise certains de ses organes dans ses préparations. Associée aux zombis et aux esprits errants dans les croyances créoles.",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "sacré-ambivalent-dans-le-quimbois,-la-chauve-souris-est-l'animal-de-la-nuit,-du-passage-entre-deux-mondes.-le-gadèzafé-utilise-certains-de-ses-organes-dans-ses-préparations.-associée-aux-zombis-et-aux-esprits-errants-dans-les-croyances-créoles."],
  },
  {
  id: "baln-meg",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Balèn",
  nomFrancais: "Baleine à bosse",
  nomScientifique: "Megaptera novaeangliae",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Les Kalinagos considéraient les grandes baleines comme des ancêtres revenus sous forme marine. Les pêcheurs créoles leur accordent un respect profond — les tuer porte malheur.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Les Kalinagos considéraient les grandes baleines comme des ancêtres revenus sous forme marine. Les pêcheurs créoles leur accordent un respect profond — les tuer porte malheur.",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "sacré-les-kalinagos-considéraient-les-grandes-baleines-comme-des-ancêtres-revenus-sous-forme-marine.-les-pêcheurs-créoles-leur-accordent-un-respect-profond-—-les-tuer-porte-malheur."],
  },
  {
  id: "manman-dlo-lamantin-tri",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Manman dlo / Lamantin",
  nomFrancais: "Lamantin des Caraïbes",
  nomScientifique: "Trichechus manatus",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ MYTHIQUE Mammifère marin à l'origine des légendes de sirènes dans toute la Caraïbe. Les Arawaks le considéraient comme un être de passage entre le monde aquatique et humain. Aujourd'hui espèce protégée en grand danger.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ MYTHIQUE",
  dimensionCulturelle: "Mammifère marin à l'origine des légendes de sirènes dans toute la Caraïbe. Les Arawaks le considéraient comme un être de passage entre le monde aquatique et humain. Aujourd'hui espèce protégée en grand danger.",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "sacré-mythique-mammifère-marin-à-l'origine-des-légendes-de-sirènes-dans-toute-la-caraïbe.-les-arawaks-le-considéraient-comme-un-être-de-passage-entre-le-monde-aquatique-et-humain.-aujourd'hui-espèce-protégée-en-grand-danger."],
  },
  {
  id: "mangouste-mongos-her",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Mangouste / Mongos",
  nomFrancais: "Mangouste indienne",
  nomScientifique: "Herpestes javanicus",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduite en 1887 pour lutter contre les rats. Devenue invasive. Symbole de ruse (Lorvelec et al. 2017).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduite en 1887 pour lutter contre les rats. Devenue invasive. Symbole de ruse (Lorvelec et al. 2017).",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "ambivalent-introduite-en-1887-pour-lutter-contre-les-rats.-devenue-invasive.-symbole-de-ruse-(lorvelec-et-al.-2017)."],
  },
  {
  id: "rat-nw-rat",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Rat nwè",
  nomFrancais: "Rat noir",
  nomScientifique: "Rattus rattus",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduit avec les navires européens. Associé aux épidémies et aux sorts de malchance (quimbois).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduit avec les navires européens. Associé aux épidémies et aux sorts de malchance (quimbois).",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "ambivalent-introduit-avec-les-navires-européens.-associé-aux-épidémies-et-aux-sorts-de-malchance-(quimbois)."],
  },
  {
  id: "souris-lafimi-mus",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Souris lafimi",
  nomFrancais: "Souris domestique",
  nomScientifique: "Mus musculus",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Introduite. Utilisée dans les rituels de divination (tradition afro-guadeloupéenne).",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "symbolique"],
  },
  {
  id: "chauv-souris-frwi-art",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Chauv-souris frwi",
  nomFrancais: "Chauve-souris frugivore",
  nomScientifique: "Artibeus jamaicensis",
  isResistanceSymbol: true,
  resistanceType: "Culturel Pollinise les fruits. Symbole de connexion entre les mondes (Kalinago).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Pollinise les fruits. Symbole de connexion entre les mondes (Kalinago).",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "culturel-pollinise-les-fruits.-symbole-de-connexion-entre-les-mondes-(kalinago)."],
  },
  {
  id: "tatou-das",
  categorie: "MAMMIFÈRES",
  sousCategorie: "mammifère",
  nomCreole: "Tatou",
  nomFrancais: "Tatou à neuf bandes",
  nomScientifique: "Dasypus novemcinctus",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Introduit. Associé à la protection (carapace utilisée comme talisman). Habitat: zones sèches (ONF).",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Introduit. Associé à la protection (carapace utilisée comme talisman). Habitat: zones sèches (ONF).",
  tags: ["mammifères", "mammifère", "resistance", "sacré", "emblématique-introduit.-associé-à-la-protection-(carapace-utilisée-comme-talisman).-habitat:-zones-sèches-(onf)."],
  },
  {
  id: "chauv-souris-frwi-bra",
  categorie: "MAMMIFÈRES",
  sousCategorie: "chauve-souris",
  nomCreole: "Chauv-souris frwi",
  nomFrancais: "Brachyphylle de Guadeloupe",
  nomScientifique: "Brachyphylla cavernarum",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Endémique. Pollinise les fruits sacrés (*corossol*). Associée aux grottes et aux esprits (MNHN). Statut UICN: NT.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Endémique. Pollinise les fruits sacrés (*corossol*). Associée aux grottes et aux esprits (MNHN). Statut UICN: NT.",
  tags: ["mammifères", "chauve-souris", "resistance", "sacré", "sacré-endémique.-pollinise-les-fruits-sacrés-(*corossol*).-associée-aux-grottes-et-aux-esprits-(mnhn).-statut-uicn:-nt."],
  },
  {
  id: "chauv-souris-grise-mor",
  categorie: "MAMMIFÈRES",
  sousCategorie: "chauve-souris",
  nomCreole: "Chauv-souris grise",
  nomFrancais: "Mormoops de la Guadeloupe",
  nomScientifique: "Mormoops megalophylla",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Chasse les insectes nuisibles. Symbole de purification nocturne (quimbois).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Chasse les insectes nuisibles. Symbole de purification nocturne (quimbois).",
  tags: ["mammifères", "chauve-souris", "resistance", "sacré", "culturel-endémique.-chasse-les-insectes-nuisibles.-symbole-de-purification-nocturne-(quimbois)."],
  },
  {
  id: "chauv-souris-swif-mol",
  categorie: "MAMMIFÈRES",
  sousCategorie: "chauve-souris",
  nomCreole: "Chauv-souris swif",
  nomFrancais: "Molosse de la Guadeloupe",
  nomScientifique: "Molossus molossus",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Visiteur occasionnel. Associé à la vitesse et à la protection des récoltes (tradition agricole).",
  tags: ["mammifères", "chauve-souris", "resistance", "sacré", "symbolique"],
  },
  {
  id: "chauv-souris-ti-nat",
  categorie: "MAMMIFÈRES",
  sousCategorie: "chauve-souris",
  nomCreole: "Chauv-souris ti",
  nomFrancais: "Natalus de la Guadeloupe",
  nomScientifique: "Natalus stramineus",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Endémique. Niche dans les grottes. Symbole de discrétion (marronnage). Statut UICN: VU (Lorvelec et al. 2017).",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Endémique. Niche dans les grottes. Symbole de discrétion (marronnage). Statut UICN: VU (Lorvelec et al. 2017).",
  tags: ["mammifères", "chauve-souris", "resistance", "sacré", "emblématique-endémique.-niche-dans-les-grottes.-symbole-de-discrétion-(marronnage).-statut-uicn:-vu-(lorvelec-et-al.-2017)."],
  },
  {
  id: "chauv-souris-sak-sac",
  categorie: "MAMMIFÈRES",
  sousCategorie: "chauve-souris",
  nomCreole: "Chauv-souris sak",
  nomFrancais: "Saccopteryx de Guadeloupe",
  nomScientifique: "Saccopteryx bilineata",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Associée aux rituels de chasse nocturne (Kalinago). Habitat: forêts humides (GBIF).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Associée aux rituels de chasse nocturne (Kalinago). Habitat: forêts humides (GBIF).",
  tags: ["mammifères", "chauve-souris", "resistance", "sacré", "culturel-endémique.-associée-aux-rituels-de-chasse-nocturne-(kalinago).-habitat:-forêts-humides-(gbif)."],
  },
  {
  id: "tti-vt-tortue-verte-che",
  categorie: "TORTUES MARINES",
  sousCategorie: "tortue marine",
  nomCreole: "Tòti vèt / Tortue verte",
  nomFrancais: "Tortue verte",
  nomScientifique: "Chelonia mydas",
  isResistanceSymbol: true,
  resistanceType: "SACRÉE Animal totem des peuples amérindiens de la Caraïbe. Symbole de longévité, de fertilité et de sagesse. Ses herbiers sous-marins sont des lieux de vie sacrés. Protégée depuis 1991.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉE",
  dimensionCulturelle: "Animal totem des peuples amérindiens de la Caraïbe. Symbole de longévité, de fertilité et de sagesse. Ses herbiers sous-marins sont des lieux de vie sacrés. Protégée depuis 1991.",
  tags: ["tortues marines", "tortue marine", "resistance", "sacré", "sacrée-animal-totem-des-peuples-amérindiens-de-la-caraïbe.-symbole-de-longévité,-de-fertilité-et-de-sagesse.-ses-herbiers-sous-marins-sont-des-lieux-de-vie-sacrés.-protégée-depuis-1991."],
  },
  {
  id: "tti-kar-caret-ere",
  categorie: "TORTUES MARINES",
  sousCategorie: "tortue marine",
  nomCreole: "Tòti karé / Caret",
  nomFrancais: "Tortue imbriquée",
  nomScientifique: "Eretmochelys imbricata",
  isResistanceSymbol: true,
  resistanceType: "SACRÉE Carapace en écailles (l'écaille de tortue) utilisée dans les parures amérindiennes rituelles. Vient pondre sur les plages du nord de Grande-Terre. Espèce en danger critique.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉE",
  dimensionCulturelle: "Carapace en écailles (l'écaille de tortue) utilisée dans les parures amérindiennes rituelles. Vient pondre sur les plages du nord de Grande-Terre. Espèce en danger critique.",
  tags: ["tortues marines", "tortue marine", "resistance", "sacré", "sacrée-carapace-en-écailles-(l'écaille-de-tortue)-utilisée-dans-les-parures-amérindiennes-rituelles.-vient-pondre-sur-les-plages-du-nord-de-grande-terre.-espèce-en-danger-critique."],
  },
  {
  id: "tti-luth-grandluth-der",
  categorie: "TORTUES MARINES",
  sousCategorie: "tortue marine",
  nomCreole: "Tòti luth / Grand'luth",
  nomFrancais: "Tortue luth",
  nomScientifique: "Dermochelys coriacea",
  isResistanceSymbol: true,
  resistanceType: "SACRÉE Plus grande tortue du monde (jusqu'à 700 kg). La voir émerger de la mer de nuit pour pondre est considéré comme un événement spirituel majeur dans les communautés côtières.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉE",
  dimensionCulturelle: "Plus grande tortue du monde (jusqu'à 700 kg). La voir émerger de la mer de nuit pour pondre est considéré comme un événement spirituel majeur dans les communautés côtières.",
  tags: ["tortues marines", "tortue marine", "resistance", "sacré", "sacrée-plus-grande-tortue-du-monde-(jusqu'à-700-kg).-la-voir-émerger-de-la-mer-de-nuit-pour-pondre-est-considéré-comme-un-événement-spirituel-majeur-dans-les-communautés-côtières."],
  },
  {
  id: "grenn-bwa-hylode-ele",
  categorie: "AMPHIBIENS",
  sousCategorie: "amphibien",
  nomCreole: "Grenn-bwa / Hylode",
  nomFrancais: "Hylode de Barlagne",
  nomScientifique: "Eleutherodactylus barlagnei",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Endémique de Basse-Terre uniquement. Son chant nocturne berce les nuits guadeloupéennes. Dans la tradition créole, le silence soudain des grenouilles annonce un danger ou la présence d'un esprit.",
  tags: ["amphibiens", "amphibien", "resistance", "sacré", "symbolique"],
  },
  {
  id: "krapo-crapaud-buffle-rhi",
  categorie: "AMPHIBIENS",
  sousCategorie: "amphibien",
  nomCreole: "Krapo / Crapaud buffle",
  nomFrancais: "Crapaud buf",
  nomScientifique: "Rhinella marina",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Utilisé dans certains rituels du quimbois pour ses sécrétions psychoactives (bufoténine). Associé aux rituels ancestraux et aux préparations des gadèzafé.",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Utilisé dans certains rituels du quimbois pour ses sécrétions psychoactives (bufoténine). Associé aux rituels ancestraux et aux préparations des gadèzafé.",
  tags: ["amphibiens", "amphibien", "resistance", "sacré", "ambivalent-utilisé-dans-certains-rituels-du-quimbois-pour-ses-sécrétions-psychoactives-(bufoténine).-associé-aux-rituels-ancestraux-et-aux-préparations-des-gadèzafé."],
  },
  {
  id: "rainett-ka-boa",
  categorie: "AMPHIBIENS",
  sousCategorie: "amphibien",
  nomCreole: "Rainett ka",
  nomFrancais: "Rainette de la Guadeloupe",
  nomScientifique: "Boana grenadensis",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Son chant est un indicateur de pluie (tradition agricole). Habitat: zones humides (Breuil 2002).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Son chant est un indicateur de pluie (tradition agricole). Habitat: zones humides (Breuil 2002).",
  tags: ["amphibiens", "amphibien", "resistance", "sacré", "culturel-endémique.-son-chant-est-un-indicateur-de-pluie-(tradition-agricole).-habitat:-zones-humides-(breuil-2002)."],
  },
  {
  id: "krap-dlo-lep",
  categorie: "AMPHIBIENS",
  sousCategorie: "amphibien",
  nomCreole: "Krapò dlo",
  nomFrancais: "Grenouille des Antilles",
  nomScientifique: "Leptodactylus fallax",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Endémique. Associée aux sources d'eau sacrées (*dlo*). Menacée par la chytridiomycose (UICN VU).",
  tags: ["amphibiens", "amphibien", "resistance", "sacré", "symbolique"],
  },
  {
  id: "grenouy-venim-den",
  categorie: "AMPHIBIENS",
  sousCategorie: "amphibien",
  nomCreole: "Grenouy venim",
  nomFrancais: "Grenouille venimeuse",
  nomScientifique: "Dendrobates tinctorius",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Introduite (Guyane). Toxine utilisée pour empoisonner les flèches (Kalinago). Symbole de danger (Barraud 1994).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Introduite (Guyane). Toxine utilisée pour empoisonner les flèches (Kalinago). Symbole de danger (Barraud 1994).",
  tags: ["amphibiens", "amphibien", "resistance", "sacré", "sacré-introduite-(guyane).-toxine-utilisée-pour-empoisonner-les-flèches-(kalinago).-symbole-de-danger-(barraud-1994)."],
  },
  {
  id: "krab-t-crabe-de-terre-car",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Krab tè / Crabe de terre",
  nomFrancais: "Crabe de terre",
  nomScientifique: "Cardisoma guanhumi",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ CULTUREL Animal central de la culture guadeloupéenne. Le matoutou (fricassée de crabes) est le plat du lundi de Pâques. La fête du crabe après Pâques est un rituel collectif ancré. Nourriture sacrée du retour du printemps.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ CULTUREL",
  dimensionCulturelle: "Animal central de la culture guadeloupéenne. Le matoutou (fricassée de crabes) est le plat du lundi de Pâques. La fête du crabe après Pâques est un rituel collectif ancré. Nourriture sacrée du retour du printemps.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "sacré-culturel-animal-central-de-la-culture-guadeloupéenne.-le-matoutou-(fricassée-de-crabes)-est-le-plat-du-lundi-de-pâques.-la-fête-du-crabe-après-pâques-est-un-rituel-collectif-ancré.-nourriture-sacrée-du-retour-du-printemps."],
  },
  {
  id: "touloulou-itouloulou-gec",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Touloulou / Itouloulou",
  nomFrancais: "Crabe touloulou",
  nomScientifique: "Gecarcinus lateralis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ CULTUREL Petit crabe rouge du bord de mer. Son nom créole « itouloulou » est directement hérité des Kalinagos. Il a donné son nom aux femmes masquées du carnaval (les touloulous de Cayenne). Symbole de la résistance féminine.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ CULTUREL",
  dimensionCulturelle: "Petit crabe rouge du bord de mer. Son nom créole « itouloulou » est directement hérité des Kalinagos. Il a donné son nom aux femmes masquées du carnaval (les touloulous de Cayenne). Symbole de la résistance féminine.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "sacré-culturel-petit-crabe-rouge-du-bord-de-mer.-son-nom-créole-«-itouloulou-»-est-directement-hérité-des-kalinagos.-il-a-donné-son-nom-aux-femmes-masquées-du-carnaval-(les-touloulous-de-cayenne).-symbole-de-la-résistance-féminine."],
  },
  {
  id: "sirik-cirique-gra",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Sirik / Cirique",
  nomFrancais: "Crabe des rochers",
  nomScientifique: "Grapsus grapsus",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Crabe des rochers côtiers aux pinces redoutables. Nom d'origine amérindienne conservé intact. Animal de la frontière entre mer et terre.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "symbolique"],
  },
  {
  id: "zachari-zagalliac-esp",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Zachari / Zagalliac",
  nomFrancais: "Zagalliac / Crabe de mer",
  nomScientifique: "(espèce locale)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Nom intégralement conservé de la langue kalinago. Crabe de bord de mer emblématique.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "symbolique"],
  },
  {
  id: "wasou-ouassou-mac",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Wasou / Ouassou",
  nomFrancais: "Crevette d'eau douce",
  nomScientifique: "Macrobrachium rosenbergii",
  isResistanceSymbol: true,
  resistanceType: "Culturel Crevette géante des rivières de Basse-Terre. Pêchée dans les rivières sacrées. Cuisine créole incontournable.",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Crevette géante des rivières de Basse-Terre. Pêchée dans les rivières sacrées. Cuisine créole incontournable.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "culturel-crevette-géante-des-rivières-de-basse-terre.-pêchée-dans-les-rivières-sacrées.-cuisine-créole-incontournable."],
  },
  {
  id: "langous-pan",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Langous",
  nomFrancais: "Langouste des Caraïbes",
  nomScientifique: "Panulirus argus",
  isResistanceSymbol: true,
  resistanceType: "Culturel Symbole de la pêche artisanale. Sa pêche est un rite saisonnier très encadré. Partagée lors des grandes occasions familiales.",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Symbole de la pêche artisanale. Sa pêche est un rite saisonnier très encadré. Partagée lors des grandes occasions familiales.",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "culturel-symbole-de-la-pêche-artisanale.-sa-pêche-est-un-rite-saisonnier-très-encadré.-partagée-lors-des-grandes-occasions-familiales."],
  },
  {
  id: "krab-rivy-pot",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Krab rivyè",
  nomFrancais: "Crabe de rivière",
  nomScientifique: "Potamon guadeloupensis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ ENDÉMIQUE Endémique des rivières de Basse-Terre. Utilisé dans les rituels de purification de l'eau (*gadèzafé*). Statut UICN: EN (INPN 2020).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ ENDÉMIQUE",
  dimensionCulturelle: "Endémique des rivières de Basse-Terre. Utilisé dans les rituels de purification de l'eau (*gadèzafé*). Statut UICN: EN (INPN 2020).",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "sacré-endémique-endémique-des-rivières-de-basse-terre.-utilisé-dans-les-rituels-de-purification-de-l'eau-(*gadèzafé*).-statut-uicn:-en-(inpn-2020)."],
  },
  {
  id: "krab-moun-gec",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Krab moun",
  nomFrancais: "Crabe de terre",
  nomScientifique: "Gecarcinus ruricola",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Symbole de résistance (marronnage). Habitat: forêts humides (Barraud 1994).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Symbole de résistance (marronnage). Habitat: forêts humides (Barraud 1994).",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "culturel-endémique.-symbole-de-résistance-(marronnage).-habitat:-forêts-humides-(barraud-1994)."],
  },
  {
  id: "krab-bdlanm-uci",
  categorie: "CRUSTACÉS SACRÉS",
  sousCategorie: "crustacé",
  nomCreole: "Krab bòdlanmè",
  nomFrancais: "Crabe violoneux",
  nomScientifique: "Ucides cordatus",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Présent dans les mangroves. Associé à la protection des côtes (tradition kalinago).",
  tags: ["crustacés sacrés", "crustacé", "resistance", "sacré", "symbolique"],
  },
  {
  id: "myl-abeille-pyi-api",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Myèl / Abeille péyi",
  nomFrancais: "Abeille domestique",
  nomScientifique: "Apis mellifera",
  isResistanceSymbol: true,
  resistanceType: "SACRÉE Le miel est utilisé dans les offrandes, les bains rituels et les préparations médicinales du quimbois. Dans la tradition africaine, l'abeille est messagère entre les vivants et les ancêtres. Essaim entrant dans une maison = signe de chance ou d'arrivée d'un esprit.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉE",
  dimensionCulturelle: "Le miel est utilisé dans les offrandes, les bains rituels et les préparations médicinales du quimbois. Dans la tradition africaine, l'abeille est messagère entre les vivants et les ancêtres. Essaim entrant dans une maison = signe de chance ou d'arrivée d'un esprit.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacrée-le-miel-est-utilisé-dans-les-offrandes,-les-bains-rituels-et-les-préparations-médicinales-du-quimbois.-dans-la-tradition-africaine,-l'abeille-est-messagère-entre-les-vivants-et-les-ancêtres.-essaim-entrant-dans-une-maison-=-signe-de-chance-ou-d'arrivée-d'un-esprit."],
  },
  {
  id: "foumi-manyok-acr",
  categorie: "ANIMAUX — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "insecte / résistance",
  nomCreole: "Foumi manyok",
  nomFrancais: "Fourmi manioc",
  nomScientifique: "Acromyrmex octospinosus",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE",
  resistanceDescription: undefined,
  sacreSymbolique: "RÉSISTANCE COLLECTIVE",
  dimensionCulturelle: "Colonie organisée, invisible, travaillant dans l'ombre et construisant sans relâche. Symbole de la résistance collective et silencieuse des esclaves. Les anciens disaient : « Foumi ka travay, foumi ka manyé » — la fourmi travaille, la fourmi mange.",
  tags: ["animaux — symboles de résistance", "insecte / résistance", "resistance", "sacré", "résistance"],
  },
  {
  id: "kabribo-cabrit-bois-esp",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Kabribo / Cabrit-bois",
  nomFrancais: "Grillon des bois",
  nomScientifique: "(espèce locale Gryllidae)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ NOCTURNE Grande sauterelle dont le chant berce les nuits antillaises. Son silence subit est dans la tradition créole le signe d'une présence surnaturelle — esprit, zombie ou gadèzafé qui passe. Les anciens écoutent les cabrit-bois pour « lire » la nuit.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ NOCTURNE",
  dimensionCulturelle: "Grande sauterelle dont le chant berce les nuits antillaises. Son silence subit est dans la tradition créole le signe d'une présence surnaturelle — esprit, zombie ou gadèzafé qui passe. Les anciens écoutent les cabrit-bois pour « lire » la nuit.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacré-nocturne-grande-sauterelle-dont-le-chant-berce-les-nuits-antillaises.-son-silence-subit-est-dans-la-tradition-créole-le-signe-d'une-présence-surnaturelle-—-esprit,-zombie-ou-gadèzafé-qui-passe.-les-anciens-écoutent-les-cabrit-bois-pour-«-lire-»-la-nuit."],
  },
  {
  id: "luciole-ti-flambeau-lam",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Luciole / Ti flambeau",
  nomFrancais: "Luciole",
  nomScientifique: "(Lampyridae spp.)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉE Insecte lumineux de la nuit tropicale. Dans la tradition créole, les lucioles sont les âmes des enfants morts sans baptême qui errent dans les mornes. Les voir danser en groupe est un signe de présence des ancêtres.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉE",
  dimensionCulturelle: "Insecte lumineux de la nuit tropicale. Dans la tradition créole, les lucioles sont les âmes des enfants morts sans baptême qui errent dans les mornes. Les voir danser en groupe est un signe de présence des ancêtres.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacrée-insecte-lumineux-de-la-nuit-tropicale.-dans-la-tradition-créole,-les-lucioles-sont-les-âmes-des-enfants-morts-sans-baptême-qui-errent-dans-les-mornes.-les-voir-danser-en-groupe-est-un-signe-de-présence-des-ancêtres."],
  },
  {
  id: "mouche-miel-gupe-pyi-pol",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Mouche à miel / Guêpe péyi",
  nomFrancais: "Guêpe des Antilles",
  nomScientifique: "Polybia spp.",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Son nid en papier mâché suspendu est un avertissement : y toucher sans rituel de protection attire les mauvais sorts. Les gadèzafé prélèvent parfois le nid vide pour des préparations.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "papillon-nw-mariposa-her",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Papillon nwè / Mariposa",
  nomFrancais: "Grand papillon noir",
  nomScientifique: "Heraclides andraemon",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Dans la tradition créole, un grand papillon noir entrant dans la maison est l'âme d'un ancêtre défunt venu rendre visite. On ne le chasse jamais. Lui faire mal attire le malheur sur la famille.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Dans la tradition créole, un grand papillon noir entrant dans la maison est l'âme d'un ancêtre défunt venu rendre visite. On ne le chasse jamais. Lui faire mal attire le malheur sur la famille.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacré-dans-la-tradition-créole,-un-grand-papillon-noir-entrant-dans-la-maison-est-l'âme-d'un-ancêtre-défunt-venu-rendre-visite.-on-ne-le-chasse-jamais.-lui-faire-mal-attire-le-malheur-sur-la-famille."],
  },
  {
  id: "papillon-transparent-gre",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Papillon transparent",
  nomFrancais: "Papillon aux ailes transparentes",
  nomScientifique: "Greta oto (et espèces locales)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Papillon rare aux ailes de verre. Associé dans la tradition créole à la transparence entre le monde des vivants et celui des esprits.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ravt-per",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Ravèt",
  nomFrancais: "Cafard / Blatte",
  nomScientifique: "Periplaneta americana",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Animal du quotidien créole au fort symbolisme négatif — sa présence dans la maison signale un manque de protection spirituelle. Dans le quimbois, il est utilisé dans certains sorts de nuisance.",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Animal du quotidien créole au fort symbolisme négatif — sa présence dans la maison signale un manque de protection spirituelle. Dans le quimbois, il est utilisé dans certains sorts de nuisance.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "ambivalent-animal-du-quotidien-créole-au-fort-symbolisme-négatif-—-sa-présence-dans-la-maison-signale-un-manque-de-protection-spirituelle.-dans-le-quimbois,-il-est-utilisé-dans-certains-sorts-de-nuisance."],
  },
  {
  id: "myg-mygale-de-la-soufrire-cyr",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Myg / Mygale de la Soufrière",
  nomFrancais: "Mygale de la Soufrière",
  nomScientifique: "Cyrtopholis guadeloupensis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ ENDÉMIQUE Araignée endémique découverte en 1999 dans les hauteurs du volcan. Gardienne des hauteurs de la Soufrière. Sa rareté et son habitat volcanique lui confèrent un statut de créature de l'entre-deux-mondes dans les croyances locales.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ ENDÉMIQUE",
  dimensionCulturelle: "Araignée endémique découverte en 1999 dans les hauteurs du volcan. Gardienne des hauteurs de la Soufrière. Sa rareté et son habitat volcanique lui confèrent un statut de créature de l'entre-deux-mondes dans les croyances locales.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacré-endémique-araignée-endémique-découverte-en-1999-dans-les-hauteurs-du-volcan.-gardienne-des-hauteurs-de-la-soufrière.-sa-rareté-et-son-habitat-volcanique-lui-confèrent-un-statut-de-créature-de-l'entre-deux-mondes-dans-les-croyances-locales."],
  },
  {
  id: "bef-scarabe-sacr-can",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Bef / Scarabée sacré",
  nomFrancais: "Bousier tropical",
  nomScientifique: "Canthon spp.",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Insecte qui roule des boules de matière organique — symbole de régénération dans les traditions africaines importées. Associé à la roue de la vie dans la spiritualité créole syncrétique.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "milpat-rha",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Milpat",
  nomFrancais: "Mille-pattes géant",
  nomScientifique: "Rhachidesmus guadeloupensis",
  isResistanceSymbol: true,
  resistanceType: "Culturel Endémique. Utilisé dans les remèdes traditionnels contre les morsures de serpent (quimbois).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Endémique. Utilisé dans les remèdes traditionnels contre les morsures de serpent (quimbois).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-endémique.-utilisé-dans-les-remèdes-traditionnels-contre-les-morsures-de-serpent-(quimbois)."],
  },
  {
  id: "zandoli-piq-cen",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Zandoli piq",
  nomFrancais: "Scorpion de la Guadeloupe",
  nomScientifique: "Centruroides guadeloupensis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Endémique. Venin utilisé en médecine traditionnelle (douleur). Symbole de protection (Boucher 2008).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Endémique. Venin utilisé en médecine traditionnelle (douleur). Symbole de protection (Boucher 2008).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "sacré-endémique.-venin-utilisé-en-médecine-traditionnelle-(douleur).-symbole-de-protection-(boucher-2008)."],
  },
  {
  id: "matoutou-fy-cyr",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Matoutou fèy",
  nomFrancais: "Mygale des Antilles",
  nomScientifique: "Cyrtopholis permata",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Endémique. Toiles associées aux pièges des esprits (*zombi*). Habitat: forêts (MNHN).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Endémique. Toiles associées aux pièges des esprits (*zombi*). Habitat: forêts (MNHN).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "ambivalent-endémique.-toiles-associées-aux-pièges-des-esprits-(*zombi*).-habitat:-forêts-(mnhn)."],
  },
  {
  id: "fwz-ory",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Fwèzè",
  nomFrancais: "Hanneton rhinocéros",
  nomScientifique: "Oryctes nasicornis",
  isResistanceSymbol: true,
  resistanceType: "Culturel Introduit. Larves consommées par les Kalinagos. Symbole de fertilité des sols (Barraud 1994).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Introduit. Larves consommées par les Kalinagos. Symbole de fertilité des sols (Barraud 1994).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-introduit.-larves-consommées-par-les-kalinagos.-symbole-de-fertilité-des-sols-(barraud-1994)."],
  },
  {
  id: "papiyon-nwi-hyl",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Papiyon nwi",
  nomFrancais: "Papillon de nuit géant",
  nomScientifique: "Hyles lineata",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Pollinise les fleurs nocturnes. Associé aux esprits de la nuit (*dlo*).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "klop-por",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Klop",
  nomFrancais: "Cloporte géant",
  nomScientifique: "Porcellio laevis",
  isResistanceSymbol: true,
  resistanceType: "Culturel Introduit. Associé à la décomposition et au cycle de la vie (tradition créole).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Introduit. Associé à la décomposition et au cycle de la vie (tradition créole).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-introduit.-associé-à-la-décomposition-et-au-cycle-de-la-vie-(tradition-créole)."],
  },
  {
  id: "liblul-ort",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Libélul",
  nomFrancais: "Libellule des Antilles",
  nomScientifique: "Orthemis ferruginea",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Symbole de légèreté et de liberté. Présente près des sources sacrées (archives MNHN).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "fmi-kabrit-att",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Fòmi kabrit",
  nomFrancais: "Fourmi coup-feuille",
  nomScientifique: "Atta cephalotes",
  isResistanceSymbol: true,
  resistanceType: "Culturel Introduite. Utilisée dans les rituels de protection des cultures (quimbois).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Introduite. Utilisée dans les rituels de protection des cultures (quimbois).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-introduite.-utilisée-dans-les-rituels-de-protection-des-cultures-(quimbois)."],
  },
  {
  id: "mouch-kochon-xyl",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Mouch kochon",
  nomFrancais: "Abeille charpentière",
  nomScientifique: "Xylocopa mordax",
  isResistanceSymbol: true,
  resistanceType: "Culturel Pollinise les plantes sacrées (*lalo*). Symbole de travail collectif (tradition créole).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Pollinise les plantes sacrées (*lalo*). Symbole de travail collectif (tradition créole).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-pollinise-les-plantes-sacrées-(*lalo*).-symbole-de-travail-collectif-(tradition-créole)."],
  },
  {
  id: "gs-piken-pol",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Gès piken",
  nomFrancais: "Guêpe sociale",
  nomScientifique: "Polistes crinitus",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Nid utilisé dans les remèdes contre les douleurs articulaires (quimbois).",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pwason-priy-sta",
  categorie: "INSECTES SACRÉS",
  sousCategorie: "insecte",
  nomCreole: "Pwason priyè",
  nomFrancais: "Mante religieuse",
  nomScientifique: "Stagmomantis carolina",
  isResistanceSymbol: true,
  resistanceType: "Culturel Symbole de patience et de stratégie (chasse traditionnelle). Habitat: zones buissonneuses.",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Symbole de patience et de stratégie (chasse traditionnelle). Habitat: zones buissonneuses.",
  tags: ["insectes sacrés", "insecte", "resistance", "sacré", "culturel-symbole-de-patience-et-de-stratégie-(chasse-traditionnelle).-habitat:-zones-buissonneuses."],
  },
  {
  id: "poul-nw-gal",
  categorie: "ANIMAUX DU QUIMBOIS",
  sousCategorie: "ritual / quimbois",
  nomCreole: "Poul nwè",
  nomFrancais: "Poule noire",
  nomScientifique: "Gallus gallus domesticus",
  isResistanceSymbol: true,
  resistanceType: "ANIMAL",
  resistanceDescription: undefined,
  sacreSymbolique: "ANIMAL RITUEL",
  dimensionCulturelle: "Dans les cérémonies du quimbois, la poule noire est un animal sacré offert aux esprits des carrefours. Sa présence marque le passage entre le monde des vivants et celui des ancêtres. Animal à la frontière des deux mondes.",
  tags: ["animaux du quimbois", "ritual / quimbois", "resistance", "sacré", "animal"],
  },
  {
  id: "kabrit-nw-cap",
  categorie: "ANIMAUX DU QUIMBOIS",
  sousCategorie: "ritual / quimbois",
  nomCreole: "Kabrit nwè",
  nomFrancais: "Cabri noir",
  nomScientifique: "Capra aegagrus hircus",
  isResistanceSymbol: true,
  resistanceType: "ANIMAL",
  resistanceDescription: undefined,
  sacreSymbolique: "ANIMAL RITUEL",
  dimensionCulturelle: "Dans la tradition vaudou et le quimbois, le cabri noir est un intermédiaire sacré entre les vivants et les lwa. Son offrande est un acte de dévotion — l'équivalent d'une prière incarnée, un don de soi fait à travers l'animal.",
  tags: ["animaux du quimbois", "ritual / quimbois", "resistance", "sacré", "animal"],
  },
  {
  id: "chatou-poulpe-oct",
  categorie: "ANIMAUX DU QUIMBOIS",
  sousCategorie: "ritual / quimbois",
  nomCreole: "Chatou / Poulpe",
  nomFrancais: "Poulpe / Chatrou",
  nomScientifique: "Octopus vulgaris",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Animal de la mer profonde aux huit bras. Dans la tradition créole, le chatrou est associé aux esprits de la mer qui cherchent à saisir les vivants. Les pêcheurs lui vouent un respect mêlé de crainte.",
  tags: ["animaux du quimbois", "ritual / quimbois", "resistance", "sacré", "symbolique"],
  },
  {
  id: "lambi-lob",
  categorie: "MOLLUSQUES",
  sousCategorie: "mollusque",
  nomCreole: "Lambi",
  nomFrancais: "Conque reine",
  nomScientifique: "Lobatus gigas",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ CULTUREL Mollusque marin. Coquille utilisée comme trompe (*konch*) dans les cérémonies kalinagos. Symbole de communication avec la mer. Ramassage réglementé (arrêté 2015).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ CULTUREL",
  dimensionCulturelle: "Mollusque marin. Coquille utilisée comme trompe (*konch*) dans les cérémonies kalinagos. Symbole de communication avec la mer. Ramassage réglementé (arrêté 2015).",
  tags: ["mollusques", "mollusque", "resistance", "sacré", "sacré-culturel-mollusque-marin.-coquille-utilisée-comme-trompe-(*konch*)-dans-les-cérémonies-kalinagos.-symbole-de-communication-avec-la-mer.-ramassage-réglementé-(arrêté-2015)."],
  },
  {
  id: "pwason-konch-pli",
  categorie: "MOLLUSQUES",
  sousCategorie: "mollusque",
  nomCreole: "Pwason konch",
  nomFrancais: "Pourpre des Antilles",
  nomScientifique: "Plicopurpura pansa",
  isResistanceSymbol: true,
  resistanceType: "Culturel Utilisée pour teindre les tissus sacrés (violet). Associée aux rituels de deuil (Boucher 2008).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Utilisée pour teindre les tissus sacrés (violet). Associée aux rituels de deuil (Boucher 2008).",
  tags: ["mollusques", "mollusque", "resistance", "sacré", "culturel-utilisée-pour-teindre-les-tissus-sacrés-(violet).-associée-aux-rituels-de-deuil-(boucher-2008)."],
  },
  {
  id: "koko-dlo-ner",
  categorie: "MOLLUSQUES",
  sousCategorie: "mollusque",
  nomCreole: "Koko dlo",
  nomFrancais: "Nérite des Antilles",
  nomScientifique: "Nerita peloronta",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Présente dans les estuaires. Symbole de pureté dans les rituels de purification (*bain gadèzafé*).",
  tags: ["mollusques", "mollusque", "resistance", "sacré", "symbolique"],
  },
  {
  id: "gwo-kokoy-ach",
  categorie: "MOLLUSQUES",
  sousCategorie: "mollusque",
  nomCreole: "Gwo kokoy",
  nomFrancais: "Achatine géante",
  nomScientifique: "Achatina fulica",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduite. Consommée en période de disette. Associée à la lenteur et à la patience (tradition créole).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduite. Consommée en période de disette. Associée à la lenteur et à la patience (tradition créole).",
  tags: ["mollusques", "mollusque", "resistance", "sacré", "ambivalent-introduite.-consommée-en-période-de-disette.-associée-à-la-lenteur-et-à-la-patience-(tradition-créole)."],
  },
  {
  id: "kokoy-bul",
  categorie: "MOLLUSQUES",
  sousCategorie: "mollusque",
  nomCreole: "Kokoy",
  nomFrancais: "Escargot terrestre",
  nomScientifique: "Bulimulus guadeloupensis",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Endémique. Coquille utilisée comme récipient pour les potions (quimbois). Habitat: zones humides (ONF).",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Endémique. Coquille utilisée comme récipient pour les potions (quimbois). Habitat: zones humides (ONF).",
  tags: ["mollusques", "mollusque", "resistance", "sacré", "emblématique-endémique.-coquille-utilisée-comme-récipient-pour-les-potions-(quimbois).-habitat:-zones-humides-(onf)."],
  },
  {
  id: "gupi-poe",
  categorie: "POISSONS",
  sousCategorie: "poisson",
  nomCreole: "Gupi",
  nomFrancais: "Guppy",
  nomScientifique: "Poecilia reticulata",
  isResistanceSymbol: true,
  resistanceType: "Culturel Introduit. Élevé dans les bassins pour éloigner les moustiques. Symbole de vie (tradition indienne).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Introduit. Élevé dans les bassins pour éloigner les moustiques. Symbole de vie (tradition indienne).",
  tags: ["poissons", "poisson", "resistance", "sacré", "culturel-introduit.-élevé-dans-les-bassins-pour-éloigner-les-moustiques.-symbole-de-vie-(tradition-indienne)."],
  },
  {
  id: "pwason-zorey-nan",
  categorie: "POISSONS",
  sousCategorie: "poisson",
  nomCreole: "Pwason zorey",
  nomFrancais: "Cichlidé des Antilles",
  nomScientifique: "Nandopsis haitiensis",
  isResistanceSymbol: true,
  resistanceType: "Ambivalent Introduit. Associé à la ruse et à la survie dans les étangs (marronnage).",
  resistanceDescription: undefined,
  sacreSymbolique: "Ambivalent",
  dimensionCulturelle: "Introduit. Associé à la ruse et à la survie dans les étangs (marronnage).",
  tags: ["poissons", "poisson", "resistance", "sacré", "ambivalent-introduit.-associé-à-la-ruse-et-à-la-survie-dans-les-étangs-(marronnage)."],
  },
  {
  id: "anguil-ang",
  categorie: "POISSONS",
  sousCategorie: "poisson",
  nomCreole: "Anguil",
  nomFrancais: "Anguille des Antilles",
  nomScientifique: "Anguilla rostrata",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Migratrice. Symbole de voyage entre les mondes (Kalinago). Utilisée dans les rituels de passage (MNHN).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Migratrice. Symbole de voyage entre les mondes (Kalinago). Utilisée dans les rituels de passage (MNHN).",
  tags: ["poissons", "poisson", "resistance", "sacré", "sacré-migratrice.-symbole-de-voyage-entre-les-mondes-(kalinago).-utilisée-dans-les-rituels-de-passage-(mnhn)."],
  },
  {
  id: "vivane-lut",
  categorie: "POISSONS",
  sousCategorie: "poisson",
  nomCreole: "Vivane",
  nomFrancais: "Vivaneau rouge",
  nomScientifique: "Lutjanus synagris",
  isResistanceSymbol: true,
  resistanceType: "Culturel Pêché traditionnellement. Associé aux fêtes communautaires (*koudmen*).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel",
  dimensionCulturelle: "Pêché traditionnellement. Associé aux fêtes communautaires (*koudmen*).",
  tags: ["poissons", "poisson", "resistance", "sacré", "culturel-pêché-traditionnellement.-associé-aux-fêtes-communautaires-(*koudmen*)."],
  },
  {
  id: "fk-lafimi-neo",
  categorie: "ESPÈCES DISPARUES",
  sousCategorie: "mammifère disparu",
  nomCreole: "Fòk lafimi",
  nomFrancais: "Phoque moine des Caraïbes",
  nomScientifique: "Neomonachus tropicalis",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ DISPARU Disparu au XVIIe siècle. Symbole de la connexion entre la terre et la mer (Kalinago). Chassé pour sa graisse (archives MNHN).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ DISPARU",
  dimensionCulturelle: "Disparu au XVIIe siècle. Symbole de la connexion entre la terre et la mer (Kalinago). Chassé pour sa graisse (archives MNHN).",
  tags: ["espèces disparues", "mammifère disparu", "resistance", "sacré", "sacré-disparu-disparu-au-xviie-siècle.-symbole-de-la-connexion-entre-la-terre-et-la-mer-(kalinago).-chassé-pour-sa-graisse-(archives-mnhn)."],
  },
  {
  id: "paresseux-gant-meg",
  categorie: "ESPÈCES DISPARUES",
  sousCategorie: "mammifère disparu",
  nomCreole: "Paresseux géant",
  nomFrancais: "Paresseux de la Guadeloupe",
  nomScientifique: "Megalonyx wheatleyi",
  isResistanceSymbol: true,
  resistanceType: "Emblématique DISPARU Disparu à l'arrivée des Européens. Associé à la lenteur et à la sagesse (mythes amérindiens).",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique DISPARU",
  dimensionCulturelle: "Disparu à l'arrivée des Européens. Associé à la lenteur et à la sagesse (mythes amérindiens).",
  tags: ["espèces disparues", "mammifère disparu", "resistance", "sacré", "emblématique-disparu-disparu-à-l'arrivée-des-européens.-associé-à-la-lenteur-et-à-la-sagesse-(mythes-amérindiens)."],
  },
  {
  id: "tti-bwa-che",
  categorie: "ESPÈCES DISPARUES",
  sousCategorie: "reptile disparu",
  nomCreole: "Tòti bwa",
  nomFrancais: "Tortue terrestre géante",
  nomScientifique: "Chelonoidis carbonarius",
  isResistanceSymbol: true,
  resistanceType: "Culturel DISPARU Disparue au XVIIIe siècle. Symbole de longévité. Carapace utilisée comme récipient (archives coloniales).",
  resistanceDescription: undefined,
  sacreSymbolique: "Culturel DISPARU",
  dimensionCulturelle: "Disparue au XVIIIe siècle. Symbole de longévité. Carapace utilisée comme récipient (archives coloniales).",
  tags: ["espèces disparues", "reptile disparu", "resistance", "sacré", "culturel-disparu-disparue-au-xviiie-siècle.-symbole-de-longévité.-carapace-utilisée-comme-récipient-(archives-coloniales)."],
  }
];

// Index pour recherche rapide
export const fauneIndex: Record<string, FauneEntry> = {
  "fwou-fwou-kolibri-ort": fauneData.find(p => p.id === "fwou-fwou-kolibri-ort")!,
  "kolibri-mad-eul": fauneData.find(p => p.id === "kolibri-mad-eul")!,
  "kolibri-fal-vt-eul": fauneData.find(p => p.id === "kolibri-fal-vt-eul")!,
  "sucrier-coe": fauneData.find(p => p.id === "sucrier-coe")!,
  "soukougnan-myt": fauneData.find(p => p.id === "soukougnan-myt")!,
  "plikan-gran-plikan-pel": fauneData.find(p => p.id === "plikan-gran-plikan-pel")!,
  "urakan-frgate-fre": fauneData.find(p => p.id === "urakan-frgate-fre")!,
  "pic-de-gwadloup-mel": fauneData.find(p => p.id === "pic-de-gwadloup-mel")!,
  "yl-siffleur-montagne-sei": fauneData.find(p => p.id === "yl-siffleur-montagne-sei")!,
  "jakt-ama": fauneData.find(p => p.id === "jakt-ama")!,
  "serpan-sym": fauneData.find(p => p.id === "serpan-sym")!,
  "merl-lafr-tur": fauneData.find(p => p.id === "merl-lafr-tur")!,
  "ti-chant-set": fauneData.find(p => p.id === "ti-chant-set")!,
  "ramy-griv-pat": fauneData.find(p => p.id === "ramy-griv-pat")!,
  "chout-kabrit-tyt": fauneData.find(p => p.id === "chout-kabrit-tyt")!,
  "dab-hibou-tyt": fauneData.find(p => p.id === "dab-hibou-tyt")!,
  "bwa-fouy-buse-but": fauneData.find(p => p.id === "bwa-fouy-buse-but")!,
  "ibis-rouj-eud": fauneData.find(p => p.id === "ibis-rouj-eud")!,
  "igwann-vt-igwann-pyi-igu": fauneData.find(p => p.id === "igwann-vt-igwann-pyi-igu")!,
  "igwann-pyi-igu": fauneData.find(p => p.id === "igwann-pyi-igu")!,
  "zandoli-anoli-ano": fauneData.find(p => p.id === "zandoli-anoli-ano")!,
  "mabouya-the": fauneData.find(p => p.id === "mabouya-the")!,
  "koures-couresse-als": fauneData.find(p => p.id === "koures-couresse-als")!,
  "kwikwi-amp": fauneData.find(p => p.id === "kwikwi-amp")!,
  "lza-moun-gym": fauneData.find(p => p.id === "lza-moun-gym")!,
  "serpan-moun-chi": fauneData.find(p => p.id === "serpan-moun-chi")!,
  "geko-pi-sph": fauneData.find(p => p.id === "geko-pi-sph")!,
  "zandoli-gwo-ame": fauneData.find(p => p.id === "zandoli-gwo-ame")!,
  "tarente-hem": fauneData.find(p => p.id === "tarente-hem")!,
  "krokod-cro": fauneData.find(p => p.id === "krokod-cro")!,
  "gouti-das": fauneData.find(p => p.id === "gouti-das")!,
  "raton-laveur-racoon-pro": fauneData.find(p => p.id === "raton-laveur-racoon-pro")!,
  "guimbo-chauve-souris-13": fauneData.find(p => p.id === "guimbo-chauve-souris-13")!,
  "baln-meg": fauneData.find(p => p.id === "baln-meg")!,
  "manman-dlo-lamantin-tri": fauneData.find(p => p.id === "manman-dlo-lamantin-tri")!,
  "mangouste-mongos-her": fauneData.find(p => p.id === "mangouste-mongos-her")!,
  "rat-nw-rat": fauneData.find(p => p.id === "rat-nw-rat")!,
  "souris-lafimi-mus": fauneData.find(p => p.id === "souris-lafimi-mus")!,
  "chauv-souris-frwi-art": fauneData.find(p => p.id === "chauv-souris-frwi-art")!,
  "tatou-das": fauneData.find(p => p.id === "tatou-das")!,
  "chauv-souris-frwi-bra": fauneData.find(p => p.id === "chauv-souris-frwi-bra")!,
  "chauv-souris-grise-mor": fauneData.find(p => p.id === "chauv-souris-grise-mor")!,
  "chauv-souris-swif-mol": fauneData.find(p => p.id === "chauv-souris-swif-mol")!,
  "chauv-souris-ti-nat": fauneData.find(p => p.id === "chauv-souris-ti-nat")!,
  "chauv-souris-sak-sac": fauneData.find(p => p.id === "chauv-souris-sak-sac")!,
  "tti-vt-tortue-verte-che": fauneData.find(p => p.id === "tti-vt-tortue-verte-che")!,
  "tti-kar-caret-ere": fauneData.find(p => p.id === "tti-kar-caret-ere")!,
  "tti-luth-grandluth-der": fauneData.find(p => p.id === "tti-luth-grandluth-der")!,
  "grenn-bwa-hylode-ele": fauneData.find(p => p.id === "grenn-bwa-hylode-ele")!,
  "krapo-crapaud-buffle-rhi": fauneData.find(p => p.id === "krapo-crapaud-buffle-rhi")!,
  "rainett-ka-boa": fauneData.find(p => p.id === "rainett-ka-boa")!,
  "krap-dlo-lep": fauneData.find(p => p.id === "krap-dlo-lep")!,
  "grenouy-venim-den": fauneData.find(p => p.id === "grenouy-venim-den")!,
  "krab-t-crabe-de-terre-car": fauneData.find(p => p.id === "krab-t-crabe-de-terre-car")!,
  "touloulou-itouloulou-gec": fauneData.find(p => p.id === "touloulou-itouloulou-gec")!,
  "sirik-cirique-gra": fauneData.find(p => p.id === "sirik-cirique-gra")!,
  "zachari-zagalliac-esp": fauneData.find(p => p.id === "zachari-zagalliac-esp")!,
  "wasou-ouassou-mac": fauneData.find(p => p.id === "wasou-ouassou-mac")!,
  "langous-pan": fauneData.find(p => p.id === "langous-pan")!,
  "krab-rivy-pot": fauneData.find(p => p.id === "krab-rivy-pot")!,
  "krab-moun-gec": fauneData.find(p => p.id === "krab-moun-gec")!,
  "krab-bdlanm-uci": fauneData.find(p => p.id === "krab-bdlanm-uci")!,
  "myl-abeille-pyi-api": fauneData.find(p => p.id === "myl-abeille-pyi-api")!,
  "foumi-manyok-acr": fauneData.find(p => p.id === "foumi-manyok-acr")!,
  "kabribo-cabrit-bois-esp": fauneData.find(p => p.id === "kabribo-cabrit-bois-esp")!,
  "luciole-ti-flambeau-lam": fauneData.find(p => p.id === "luciole-ti-flambeau-lam")!,
  "mouche-miel-gupe-pyi-pol": fauneData.find(p => p.id === "mouche-miel-gupe-pyi-pol")!,
  "papillon-nw-mariposa-her": fauneData.find(p => p.id === "papillon-nw-mariposa-her")!,
  "papillon-transparent-gre": fauneData.find(p => p.id === "papillon-transparent-gre")!,
  "ravt-per": fauneData.find(p => p.id === "ravt-per")!,
  "myg-mygale-de-la-soufrire-cyr": fauneData.find(p => p.id === "myg-mygale-de-la-soufrire-cyr")!,
  "bef-scarabe-sacr-can": fauneData.find(p => p.id === "bef-scarabe-sacr-can")!,
  "milpat-rha": fauneData.find(p => p.id === "milpat-rha")!,
  "zandoli-piq-cen": fauneData.find(p => p.id === "zandoli-piq-cen")!,
  "matoutou-fy-cyr": fauneData.find(p => p.id === "matoutou-fy-cyr")!,
  "fwz-ory": fauneData.find(p => p.id === "fwz-ory")!,
  "papiyon-nwi-hyl": fauneData.find(p => p.id === "papiyon-nwi-hyl")!,
  "klop-por": fauneData.find(p => p.id === "klop-por")!,
  "liblul-ort": fauneData.find(p => p.id === "liblul-ort")!,
  "fmi-kabrit-att": fauneData.find(p => p.id === "fmi-kabrit-att")!,
  "mouch-kochon-xyl": fauneData.find(p => p.id === "mouch-kochon-xyl")!,
  "gs-piken-pol": fauneData.find(p => p.id === "gs-piken-pol")!,
  "pwason-priy-sta": fauneData.find(p => p.id === "pwason-priy-sta")!,
  "poul-nw-gal": fauneData.find(p => p.id === "poul-nw-gal")!,
  "kabrit-nw-cap": fauneData.find(p => p.id === "kabrit-nw-cap")!,
  "chatou-poulpe-oct": fauneData.find(p => p.id === "chatou-poulpe-oct")!,
  "lambi-lob": fauneData.find(p => p.id === "lambi-lob")!,
  "pwason-konch-pli": fauneData.find(p => p.id === "pwason-konch-pli")!,
  "koko-dlo-ner": fauneData.find(p => p.id === "koko-dlo-ner")!,
  "gwo-kokoy-ach": fauneData.find(p => p.id === "gwo-kokoy-ach")!,
  "kokoy-bul": fauneData.find(p => p.id === "kokoy-bul")!,
  "gupi-poe": fauneData.find(p => p.id === "gupi-poe")!,
  "pwason-zorey-nan": fauneData.find(p => p.id === "pwason-zorey-nan")!,
  "anguil-ang": fauneData.find(p => p.id === "anguil-ang")!,
  "vivane-lut": fauneData.find(p => p.id === "vivane-lut")!,
  "fk-lafimi-neo": fauneData.find(p => p.id === "fk-lafimi-neo")!,
  "paresseux-gant-meg": fauneData.find(p => p.id === "paresseux-gant-meg")!,
  "tti-bwa-che": fauneData.find(p => p.id === "tti-bwa-che")!
};

// Fonction utilitaire
export function getFauneByNomCreole(nom: string): FauneEntry | undefined {
  return fauneData.find(p => 
    p.nomCreole.toLowerCase() === nom.toLowerCase() ||
    p.nomCreole.toLowerCase().includes(nom.toLowerCase()) ||
    p.nomFrancais.toLowerCase() === nom.toLowerCase() ||
    p.nomFrancais.toLowerCase().includes(nom.toLowerCase())
  );
}
