export interface FloreEntry {
  id: string;
  categorie: string;
  sousCategorie: string;
  nomCreole: string;
  nomFrancais: string;
  nomScientifique: string;
  usage: string;
  isResistanceSymbol: boolean;
  resistanceType?: string;
  resistanceDescription?: string;
  sacreSymbolique?: string;
  dimensionCulturelle: string;
  tags: string[];
}


// Données générées automatiquement depuis flore_guadeloupe_ref.md
// NE PAS MODIFIER MANUELLEMENT - Exécuter 'npm run flore:parse' pour mettre à jour
export const floreData: FloreEntry[] = [
  {
  id: "mangui",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Manguié",
  nomFrancais: "Manguier",
  nomScientifique: "Mangifera indica",
  usage: "Arbre tuteur du jardin. Ombrage pour les autres plants. 20+ variétés locales.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre tuteur du jardin. Ombrage pour les autres plants. 20+ variétés locales.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "korossoli",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Korossolié",
  nomFrancais: "Corossolier",
  nomScientifique: "Annona muricata",
  usage: "Ombre et fruit. Feuilles récoltées pour tisane sédative.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Ombre et fruit. Feuilles récoltées pour tisane sédative.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "marakoudja",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Marakoudja",
  nomFrancais: "Fruit de la passion / Maracuja",
  nomScientifique: "Passiflora edulis",
  usage: "Acide et sucré. Fruit identitaire de la Guadeloupe. Très présent en jus et sorbets.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Acide et sucré. Fruit identitaire de la Guadeloupe. Très présent en jus et sorbets.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "gwayavi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Gwayavié",
  nomFrancais: "Goyavier",
  nomScientifique: "Psidium guajava",
  usage: "Arbre semi-sauvage très présent dans les mornes. Fruits, gelée, bois de chauffe.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre semi-sauvage très présent dans les mornes. Fruits, gelée, bois de chauffe.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "papayi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Papayié",
  nomFrancais: "Papayer",
  nomScientifique: "Carica papaya",
  usage: "Croissance rapide. Fruit toute l'année. Feuilles et latex aux vertus médicinales.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Croissance rapide. Fruit toute l'année. Feuilles et latex aux vertus médicinales.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "ananas-pyi",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Ananas péyi",
  nomFrancais: "Ananas",
  nomScientifique: "Ananas comosus",
  usage: "Ananas local plus petit et plus sucré que les variétés industrielles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Ananas local plus petit et plus sucré que les variétés industrielles.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "sitwl-prune-sitwl",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Sitwèl / Prune sitwèl",
  nomFrancais: "Prune de Cythère / Pomme cythère",
  nomScientifique: "Spondias dulcis",
  usage: "Fruit vert à chair crème. Consommé en jus, sorbet, confiture.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fruit vert à chair crème. Consommé en jus, sorbet, confiture.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "sapotiyi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Sapotiyié",
  nomFrancais: "Sapotillier",
  nomScientifique: "Manilkara zapota",
  usage: "Grand arbre lent à croître. Fruit très sucré. Latex utilisé comme gomme naturelle.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grand arbre lent à croître. Fruit très sucré. Latex utilisé comme gomme naturelle.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "karanboli",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Karanbolié",
  nomFrancais: "Carambolier",
  nomScientifique: "Averrhoa carambola",
  usage: "Arbre de taille moyenne. Fruit étoilé désaltérant. Ombre légère.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre de taille moyenne. Fruit étoilé désaltérant. Ombre légère.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "pomme-kannl",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Pomme-kannèl",
  nomFrancais: "Pomme cannelle / Cachiman",
  nomScientifique: "Annona squamosa",
  usage: "Fruit vert bosselé, chair blanche sucrée autour de pépins noirs.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fruit vert bosselé, chair blanche sucrée autour de pépins noirs.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "kent",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Kenèt",
  nomFrancais: "Quenette / Chenette",
  nomScientifique: "Melicoccus bijugatus",
  usage: "Grappes de petites coques vertes, chair jaune tirant sur le litchi. Fruit de saison populaire.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grappes de petites coques vertes, chair jaune tirant sur le litchi. Fruit de saison populaire.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "abwiko-pyi",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Abwiko péyi",
  nomFrancais: "Abricot pays",
  nomScientifique: "Mammea americana",
  usage: "Fine écorce brune, noyau unique. Confondu parfois avec l'abricot tropical.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fine écorce brune, noyau unique. Confondu parfois avec l'abricot tropical.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "sriz-pyi",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Sèriz péyi",
  nomFrancais: "Cerise pays / Acérola",
  nomScientifique: "Malpighia emarginata",
  usage: "Très riche en vitamine C. Consommée en jus. Petit fruit rouge acidulé.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Très riche en vitamine C. Consommée en jus. Petit fruit rouge acidulé.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "kokoti",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Kokotié",
  nomFrancais: "Cocotier",
  nomScientifique: "Cocos nucifera",
  usage: "Arbre de protection et de subsistance. Eau, chair, huile, feuilles tressées.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre de protection et de subsistance. Eau, chair, huile, feuilles tressées.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "pomd-pomme-liane",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Pomdó / Pomme-liane",
  nomFrancais: "Pomme d'or / Grenadille",
  nomScientifique: "Passiflora laurifolia",
  usage: "Ressemble au maracuja, peau jaune lisse. Saveur douce différente.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Ressemble au maracuja, peau jaune lisse. Saveur douce différente.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "figye-figue-banane",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Figye / Figue banane",
  nomFrancais: "Banane dessert",
  nomScientifique: "Musa acuminata",
  usage: "Banane classique. Transformée en flambée, confitures, chips.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Banane classique. Transformée en flambée, confitures, chips.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "banann-pm",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Banann pòm",
  nomFrancais: "Banane pomme",
  nomScientifique: "Musa (var. pomme)",
  usage: "Plus petite, plus sucrée. Très appréciée des locaux.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plus petite, plus sucrée. Très appréciée des locaux.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "pwayo-poyo",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Pwayo / Poyo",
  nomFrancais: "Banane plantain",
  nomScientifique: "Musa paradisiaca",
  usage: "Banane verte cuisinée en légume : frite, bouillie, en gratin. Base de la cuisine créole.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Banane verte cuisinée en légume : frite, bouillie, en gratin. Base de la cuisine créole.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "kalbasi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Kalbasi",
  nomFrancais: "Calebassier",
  nomScientifique: "Crescentia cujete",
  usage: "Fruit non comestible. Calebasses utilisées comme récipients, instruments, objets rituels.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fruit non comestible. Calebasses utilisées comme récipients, instruments, objets rituels.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "friyapen",
  categorie: "FRUITS",
  sousCategorie: "fruit",
  nomCreole: "Friyapen",
  nomFrancais: "Fruit à pain",
  nomScientifique: "Artocarpus altilis",
  usage: "Gros fruit vert cuisiné comme une fécule. Frites, baguette, gratin. Héritage amérindien.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Gros fruit vert cuisiné comme une fécule. Frites, baguette, gratin. Héritage amérindien.",
  tags: ["fruits", "fruit"],
  },
  {
  id: "grennadi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Grennadié",
  nomFrancais: "Grenadier",
  nomScientifique: "Punica granatum",
  usage: "Arbre ornemental et fruitier. Jus de grenade et sirop.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre ornemental et fruitier. Jus de grenade et sirop.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "tamarin",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Tamariné",
  nomFrancais: "Tamarinier",
  nomScientifique: "Tamarindus indica",
  usage: "Grand arbre de case. Gousses acidulées. Sirop rafraîchissant. Médecine créole.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grand arbre de case. Gousses acidulées. Sirop rafraîchissant. Médecine créole.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "awokasi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Awokasié",
  nomFrancais: "Avocatier",
  nomScientifique: "Persea americana",
  usage: "Arbre semi-sauvage dans les jardins. Fruit gras consommé cru avec citron et sel.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre semi-sauvage dans les jardins. Fruit gras consommé cru avec citron et sel.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "malaki-pm-malaka",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Malakié / Pòm malaka",
  nomFrancais: "Pommier malacca",
  nomScientifique: "Syzygium malaccense",
  usage: "Arbre ornemental et fruitier à fleurs fuchsia spectaculaires. Ombrage.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre ornemental et fruitier à fleurs fuchsia spectaculaires. Ombrage.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "pm-sirt-girembl",
  categorie: "FRUITS (suite)",
  sousCategorie: "fruit",
  nomCreole: "Pòm sirèt / Girembèl",
  nomFrancais: "Pomme surette / Groseille pays",
  nomScientifique: "Phyllanthus acidus",
  usage: "Petit fruit jaune citron très acidulé, chair croquante autour d'un noyau. Consommé en confiture, punch ou nature. Se ramasse en grappes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Petit fruit jaune citron très acidulé, chair croquante autour d'un noyau. Consommé en confiture, punch ou nature. Se ramasse en grappes.",
  tags: ["fruits (suite)", "fruit"],
  },
  {
  id: "prn-mombin-mombin-jaune",
  categorie: "FRUITS (suite)",
  sousCategorie: "fruit",
  nomCreole: "Pròn mombin / Mombin jaune",
  nomFrancais: "Prune mombin",
  nomScientifique: "Spondias mombin",
  usage: "Fruit oblong à chair jaune et sucrée autour d'un noyau fibreux. Jus, sorbet, liqueur. Arbre sauvage des mornes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fruit oblong à chair jaune et sucrée autour d'un noyau fibreux. Jus, sorbet, liqueur. Arbre sauvage des mornes.",
  tags: ["fruits (suite)", "fruit"],
  },
  {
  id: "piman-vgtarien",
  categorie: "PIMENTS (famille complète)",
  sousCategorie: "piment",
  nomCreole: "Piman végétarien",
  nomFrancais: "Piment végétarien",
  nomScientifique: "Capsicum frutescens",
  usage: "Petit piment très doux à la saveur légèrement sucrée à maturité. Constitue, avec l'ail, l'oignon, l'oignon-pays et le persil, la base des assaisonnements antillais. Force : 0. Croqué cru dans les salades. Variété endémique du jardin créole antillais.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Petit piment très doux à la saveur légèrement sucrée à maturité. Constitue, avec l'ail, l'oignon, l'oignon-pays et le persil, la base des assaisonnements antillais. Force : 0. Croqué cru dans les salades. Variété endémique du jardin créole antillais.",
  tags: ["piments (famille complète)", "piment"],
  },
  {
  id: "piman-bouk",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Piman bouk",
  nomFrancais: "Piment bonda man Jacques",
  nomScientifique: "Capsicum chinense",
  usage: "Piment local très fort à la forme de bonnet. Symbole de la cuisine créole épicée.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Piment local très fort à la forme de bonnet. Symbole de la cuisine créole épicée.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "dachine",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "plante racine",
  nomCreole: "Dachine",
  nomFrancais: "Dachine / Taro",
  nomScientifique: "Colocasia esculenta",
  usage: "Tubercule fondant. Feuilles (brede chouk) cuisinées en court-bouillon de poisson.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Tubercule fondant. Feuilles (brede chouk) cuisinées en court-bouillon de poisson.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "plante racine"],
  },
  {
  id: "iyam",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Iyam",
  nomFrancais: "Igname",
  nomScientifique: "Dioscorea alata",
  usage: "Tubercule africain apporté dans les cales des bateaux négriers — volontairement ou non. Sa culture dans les jardins de case représentait un lien direct avec l'Afrique et une autonomie nutritive essentielle. L'igname est un acte de mémoire autant que de nourriture. RÉSISTANCE ALIMENTAIRE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE ALIMENTAIRE",
  resistanceDescription: "Tubercule africain apporté dans les cales des bateaux négriers — volontairement ou non. Sa culture dans les jardins de case représentait un lien direct avec l'Afrique et une autonomie nutritive essentielle. L'igname est un acte de mémoire autant que de nourriture.",
  sacreSymbolique: "RÉSISTANCE ALIMENTAIRE",
  dimensionCulturelle: "Tubercule africain apporté dans les cales des bateaux négriers — volontairement ou non. Sa culture dans les jardins de case représentait un lien direct avec l'Afrique et une autonomie nutritive essentielle. L'igname est un acte de mémoire autant que de nourriture. RÉSISTANCE ALIMENTAIRE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-alimentaire"],
  },
  {
  id: "manyk",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Manyòk",
  nomFrancais: "Manioc",
  nomScientifique: "Manihot esculenta",
  usage: "Racine sacrée des Arawaks devenue arme de survie des esclaves. Cultivée en secret dans les jardins de case, elle permettait une autonomie alimentaire totale hors du contrôle des maîtres. Transformée en cassave, elle nourrissait les marrons en fuite dans les mornes. RÉSISTANCE ALIMENTAIRE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE ALIMENTAIRE",
  resistanceDescription: "Racine sacrée des Arawaks devenue arme de survie des esclaves. Cultivée en secret dans les jardins de case, elle permettait une autonomie alimentaire totale hors du contrôle des maîtres. Transformée en cassave, elle nourrissait les marrons en fuite dans les mornes.",
  sacreSymbolique: "RÉSISTANCE ALIMENTAIRE",
  dimensionCulturelle: "Racine sacrée des Arawaks devenue arme de survie des esclaves. Cultivée en secret dans les jardins de case, elle permettait une autonomie alimentaire totale hors du contrôle des maîtres. Transformée en cassave, elle nourrissait les marrons en fuite dans les mornes. RÉSISTANCE ALIMENTAIRE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-alimentaire"],
  },
  {
  id: "mad",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "plante racine",
  nomCreole: "Madè",
  nomFrancais: "Madère",
  nomScientifique: "Xanthosoma sagittifolium",
  usage: "Tubercule ferme absorbant les sauces créoles. Souvent mélangé à l'igname.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Tubercule ferme absorbant les sauces créoles. Souvent mélangé à l'igname.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "plante racine"],
  },
  {
  id: "jiramn-giraumon",
  categorie: "LÉGUMES / RACINES",
  sousCategorie: "légume / racine",
  nomCreole: "Jiramòn / Giraumon",
  nomFrancais: "Giraumon",
  nomScientifique: "Cucurbita moschata",
  usage: "Courge locale. Soupe, purée, gratin. Proche de la citrouille.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Courge locale. Soupe, purée, gratin. Proche de la citrouille.",
  tags: ["légumes / racines", "légume / racine"],
  },
  {
  id: "kowosol-christofen",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Kowosol / Christofen",
  nomFrancais: "Christophine",
  nomScientifique: "Sechium edule",
  usage: "Liane grimpante sur les haies. Fruit léger en gratin ou sauté.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Liane grimpante sur les haies. Fruit léger en gratin ou sauté.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "pwa-dangow",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "légumineuse",
  nomCreole: "Pwa dangow",
  nomFrancais: "Pois d'Angole",
  nomScientifique: "Cajanus cajan",
  usage: "Arbuste à graines. Plat de Noël incontournable. Fixe l'azote dans le sol.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbuste à graines. Plat de Noël incontournable. Fixe l'azote dans le sol.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "légumineuse"],
  },
  {
  id: "gombo",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Gombo",
  nomFrancais: "Gombo / Okra",
  nomScientifique: "Abelmoschus esculentus",
  usage: "Légume africain. Épaissit les soupes et ragoûts. Floraison ornementale.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Légume africain. Épaissit les soupes et ragoûts. Floraison ornementale.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "bred-chouk-chou-carabe",
  categorie: "LÉGUMES / RACINES",
  sousCategorie: "légume / racine",
  nomCreole: "Bred chouk / Chou caraïbe",
  nomFrancais: "Chou caraïbe",
  nomScientifique: "Colocasia esculenta (feuilles)",
  usage: "Feuilles du dachine. Utilisées en court-bouillon de poisson.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Feuilles du dachine. Utilisées en court-bouillon de poisson.",
  tags: ["légumes / racines", "légume / racine"],
  },
  {
  id: "bwa-dind-feuilles",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Bwa d'Ind (feuilles)",
  nomFrancais: "Feuilles de bois d'inde",
  nomScientifique: "Pimenta racemosa",
  usage: "Feuilles aromatiques des haies. Bouillons, bains rituels du quimbois.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Feuilles aromatiques des haies. Bouillons, bains rituels du quimbois.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "kannel",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Kannel",
  nomFrancais: "Cannelle",
  nomScientifique: "Cinnamomum zeylanicum",
  usage: "Écorce parfumée. Tisanes, punchs, gâteaux créoles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Écorce parfumée. Tisanes, punchs, gâteaux créoles.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "klou-jiwofl",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Klou jiwofl",
  nomFrancais: "Girofle / Clou de girofle",
  nomScientifique: "Syzygium aromaticum",
  usage: "Bouton floral séché. Épice du colombo, des bouillons, des punchs arrangés.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Bouton floral séché. Épice du colombo, des bouillons, des punchs arrangés.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "noumiskat",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Noumiskat",
  nomFrancais: "Noix de muscade",
  nomScientifique: "Myristica fragrans",
  usage: "Râpée dans le punch coco, les desserts créoles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Râpée dans le punch coco, les desserts créoles.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "koubari-curcuma",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Koubari / Curcuma",
  nomFrancais: "Curcuma",
  nomScientifique: "Curcuma longa",
  usage: "Épice apportée par les travailleurs indiens engagés après l'abolition (1848). Sa culture et son usage dans le colombo représentent la résistance culturelle des communautés indiennes à l'assimilation forcée. RÉSISTANCE CULTURELLE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE CULTURELLE",
  resistanceDescription: "Épice apportée par les travailleurs indiens engagés après l'abolition (1848). Sa culture et son usage dans le colombo représentent la résistance culturelle des communautés indiennes à l'assimilation forcée.",
  sacreSymbolique: "RÉSISTANCE CULTURELLE",
  dimensionCulturelle: "Épice apportée par les travailleurs indiens engagés après l'abolition (1848). Sa culture et son usage dans le colombo représentent la résistance culturelle des communautés indiennes à l'assimilation forcée. RÉSISTANCE CULTURELLE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-culturelle"],
  },
  {
  id: "vaniy",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Vaniy",
  nomFrancais: "Vanilier",
  nomScientifique: "Vanilla planifolia",
  usage: "Cultivé par les esclaves et affranchis à Pointe-Noire. La maîtrise de la pollinisation manuelle — technique développée en 1841 par Edmond Albius, esclave réunionnais — est un acte de résistance intellectuelle et économique majeur. Une source de revenus autonomes hors de la plantation. RÉSISTANCE ÉCONOMIQUE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE ÉCONOMIQUE",
  resistanceDescription: "Cultivé par les esclaves et affranchis à Pointe-Noire. La maîtrise de la pollinisation manuelle — technique développée en 1841 par Edmond Albius, esclave réunionnais — est un acte de résistance intellectuelle et économique majeur. Une source de revenus autonomes hors de la plantation.",
  sacreSymbolique: "RÉSISTANCE ÉCONOMIQUE",
  dimensionCulturelle: "Cultivé par les esclaves et affranchis à Pointe-Noire. La maîtrise de la pollinisation manuelle — technique développée en 1841 par Edmond Albius, esclave réunionnais — est un acte de résistance intellectuelle et économique majeur. Une source de revenus autonomes hors de la plantation. RÉSISTANCE ÉCONOMIQUE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-économique"],
  },
  {
  id: "chadki",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Chadékié",
  nomFrancais: "Chadéquier / Pomélo",
  nomScientifique: "Citrus maxima",
  usage: "Grand agrume. Zeste utilisé en cuisine et en médecine créole.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grand agrume. Zeste utilisé en cuisine et en médecine créole.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "citwonn-citron-pyi",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Citwonn / Citron péyi",
  nomFrancais: "Citron vert / Lime",
  nomScientifique: "Citrus aurantiifolia",
  usage: "Incontournable de la cuisine créole. Marinade, acras, punch, vinaigrette créole.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Incontournable de la cuisine créole. Marinade, acras, punch, vinaigrette créole.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "klmb",
  categorie: "ÉPICES / AROMATES",
  sousCategorie: "épice / aromate",
  nomCreole: "Kòlòmbò",
  nomFrancais: "Colombo (épice)",
  nomScientifique: "Mélange de curcuma, coriandre, cumin, etc.",
  usage: "Mélange d'épices d'origine tamoule. Plat national de Guadeloupe. Héritage indien.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Mélange d'épices d'origine tamoule. Plat national de Guadeloupe. Héritage indien.",
  tags: ["épices / aromates", "épice / aromate"],
  },
  {
  id: "kakaoye",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Kakaoye",
  nomFrancais: "Cacaoyer",
  nomScientifique: "Theobroma cacao",
  usage: "Arbre mi-ombre des sous-bois du jardin. Cabosse transformée en chocolat artisanal.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre mi-ombre des sous-bois du jardin. Cabosse transformée en chocolat artisanal.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "chadon-bni",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Chadon béni",
  nomFrancais: "Chardon béni",
  nomScientifique: "Eryngium foetidum",
  usage: "Plante de sol omniprésente. Anti-fièvre, digestive. Aussi utilisée en cuisine (acras).",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plante de sol omniprésente. Anti-fièvre, digestive. Aussi utilisée en cuisine (acras).",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "brize",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Brizée",
  nomFrancais: "Brizée / Plante 3 tasses",
  nomScientifique: "Lippia alba",
  usage: "Tisane anti-stress et sédative. Feuilles citronnées. Très répandue.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Tisane anti-stress et sédative. Feuilles citronnées. Très répandue.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "sitwonl",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Sitwonèl",
  nomFrancais: "Citronnelle",
  nomScientifique: "Cymbopogon citratus",
  usage: "Plante en touffes. Tisane calmante, répulsive anti-moustiques. Incontournable.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plante en touffes. Tisane calmante, répulsive anti-moustiques. Incontournable.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "gwo-tim",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Gwo tim",
  nomFrancais: "Gros thym créole",
  nomScientifique: "Plectranthus amboinicus",
  usage: "Grandes feuilles charnues. Contre toux, rhume, grippe. Cuisine et médecine.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grandes feuilles charnues. Contre toux, rhume, grippe. Cuisine et médecine.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "alowes",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Alowes",
  nomFrancais: "Aloès vera",
  nomScientifique: "Aloe vera",
  usage: "Arbuste succulent en bordure. Gel cicatrisant. Plante médecine de premier secours.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbuste succulent en bordure. Gel cicatrisant. Plante médecine de premier secours.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "dartrier",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Dartrier",
  nomFrancais: "Dartrier / Sene",
  nomScientifique: "Senna alata",
  usage: "Feuilles anti-dermatoses. Traite dartres, teigne et infections cutanées.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Feuilles anti-dermatoses. Traite dartres, teigne et infections cutanées.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "verven",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Verven",
  nomFrancais: "Verveine des Antilles",
  nomScientifique: "Verbena officinalis",
  usage: "Tisane digestive et calmante. Très commune dans les jardins créoles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Tisane digestive et calmante. Très commune dans les jardins créoles.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "zeb-a-femme",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Zeb a femme",
  nomFrancais: "Herbe à femme / Armoise",
  nomScientifique: "Artemisia absinthium",
  usage: "Plante gynécologique créole. Régularise le cycle. Réservée aux femmes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plante gynécologique créole. Régularise le cycle. Réservée aux femmes.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "zeb-kabrit",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Zeb kabrit",
  nomFrancais: "Herbe à cabri",
  nomScientifique: "Capraria biflora",
  usage: "Plante sauvage des bords du jardin. Tisane contre douleurs et fièvre.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plante sauvage des bords du jardin. Tisane contre douleurs et fièvre.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "malom-malnomme",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Malomé / Malnommée",
  nomFrancais: "Malnommée",
  nomScientifique: "Petiveria alliacea",
  usage: "Plantée aux angles de la case par les esclaves pour se protéger de l'emprise des maîtres. Son odeur forte d'ail était un bouclier invisible. Garder cette plante était un acte de résistance culturelle à la christianisation forcée. RÉSISTANCE SPIRITUELLE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE SPIRITUELLE",
  resistanceDescription: "Plantée aux angles de la case par les esclaves pour se protéger de l'emprise des maîtres. Son odeur forte d'ail était un bouclier invisible. Garder cette plante était un acte de résistance culturelle à la christianisation forcée.",
  sacreSymbolique: "RÉSISTANCE SPIRITUELLE",
  dimensionCulturelle: "Plantée aux angles de la case par les esclaves pour se protéger de l'emprise des maîtres. Son odeur forte d'ail était un bouclier invisible. Garder cette plante était un acte de résistance culturelle à la christianisation forcée. RÉSISTANCE SPIRITUELLE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-spirituelle"],
  },
  {
  id: "woucou-roucou",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Woucou / Roucou",
  nomFrancais: "Roucou / Annatto",
  nomScientifique: "Bixa orellana",
  usage: "Plante des Arawaks utilisée pour se peindre le corps lors des cérémonies et des combats. Les esclaves l'ont réappropriée comme colorant alimentaire et comme marqueur identitaire discret, invisible aux yeux des maîtres. RÉSISTANCE IDENTITAIRE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE IDENTITAIRE",
  resistanceDescription: "Plante des Arawaks utilisée pour se peindre le corps lors des cérémonies et des combats. Les esclaves l'ont réappropriée comme colorant alimentaire et comme marqueur identitaire discret, invisible aux yeux des maîtres.",
  sacreSymbolique: "RÉSISTANCE IDENTITAIRE",
  dimensionCulturelle: "Plante des Arawaks utilisée pour se peindre le corps lors des cérémonies et des combats. Les esclaves l'ont réappropriée comme colorant alimentaire et comme marqueur identitaire discret, invisible aux yeux des maîtres. RÉSISTANCE IDENTITAIRE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-identitaire"],
  },
  {
  id: "zeb-a-pik-sensitive",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Zeb a pik / Sensitive",
  nomFrancais: "Sensitive / Herbe à pique",
  nomScientifique: "Mimosa pudica",
  usage: "Plante sensitive (se referme au toucher). Tisane calmante. Plante des enfants.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Plante sensitive (se referme au toucher). Tisane calmante. Plante des enfants.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "patchouli-pyi",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Patchouli péyi",
  nomFrancais: "Patchouli antillais",
  nomScientifique: "Pogostemon cablin",
  usage: "Parfum intense. Bains rituels et protection spirituelle du quimbois.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Parfum intense. Bains rituels et protection spirituelle du quimbois.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "zeb-a-vers",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Zeb a vers",
  nomFrancais: "Herbe à vers",
  nomScientifique: "Chenopodium ambrosioides",
  usage: "Anti-parasitaire intestinal. Plante de purification interne.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Anti-parasitaire intestinal. Plante de purification interne.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "gommi-blan",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Gommié blan",
  nomFrancais: "Gommier blanc",
  nomScientifique: "Bursera simaruba",
  usage: "Arbre des Kalinagos utilisé pour creuser les pirogues de guerre et de fuite. Sa résine-encens servait aux rituels de préparation au combat. Arbre de la mobilité, de l'insoumission et du refus de l'enfermement. RÉSISTANCE AMÉRINDIENNE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE AMÉRINDIENNE",
  resistanceDescription: "Arbre des Kalinagos utilisé pour creuser les pirogues de guerre et de fuite. Sa résine-encens servait aux rituels de préparation au combat. Arbre de la mobilité, de l'insoumission et du refus de l'enfermement.",
  sacreSymbolique: "RÉSISTANCE AMÉRINDIENNE",
  dimensionCulturelle: "Arbre des Kalinagos utilisé pour creuser les pirogues de guerre et de fuite. Sa résine-encens servait aux rituels de préparation au combat. Arbre de la mobilité, de l'insoumission et du refus de l'enfermement. RÉSISTANCE AMÉRINDIENNE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-amérindienne"],
  },
  {
  id: "flanbwayan",
  categorie: "JARDIN CRÉOLE — HAIES ET BORDURES (plantes protectrices)",
  sousCategorie: "haie / bordure",
  nomCreole: "Flanbwayan",
  nomFrancais: "Flamboyant",
  nomScientifique: "Delonix regia",
  usage: "Arbre de haie et de mémoire. Fleurs rouge-orangé de mai à juillet. Annonce la saison des pluies.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre de haie et de mémoire. Fleurs rouge-orangé de mai à juillet. Annonce la saison des pluies.",
  tags: ["jardin créole — haies et bordures (plantes protectrices)", "haie / bordure"],
  },
  {
  id: "figuiye-modi-figuier-maudit",
  categorie: "ARBRES EMBLÉMATIQUES",
  sousCategorie: "arbre",
  nomCreole: "Figuiye modi / Figuier maudit",
  nomFrancais: "Figuier maudit",
  nomScientifique: "Clusia rosea",
  usage: "Présent dans le Parc des Roches Gravées. Nom créole chargé de mystère et de superstition.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Présent dans le Parc des Roches Gravées. Nom créole chargé de mystère et de superstition.",
  tags: ["arbres emblématiques", "arbre"],
  },
  {
  id: "palmis-montagn",
  categorie: "ARBRES EMBLÉMATIQUES",
  sousCategorie: "arbre",
  nomCreole: "Palmis montagn",
  nomFrancais: "Palmiste montagne",
  nomScientifique: "Prestoea montana",
  usage: "Palmier endémique de la forêt tropicale. Cœur du palmier consommé (chou palmiste).",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Palmier endémique de la forêt tropicale. Cœur du palmier consommé (chou palmiste).",
  tags: ["arbres emblématiques", "arbre"],
  },
  {
  id: "acoma-boukan-acajou",
  categorie: "ARBRES EMBLÉMATIQUES",
  sousCategorie: "arbre",
  nomCreole: "Acoma-boukan / Acajou",
  nomFrancais: "Acomat-boucan",
  nomScientifique: "Sideroxylon obtusifolium",
  usage: "Bois dur endémique de la forêt tropicale guadeloupéenne. Très résistant.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Bois dur endémique de la forêt tropicale guadeloupéenne. Très résistant.",
  tags: ["arbres emblématiques", "arbre"],
  },
  {
  id: "woz-laps",
  categorie: "JARDIN CRÉOLE — HAIES ET BORDURES (plantes protectrices)",
  sousCategorie: "haie / bordure",
  nomCreole: "Woz lapòs",
  nomFrancais: "Raisinier bord de mer",
  nomScientifique: "Coccoloba uvifera",
  usage: "Haie littorale aux grandes feuilles rondes. Petits fruits en grappes violettes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Haie littorale aux grandes feuilles rondes. Petits fruits en grappes violettes.",
  tags: ["jardin créole — haies et bordures (plantes protectrices)", "haie / bordure"],
  },
  {
  id: "paltuwy",
  categorie: "ARBRES EMBLÉMATIQUES",
  sousCategorie: "arbre",
  nomCreole: "Palétuwyé",
  nomFrancais: "Palétuvier / Manglier",
  nomScientifique: "Rhizophora mangle",
  usage: "Arbre de la mangrove. Ses racines-échasses forment un monde frontière entre terre et mer.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre de la mangrove. Ses racines-échasses forment un monde frontière entre terre et mer.",
  tags: ["arbres emblématiques", "arbre"],
  },
  {
  id: "fromaj",
  categorie: "ARBRES EMBLÉMATIQUES",
  sousCategorie: "arbre",
  nomCreole: "Fromajé",
  nomFrancais: "Fromager / Kapokier",
  nomScientifique: "Ceiba pentandra",
  usage: "Arbre géant aux contreforts imposants. Surnommé « arbre aux esclaves » et « arbre aux soukounyan ». Les esclaves récalcitrants y étaient suppliciés : attachés par des liens de cuir mouillés que le soleil rétrécissait, les épines du tronc s'enfonçant dans leur chair. Selon le folklore créole, le soukouyan (vampire antillais) vient y accrocher sa peau humaine avant de prendre la forme d'une boule de feu ou d'un oiseau noir. Arbre frontière entre le monde des vivants et celui des esprits. SACRÉ / MÉMOIRE DE L'ESCLAVAGE",
  isResistanceSymbol: true,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre géant aux contreforts imposants. Surnommé « arbre aux esclaves » et « arbre aux soukounyan ». Les esclaves récalcitrants y étaient suppliciés : attachés par des liens de cuir mouillés que le soleil rétrécissait, les épines du tronc s'enfonçant dans leur chair. Selon le folklore créole, le soukouyan (vampire antillais) vient y accrocher sa peau humaine avant de prendre la forme d'une boule de feu ou d'un oiseau noir. Arbre frontière entre le monde des vivants et celui des esprits. SACRÉ / MÉMOIRE DE L'ESCLAVAGE",
  tags: ["arbres emblématiques", "arbre", "resistance"],
  },
  {
  id: "blizl-balisi",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Bèlizèl / Balisié",
  nomFrancais: "Balisier",
  nomScientifique: "Heliconia bihai",
  usage: "Emblème de la Guadeloupe. Fleur rouge en bec. Délimite les zones du jardin.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Emblème de la Guadeloupe. Fleur rouge en bec. Délimite les zones du jardin.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "lavand-wouj-alpinia",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Lavand wouj / Alpinia",
  nomFrancais: "Alpinia / Lavande rouge",
  nomScientifique: "Alpinia purpurata",
  usage: "Grande plante ornementale (3-4 m). Délimite et embellit le jardin.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grande plante ornementale (3-4 m). Délimite et embellit le jardin.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "ti-bm-fl-porsln",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Ti-bòm / Flè porslèn",
  nomFrancais: "Fleur de porcelaine",
  nomScientifique: "Etlingera elatior",
  usage: "Grande fleur exotique. Vendue sur les marchés. Ornement du jardin.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Grande fleur exotique. Vendue sur les marchés. Ornement du jardin.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "zanno-jasmin-nwit",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Zanno / Jasmin nwit",
  nomFrancais: "Jasmin de nuit",
  nomScientifique: "Cestrum nocturnum",
  usage: "Arbuste au parfum nocturne intense. Planté aux abords de la case pour la fraîcheur.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbuste au parfum nocturne intense. Planté aux abords de la case pour la fraîcheur.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "antwiriym",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Antwiriyòm",
  nomFrancais: "Anthurium",
  nomScientifique: "Anthurium andreanum",
  usage: "Fleur tropicale rouge en cœur. Ornement des cérémonies et autels.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fleur tropicale rouge en cœur. Ornement des cérémonies et autels.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "fl-dawanj",
  categorie: "PLANTES ORNEMENTALES / SACRÉES",
  sousCategorie: "ornementale / sacrée",
  nomCreole: "Flè d'awanj",
  nomFrancais: "Fleur d'oranger",
  nomScientifique: "Citrus aurantium",
  usage: "Eau de fleur d'oranger utilisée dans les gâteaux et les prières créoles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Eau de fleur d'oranger utilisée dans les gâteaux et les prières créoles.",
  tags: ["plantes ornementales / sacrées", "ornementale / sacrée"],
  },
  {
  id: "kktye-fleur-jaune",
  categorie: "JARDIN CRÉOLE — HAIES ET BORDURES (plantes protectrices)",
  sousCategorie: "haie / bordure",
  nomCreole: "Kòkòtye / Fleur jaune",
  nomFrancais: "Coquelicot des Antilles",
  nomScientifique: "Turnera ulmifolia",
  usage: "Petite fleur jaune de bord de route et de haie. Médicinale (anti-inflammatoire).",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Petite fleur jaune de bord de route et de haie. Médicinale (anti-inflammatoire).",
  tags: ["jardin créole — haies et bordures (plantes protectrices)", "haie / bordure"],
  },
  {
  id: "banani-figi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Bananié / Figié",
  nomFrancais: "Bananier",
  nomScientifique: "Musa acuminata / paradisiaca",
  usage: "Trio fondateur du jardin créole avec manguier et ananas. Feuilles utilisées pour cuisson et emballage.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Trio fondateur du jardin créole avec manguier et ananas. Feuilles utilisées pour cuisson et emballage.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "friyapen-chtaigni-pyi",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Friyapen / Châtaignié péyi",
  nomFrancais: "Arbre à pain / Châtaignier",
  nomScientifique: "Artocarpus altilis / Sloanea massonii",
  usage: "Arbre nourricier par excellence. Le fruit à pain peut nourrir 5 personnes. Héritage amérindien.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre nourricier par excellence. Le fruit à pain peut nourrir 5 personnes. Héritage amérindien.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "sitwli-mombin",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Sitwèlié / Mombiné",
  nomFrancais: "Prunier cythère / Mombin",
  nomScientifique: "Spondias dulcis / mombin",
  usage: "Arbre caduc marquant les saisons. Jus et sorbets locaux.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre caduc marquant les saisons. Jus et sorbets locaux.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "zakasi-jacquier",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Zakasié / Jacquier",
  nomFrancais: "Jacquier",
  nomScientifique: "Artocarpus heterophyllus",
  usage: "Arbre géant à fruits énormes. Fruit mangé mûr ou vert en légume.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre géant à fruits énormes. Fruit mangé mûr ou vert en légume.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "pm-kajou",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Pòm kajou",
  nomFrancais: "Pommier cajou / Anacardier",
  nomScientifique: "Anacardium occidentale",
  usage: "Fruit rouge-jaune juteux + noix de cajou. Double récolte.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Fruit rouge-jaune juteux + noix de cajou. Double récolte.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "nfli",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Nèflié",
  nomFrancais: "Néflier du Japon",
  nomScientifique: "Eriobotrya japonica",
  usage: "Petit arbre des jardins créoles. Fruits sucrés-acidulés en grappes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Petit arbre des jardins créoles. Fruits sucrés-acidulés en grappes.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "orangi-sitwoni",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Orangié / Sitwonié",
  nomFrancais: "Oranger / Citronnier",
  nomScientifique: "Citrus sinensis / aurantiifolia",
  usage: "Agrumes incontournables. Jus, zestes, fleurs d'oranger pour pâtisserie.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Agrumes incontournables. Jus, zestes, fleurs d'oranger pour pâtisserie.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "ikani-icaquier",
  categorie: "JARDIN CRÉOLE — STRATE HAUTE (arbres fruitiers / canopée)",
  sousCategorie: "arbre fruitier",
  nomCreole: "Ikanié / Icaquier",
  nomFrancais: "Icaquier / Prunier pays",
  nomScientifique: "Chrysobalanus icaco",
  usage: "Petit arbre de haie. Fruit violet-rouge en confiture. Arbre de bordure du jardin.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Petit arbre de haie. Fruit violet-rouge en confiture. Arbre de bordure du jardin.",
  tags: ["jardin créole — strate haute (arbres fruitiers / canopée)", "arbre fruitier"],
  },
  {
  id: "kanai-canne-sucre",
  categorie: "PLANTES — SYMBOLES DE RÉSISTANCE",
  sousCategorie: "plante / résistance",
  nomCreole: "Kanaié / Canne à sucre",
  nomFrancais: "Canne à sucre",
  nomScientifique: "Saccharum officinarum",
  usage: "La canne est à la fois l'instrument de l'oppression et le lieu de la résistance. C'est dans les champs de canne que les esclaves ont forgé leur langue créole, leurs chants de travail (le Gwo Ka), leur solidarité et leurs réseaux de communication clandestins. RÉSISTANCE PARADOXALE",
  isResistanceSymbol: true,
  resistanceType: "RÉSISTANCE PARADOXALE",
  resistanceDescription: "La canne est à la fois l'instrument de l'oppression et le lieu de la résistance. C'est dans les champs de canne que les esclaves ont forgé leur langue créole, leurs chants de travail (le Gwo Ka), leur solidarité et leurs réseaux de communication clandestins.",
  sacreSymbolique: "RÉSISTANCE PARADOXALE",
  dimensionCulturelle: "La canne est à la fois l'instrument de l'oppression et le lieu de la résistance. C'est dans les champs de canne que les esclaves ont forgé leur langue créole, leurs chants de travail (le Gwo Ka), leur solidarité et leurs réseaux de communication clandestins. RÉSISTANCE PARADOXALE",
  tags: ["plantes — symboles de résistance", "plante / résistance", "resistance", "résistance-paradoxale"],
  },
  {
  id: "piman-toutes-varits",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Piman (toutes variétés)",
  nomFrancais: "Piments antillais",
  nomScientifique: "Capsicum chinense / frutescens",
  usage: "Arbuste pérenne omniprésent. Du piment végétarien au bonda man jak. Base de tout assaisonnement.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbuste pérenne omniprésent. Du piment végétarien au bonda man jak. Base de tout assaisonnement.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "tomato-pyi",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Tomato péyi",
  nomFrancais: "Tomate locale",
  nomScientifique: "Solanum lycopersicum",
  usage: "Variété locale plus petite et plus acide que les variétés industrielles.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Variété locale plus petite et plus acide que les variétés industrielles.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "ibiskis-zsy",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Ibiskis / Zòsèy",
  nomFrancais: "Hibiscus / Oseille pays",
  nomScientifique: "Hibiscus sabdariffa",
  usage: "Calices rouges en jus (bissap). Anti-cholestérol. Plante de haie ornementale.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Calices rouges en jus (bissap). Anti-cholestérol. Plante de haie ornementale.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "jenjanm",
  categorie: "JARDIN CRÉOLE — STRATE MOYENNE (arbustes et cultures vivrières)",
  sousCategorie: "arbuste / culture",
  nomCreole: "Jenjanm",
  nomFrancais: "Gingembre",
  nomScientifique: "Zingiber officinale",
  usage: "Rhizome aromatique et médicinal. Tisanes, marinades, boissons rafraîchissantes.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Rhizome aromatique et médicinal. Tisanes, marinades, boissons rafraîchissantes.",
  tags: ["jardin créole — strate moyenne (arbustes et cultures vivrières)", "arbuste / culture"],
  },
  {
  id: "patt-douce",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "plante racine",
  nomCreole: "Patàt douce",
  nomFrancais: "Patate douce",
  nomScientifique: "Ipomoea batatas",
  usage: "Racine sucrée. Desserts, gratins, beignets. Feuilles comestibles en légume vert.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Racine sucrée. Desserts, gratins, beignets. Feuilles comestibles en légume vert.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "plante racine"],
  },
  {
  id: "pwa-souch-pois-souche",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "légumineuse",
  nomCreole: "Pwa souch / Pois souche",
  nomFrancais: "Pois souche",
  nomScientifique: "Vigna unguiculata",
  usage: "Légumineuse rampante. Enrichit le sol. Graines en ragoût créole.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Légumineuse rampante. Enrichit le sol. Graines en ragoût créole.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "légumineuse"],
  },
  {
  id: "lanti-pyi",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes racines et légumineuses)",
  sousCategorie: "légumineuse",
  nomCreole: "Lanti péyi",
  nomFrancais: "Lentilles pays",
  nomScientifique: "Lens culinaris (var. locale)",
  usage: "Légumineuse du jardin vivrier créole. Soupe et ragoût.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Légumineuse du jardin vivrier créole. Soupe et ragoût.",
  tags: ["jardin créole — strate basse (plantes racines et légumineuses)", "légumineuse"],
  },
  {
  id: "basilik-pyi",
  categorie: "JARDIN CRÉOLE — STRATE BASSE (plantes aromatiques et médicinales / rimèd razié)",
  sousCategorie: "rimèd razié",
  nomCreole: "Basilik péyi",
  nomFrancais: "Basilic créole",
  nomScientifique: "Ocimum basilicum",
  usage: "Antispasmodique et digestif. Dans les accras, bouillons et marinades.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Antispasmodique et digestif. Dans les accras, bouillons et marinades.",
  tags: ["jardin créole — strate basse (plantes aromatiques et médicinales / rimèd razié)", "rimèd razié"],
  },
  {
  id: "rytrin-bwa-flotant",
  categorie: "JARDIN CRÉOLE — HAIES ET BORDURES (plantes protectrices)",
  sousCategorie: "haie / bordure",
  nomCreole: "Érytrin / Bwa flotant",
  nomFrancais: "Érythrine / Bois flotant",
  nomScientifique: "Erythrina fusca",
  usage: "Haie vive délimitant le jardin créole. Fixe l'azote. Protège les cannes des vents.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Haie vive délimitant le jardin créole. Fixe l'azote. Protège les cannes des vents.",
  tags: ["jardin créole — haies et bordures (plantes protectrices)", "haie / bordure"],
  },
  {
  id: "zanmann-amandier-pyi",
  categorie: "JARDIN CRÉOLE — HAIES ET BORDURES (plantes protectrices)",
  sousCategorie: "haie / bordure",
  nomCreole: "Zanmann / Amandier péyi",
  nomFrancais: "Amandier de plage",
  nomScientifique: "Terminalia catappa",
  usage: "Arbre de case et de haie. Ombre dense. Feuilles rouges à l'automne. Fruit comestible.",
  isResistanceSymbol: false,
  resistanceType: undefined,
  resistanceDescription: undefined,
  sacreSymbolique: undefined,
  dimensionCulturelle: "Arbre de case et de haie. Ombre dense. Feuilles rouges à l'automne. Fruit comestible.",
  tags: ["jardin créole — haies et bordures (plantes protectrices)", "haie / bordure"],
  }
];

// Index pour recherche rapide
export const floreIndex: Record<string, FloreEntry> = {
  "mangui": floreData.find(p => p.id === "mangui")!,
  "korossoli": floreData.find(p => p.id === "korossoli")!,
  "marakoudja": floreData.find(p => p.id === "marakoudja")!,
  "gwayavi": floreData.find(p => p.id === "gwayavi")!,
  "papayi": floreData.find(p => p.id === "papayi")!,
  "ananas-pyi": floreData.find(p => p.id === "ananas-pyi")!,
  "sitwl-prune-sitwl": floreData.find(p => p.id === "sitwl-prune-sitwl")!,
  "sapotiyi": floreData.find(p => p.id === "sapotiyi")!,
  "karanboli": floreData.find(p => p.id === "karanboli")!,
  "pomme-kannl": floreData.find(p => p.id === "pomme-kannl")!,
  "kent": floreData.find(p => p.id === "kent")!,
  "abwiko-pyi": floreData.find(p => p.id === "abwiko-pyi")!,
  "sriz-pyi": floreData.find(p => p.id === "sriz-pyi")!,
  "kokoti": floreData.find(p => p.id === "kokoti")!,
  "pomd-pomme-liane": floreData.find(p => p.id === "pomd-pomme-liane")!,
  "figye-figue-banane": floreData.find(p => p.id === "figye-figue-banane")!,
  "banann-pm": floreData.find(p => p.id === "banann-pm")!,
  "pwayo-poyo": floreData.find(p => p.id === "pwayo-poyo")!,
  "kalbasi": floreData.find(p => p.id === "kalbasi")!,
  "friyapen": floreData.find(p => p.id === "friyapen")!,
  "grennadi": floreData.find(p => p.id === "grennadi")!,
  "tamarin": floreData.find(p => p.id === "tamarin")!,
  "awokasi": floreData.find(p => p.id === "awokasi")!,
  "malaki-pm-malaka": floreData.find(p => p.id === "malaki-pm-malaka")!,
  "pm-sirt-girembl": floreData.find(p => p.id === "pm-sirt-girembl")!,
  "prn-mombin-mombin-jaune": floreData.find(p => p.id === "prn-mombin-mombin-jaune")!,
  "piman-vgtarien": floreData.find(p => p.id === "piman-vgtarien")!,
  "piman-bouk": floreData.find(p => p.id === "piman-bouk")!,
  "dachine": floreData.find(p => p.id === "dachine")!,
  "iyam": floreData.find(p => p.id === "iyam")!,
  "manyk": floreData.find(p => p.id === "manyk")!,
  "mad": floreData.find(p => p.id === "mad")!,
  "jiramn-giraumon": floreData.find(p => p.id === "jiramn-giraumon")!,
  "kowosol-christofen": floreData.find(p => p.id === "kowosol-christofen")!,
  "pwa-dangow": floreData.find(p => p.id === "pwa-dangow")!,
  "gombo": floreData.find(p => p.id === "gombo")!,
  "bred-chouk-chou-carabe": floreData.find(p => p.id === "bred-chouk-chou-carabe")!,
  "bwa-dind-feuilles": floreData.find(p => p.id === "bwa-dind-feuilles")!,
  "kannel": floreData.find(p => p.id === "kannel")!,
  "klou-jiwofl": floreData.find(p => p.id === "klou-jiwofl")!,
  "noumiskat": floreData.find(p => p.id === "noumiskat")!,
  "koubari-curcuma": floreData.find(p => p.id === "koubari-curcuma")!,
  "vaniy": floreData.find(p => p.id === "vaniy")!,
  "chadki": floreData.find(p => p.id === "chadki")!,
  "citwonn-citron-pyi": floreData.find(p => p.id === "citwonn-citron-pyi")!,
  "klmb": floreData.find(p => p.id === "klmb")!,
  "kakaoye": floreData.find(p => p.id === "kakaoye")!,
  "chadon-bni": floreData.find(p => p.id === "chadon-bni")!,
  "brize": floreData.find(p => p.id === "brize")!,
  "sitwonl": floreData.find(p => p.id === "sitwonl")!,
  "gwo-tim": floreData.find(p => p.id === "gwo-tim")!,
  "alowes": floreData.find(p => p.id === "alowes")!,
  "dartrier": floreData.find(p => p.id === "dartrier")!,
  "verven": floreData.find(p => p.id === "verven")!,
  "zeb-a-femme": floreData.find(p => p.id === "zeb-a-femme")!,
  "zeb-kabrit": floreData.find(p => p.id === "zeb-kabrit")!,
  "malom-malnomme": floreData.find(p => p.id === "malom-malnomme")!,
  "woucou-roucou": floreData.find(p => p.id === "woucou-roucou")!,
  "zeb-a-pik-sensitive": floreData.find(p => p.id === "zeb-a-pik-sensitive")!,
  "patchouli-pyi": floreData.find(p => p.id === "patchouli-pyi")!,
  "zeb-a-vers": floreData.find(p => p.id === "zeb-a-vers")!,
  "gommi-blan": floreData.find(p => p.id === "gommi-blan")!,
  "flanbwayan": floreData.find(p => p.id === "flanbwayan")!,
  "figuiye-modi-figuier-maudit": floreData.find(p => p.id === "figuiye-modi-figuier-maudit")!,
  "palmis-montagn": floreData.find(p => p.id === "palmis-montagn")!,
  "acoma-boukan-acajou": floreData.find(p => p.id === "acoma-boukan-acajou")!,
  "woz-laps": floreData.find(p => p.id === "woz-laps")!,
  "paltuwy": floreData.find(p => p.id === "paltuwy")!,
  "fromaj": floreData.find(p => p.id === "fromaj")!,
  "blizl-balisi": floreData.find(p => p.id === "blizl-balisi")!,
  "lavand-wouj-alpinia": floreData.find(p => p.id === "lavand-wouj-alpinia")!,
  "ti-bm-fl-porsln": floreData.find(p => p.id === "ti-bm-fl-porsln")!,
  "zanno-jasmin-nwit": floreData.find(p => p.id === "zanno-jasmin-nwit")!,
  "antwiriym": floreData.find(p => p.id === "antwiriym")!,
  "fl-dawanj": floreData.find(p => p.id === "fl-dawanj")!,
  "kktye-fleur-jaune": floreData.find(p => p.id === "kktye-fleur-jaune")!,
  "banani-figi": floreData.find(p => p.id === "banani-figi")!,
  "friyapen-chtaigni-pyi": floreData.find(p => p.id === "friyapen-chtaigni-pyi")!,
  "sitwli-mombin": floreData.find(p => p.id === "sitwli-mombin")!,
  "zakasi-jacquier": floreData.find(p => p.id === "zakasi-jacquier")!,
  "pm-kajou": floreData.find(p => p.id === "pm-kajou")!,
  "nfli": floreData.find(p => p.id === "nfli")!,
  "orangi-sitwoni": floreData.find(p => p.id === "orangi-sitwoni")!,
  "ikani-icaquier": floreData.find(p => p.id === "ikani-icaquier")!,
  "kanai-canne-sucre": floreData.find(p => p.id === "kanai-canne-sucre")!,
  "piman-toutes-varits": floreData.find(p => p.id === "piman-toutes-varits")!,
  "tomato-pyi": floreData.find(p => p.id === "tomato-pyi")!,
  "ibiskis-zsy": floreData.find(p => p.id === "ibiskis-zsy")!,
  "jenjanm": floreData.find(p => p.id === "jenjanm")!,
  "patt-douce": floreData.find(p => p.id === "patt-douce")!,
  "pwa-souch-pois-souche": floreData.find(p => p.id === "pwa-souch-pois-souche")!,
  "lanti-pyi": floreData.find(p => p.id === "lanti-pyi")!,
  "basilik-pyi": floreData.find(p => p.id === "basilik-pyi")!,
  "rytrin-bwa-flotant": floreData.find(p => p.id === "rytrin-bwa-flotant")!,
  "zanmann-amandier-pyi": floreData.find(p => p.id === "zanmann-amandier-pyi")!
};

// Fonction utilitaire
export function getFloreByNomCreole(nom: string): FloreEntry | undefined {
  return floreData.find(p => 
    p.nomCreole.toLowerCase() === nom.toLowerCase() ||
    p.nomCreole.toLowerCase().includes(nom.toLowerCase())
  );
}
