export interface HistoireEntry {
  id: string;
  periode: string;
  faitHistorique: string;
  porteeSymbolique: string;
  actionsMenees: string;
  lieu: string;
  pratiquesSpirituelles: string;
  tags: string[];
}


// Données générées automatiquement depuis histoire_guadeloupe_ref.md
// NE PAS MODIFIER MANUELLEMENT - Exécuter 'npm run histoire:parse' pour mettre à jour
export const histoireData: HistoireEntry[] = [
  {
  id: "avant300avj-c-peuplementinitialdelaguade-0",
  periode: "**Avant 300 av. J.-C.**",
  faitHistorique: "Peuplement initial de la Guadeloupe par des groupes amérindiens (premiers habitants, probablement des groupes archaïques)",
  porteeSymbolique: "**Premières racines identitaires : société égalitaire, adaptation au milieu insulaire**",
  actionsMenees: "Chasse, cueillette, pêche, utilisation d’outils en pierre",
  lieu: "Karukera (Guadeloupe actuelle), zones côtières et intérieures",
  pratiquesSpirituelles: "Culte des esprits de la nature, rituels pour la fertilité et la protection contre les éléments",
  tags: ["**premières racines identitaires : société égalitaire", "adaptation au milieu insulaire**", "karukera (guadeloupe actuelle)", "zones côtières et intérieures"],
  },
  {
  id: "300avj-c300apj-c-arriveedestainosarawaks-1",
  periode: "**300 av. J.-C. – 300 ap. J.-C.**",
  faitHistorique: "**Arrivée des Taïnos (Arawaks) en Guadeloupe**",
  porteeSymbolique: "**Civilisation taïno : société agricole sédentaire, organisation en *caciquats* (chefferies), maîtrise de l’agriculture sur brûlis et de la poterie**",
  actionsMenees: "Culture du **manioc** (avec la technique du *conuco*), du maïs, de la patate douce, fabrication de poteries à motifs géométriques, tissage de hamacs en coton",
  lieu: "Zones côtières de **Grande-Terre** (ex. : Anse-Bertrand, Port-Louis) et **Basse-Terre**, ainsi que les petites îles environnantes (ex. : Les Saintes, Marie-Galante)",
  pratiquesSpirituelles: "**Culte des *zemis*** :",
  tags: ["**civilisation taïno : société agricole sédentaire", "organisation en *caciquats* (chefferies)", "maîtrise de l’agriculture sur brûlis et de la poterie**", "zones côtières de **grande-terre** (ex. : anse-bertrand", "port-louis) et **basse-terre**", "ainsi que les petites îles environnantes (ex. : les saintes", "marie-galante)"],
  },
  {
  id: "6001500apj-c-traitetranssaharienneetro-2",
  periode: "**600–1500 ap. J.-C.**",
  faitHistorique: "**Traite transsaharienne et rôle des marchands musulmans (Arabes, Berbères)**",
  porteeSymbolique: "**Esclavage précoce : capture et déportation de millions d'Africains vers le monde arabe et musulman, souvent occulté dans l'histoire atlantique. Travaux de Tidiane N'Diaye (*Le Génocide voilé*, 2008) et Malek Chebel soulignent l'ampleur de ce commerce.**",
  actionsMenees: "**Résistance des captifs africains** : révoltes dans les caravanes, fuites vers les oasis, maintien des traditions spirituelles (ex. : culte des ancêtres). Transmission orale des récits de résistance.",
  lieu: "**Afrique de l'Ouest et du Centre** (ex. : Ghana, Mali, Nigeria, Tchad), routes transsahariennes (ex. : Tombouctou, Gao)",
  pratiquesSpirituelles: "**Spiritualité africaine pré-islamique** :",
  tags: ["**esclavage précoce : capture et déportation de millions d'africains vers le monde arabe et musulman", "souvent occulté dans l'histoire atlantique. travaux de tidiane n'diaye (*le génocide voilé*", "2008) et malek chebel soulignent l'ampleur de ce commerce.**", "**afrique de l'ouest et du centre** (ex. : ghana", "mali", "nigeria", "tchad)", "routes transsahariennes (ex. : tombouctou", "gao)"],
  },
  {
  id: "1635-prisedepossessionfrancais-3",
  periode: "**1635**",
  faitHistorique: "**Prise de possession française par Liénard de l’Olive et Duplessis d’Ossonville**",
  porteeSymbolique: "**Début de l’acculturation forcée : imposition du catholicisme, du français, destruction des structures amérindiennes**",
  actionsMenees: "Refus de participer aux messes catholiques, maintien des cultes ancestraux (ex. : rituels de la *Déesse Mère*), cache des idoles en bois",
  lieu: "Pointe Allègre (Basse-Terre)",
  pratiquesSpirituelles: "Syncrétisme forcé : mélange des croyances amérindiennes avec le catholicisme (ex. : culte de la Vierge Marie associé à la *Déesse Mère*)",
  tags: ["**début de l’acculturation forcée : imposition du catholicisme", "du français", "destruction des structures amérindiennes**", "pointe allègre (basse-terre)"],
  },
  {
  id: "1635-debutdelatraitenegriere-4",
  periode: "**1635**",
  faitHistorique: "**Début de la traite négrière en Guadeloupe**",
  porteeSymbolique: "**Remplacement des Amérindiens par des Africains : début d’un nouveau système esclavagiste, rupture totale avec le passé autochtone**",
  actionsMenees: "Révoltes à bord des navires négriers (ex. : soulèvement du *Négrier Le Rodeur* en 1819), sabotage des entrepôts de traite",
  lieu: "Port de Basse-Terre",
  pratiquesSpirituelles: "Introduction du vaudou africain : culte des *loas* (ex. : *Legba*, *Damballa*), rituels de protection pour les nouveaux arrivants",
  tags: ["**remplacement des amérindiens par des africains : début d’un nouveau système esclavagiste", "rupture totale avec le passé autochtone**", "port de basse-terre"],
  },
  {
  id: "16351650-introductiondespremierses-5",
  periode: "**1635–1650**",
  faitHistorique: "**Introduction des premiers esclaves africains**",
  porteeSymbolique: "**Début de l’exploitation humaine : travail forcé, séparation des familles, traumatisme de la déportation**",
  actionsMenees: "Fuite vers les *mornes* (zones montagneuses), création de communautés de marrons (ex. : *Nègres Marrons* de la Soufrière)",
  lieu: "Plantations de la Côte-sous-le-Vent (Habitation La Grivelière)",
  pratiquesSpirituelles: "Vaudou Rada : rituels de guérison (ex. : utilisation de *feuilles de mapou* pour soigner), culte des ancêtres",
  tags: ["**début de l’exploitation humaine : travail forcé", "séparation des familles", "traumatisme de la déportation**", "plantations de la côte-sous-le-vent (habitation la grivelière)"],
  },
  {
  id: "16351650-developpementdesplantation-6",
  periode: "**1635–1650**",
  faitHistorique: "**Développement des plantations de tabac**",
  porteeSymbolique: "**Transformation économique forcée : destruction des cultures vivrières, imposition d’un modèle colonial**",
  actionsMenees: "Brûlage des champs de tabac la nuit, vol des outils des colons pour les rendre inutilisables",
  lieu: "Plaines de Grande-Terre (Petit-Canal)",
  pratiquesSpirituelles: "Vaudou de résistance : rituels pour maudire les colons (ex. : *pwen* enfouis dans les champs)",
  tags: ["**transformation économique forcée : destruction des cultures vivrières", "imposition d’un modèle colonial**", "plaines de grande-terre (petit-canal)"],
  },
  {
  id: "16501685-transitionverslesplantati-7",
  periode: "**1650–1685**",
  faitHistorique: "**Transition vers les plantations de canne à sucre**",
  porteeSymbolique: "**Escalade de l’exploitation : conditions de travail inhumaines, destruction de l’environnement**",
  actionsMenees: "Sabotage des moulins à sucre avec du sable, utilisation de plantes toxiques (ex. : *manchineel*) pour empoisonner les sols",
  lieu: "Habitations sucrières de la Côte-au-Vent (La Mahaudière, Le Moule)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels de combat (ex. : invocation de *Ogoun* pour donner du courage aux esclaves)",
  tags: ["**escalade de l’exploitation : conditions de travail inhumaines", "destruction de l’environnement**", "habitations sucrières de la côte-au-vent (la mahaudière", "le moule)"],
  },
  {
  id: "1685-publicationducodenoir-8",
  periode: "**1685**",
  faitHistorique: "**Publication du Code Noir**",
  porteeSymbolique: "**Institutionnalisation de la barbarie : cadre légal pour l’oppression des Noirs, destruction des liens familiaux**",
  actionsMenees: "Mariages clandestins la nuit, création de *zandoli* (réseaux de solidarité) pour protéger les enfants des ventes",
  lieu: "Toutes les plantations de Guadeloupe",
  pratiquesSpirituelles: "Vaudou Kongolais : culte des esprits des ancêtres (ex. : *Nzambi*), rituels pour briser les chaînes de l’esclavage",
  tags: ["**institutionnalisation de la barbarie : cadre légal pour l’oppression des noirs", "destruction des liens familiaux**", "toutes les plantations de guadeloupe"],
  },
  {
  id: "1685-lecodenoirinterditlesma-9",
  periode: "**1685**",
  faitHistorique: "**Le Code Noir interdit les mariages entre esclaves**",
  porteeSymbolique: "**Destruction des liens familiaux : outil de déshumanisation, contrôle total de la vie privée**",
  actionsMenees: "Cérémonies de mariage secrètes dans les bois, adoption d’enfants orphelins par des familles de marrons",
  lieu: "Forêts de la Soufrière (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Ibo : rituels de protection des familles (ex. : *Asson* utilisé pour bénir les unions clandestines)",
  tags: ["**destruction des liens familiaux : outil de déshumanisation", "contrôle total de la vie privée**", "forêts de la soufrière (basse-terre)"],
  },
  {
  id: "1685-lecodenoirautoriselesch-10",
  periode: "**1685**",
  faitHistorique: "**Le Code Noir autorise les châtiments corporels**",
  porteeSymbolique: "**Légalisation de la violence : symboles de la cruauté du système, terreur permanente**",
  actionsMenees: "Révoltes dans les plantations (ex. : révolte de 1686 à la Habitation La Mahaudière), empoisonnement des surveillants",
  lieu: "Habitation La Mahaudière (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Nago : invocation de *Shango* (loa de la justice) pour punir les colons, rituels de vengeance",
  tags: ["**légalisation de la violence : symboles de la cruauté du système", "terreur permanente**", "habitation la mahaudière (basse-terre)"],
  },
  {
  id: "16851759-laguadeloupedevientuneco-11",
  periode: "**1685–1759**",
  faitHistorique: "**La Guadeloupe devient une colonie royale française**",
  porteeSymbolique: "**Légitimation de l’esclavage par l’État : centralisation de l’oppression, enrichissement de la métropole**",
  actionsMenees: "Échange d’informations entre plantations via des *tambours parlants*, organisation de *veillées* pour planifier les révoltes",
  lieu: "Toutes les habitations de Grande-Terre et Basse-Terre",
  pratiquesSpirituelles: "Vaudou Rada : utilisation des *tambours salé* pour communiquer entre communautés, culte de *Damballa*",
  tags: ["**légitimation de l’esclavage par l’état : centralisation de l’oppression", "enrichissement de la métropole**", "toutes les habitations de grande-terre et basse-terre"],
  },
  {
  id: "16851759-expansiondesplantationsde-12",
  periode: "**1685–1759**",
  faitHistorique: "**Expansion des plantations de canne à sucre**",
  porteeSymbolique: "**Enrichissement des colons sur le dos des esclaves : exploitation maximale, destruction des écosystèmes**",
  actionsMenees: "Destruction des cannes à sucre avec des couteaux, vol de bétail pour nourrir les communautés de marrons",
  lieu: "Plaines de Grande-Terre (Le Moule, Petit-Bourg)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels de malédiction (ex. : *pwen de mort* contre les surveillants), invocation de *Baron Samedi*",
  tags: ["**enrichissement des colons sur le dos des esclaves : exploitation maximale", "destruction des écosystèmes**", "plaines de grande-terre (le moule", "petit-bourg)"],
  },
  {
  id: "17591763-occupationbritanniquedela-13",
  periode: "**1759–1763**",
  faitHistorique: "**Occupation britannique de la Guadeloupe**",
  porteeSymbolique: "**Changement de colonisateur : introduction de l’anglais, nouvelles dynamiques culturelles, mais même oppression**",
  actionsMenees: "Collaboration avec les Britanniques pour obtenir des armes, espionnage des mouvements de troupes françaises",
  lieu: "Basse-Terre (siège du pouvoir britannique)",
  pratiquesSpirituelles: "Syncrétisme vaudou-anglican : intégration de chants en anglais dans les rituels, culte de *Legba* pour ouvrir les chemins",
  tags: ["**changement de colonisateur : introduction de l’anglais", "nouvelles dynamiques culturelles", "mais même oppression**", "basse-terre (siège du pouvoir britannique)"],
  },
  {
  id: "17591763-resistancedesesclavessous-14",
  periode: "**1759–1763**",
  faitHistorique: "**Résistance des esclaves sous domination britannique**",
  porteeSymbolique: "**Adaptation et lutte continue : même sous domination britannique, la résistance persiste**",
  actionsMenees: "Fuite vers la Dominique et la Martinique, création de réseaux de marrons transnationaux",
  lieu: "Zones côtières (Pointe-à-Pitre, Basse-Terre)",
  pratiquesSpirituelles: "Échanges de savoirs vaudou avec les marrons des îles voisines (ex. : rites *Kongo* pour la protection)",
  tags: ["**adaptation et lutte continue : même sous domination britannique", "la résistance persiste**", "zones côtières (pointe-à-pitre", "basse-terre)"],
  },
  {
  id: "1763-restitutiondelaguadeloupe-15",
  periode: "**1763**",
  faitHistorique: "**Restitution de la Guadeloupe à la France (Traité de Paris)**",
  porteeSymbolique: "**Retour à l’oppression française : trahison des promesses britanniques, reprise de la terreur**",
  actionsMenees: "Révoltes immédiates dans les plantations de la Côte-sous-le-Vent, refus de travailler pour les nouveaux colons",
  lieu: "Côte-sous-le-Vent (Bouillante, Deshaies)",
  pratiquesSpirituelles: "Vaudou de la colère : rituels pour maudire les Français (ex. : *pwen* jetés dans les rivières)",
  tags: ["**retour à l’oppression française : trahison des promesses britanniques", "reprise de la terreur**", "côte-sous-le-vent (bouillante", "deshaies)"],
  },
  {
  id: "17631789-renforcementdusystemeplan-16",
  periode: "**1763–1789**",
  faitHistorique: "**Renforcement du système plantationnaire**",
  porteeSymbolique: "**Intensification de l’exploitation : vie des esclaves de plus en plus dure, travail forcé accru**",
  actionsMenees: "Grèves sauvages (ex. : arrêt du travail dans les champs de canne en 1776), ralentissement coordonné des récoltes",
  lieu: "Plantations de Grande-Terre (Le Moule, Sainte-Anne)",
  pratiquesSpirituelles: "Vaudou Rada : rituels de fertilité pour les terres volées, culte de *Ezili Freda* (loa de l’amour)",
  tags: ["**intensification de l’exploitation : vie des esclaves de plus en plus dure", "travail forcé accru**", "plantations de grande-terre (le moule", "sainte-anne)"],
  },
  {
  id: "1789-influencedesideesrevoluti-17",
  periode: "**1789**",
  faitHistorique: "**Influence des idées révolutionnaires en Guadeloupe**",
  porteeSymbolique: "**Espoir de liberté : les idéaux de 1789 inspirent les esclaves, preuve que le système peut être vaincu**",
  actionsMenees: "Diffusion clandestine de pamphlets révolutionnaires, organisation de réunions secrètes",
  lieu: "Pointe-à-Pitre (centre urbain), habitations de la Côte-au-Vent",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour invoquer *Ogoun* et *Boukman* (esprit de la révolte haïtienne)",
  tags: ["**espoir de liberté : les idéaux de 1789 inspirent les esclaves", "preuve que le système peut être vaincu**", "pointe-à-pitre (centre urbain)", "habitations de la côte-au-vent"],
  },
  {
  id: "17891794-revoltesdesclavesinspiree-18",
  periode: "**1789–1794**",
  faitHistorique: "**Révoltes d’esclaves inspirées par la Révolution française**",
  porteeSymbolique: "**Lutte pour la dignité : refus de l’oppression malgré les risques, solidarité entre esclaves**",
  actionsMenees: "Révolte armée de 1789 à la Habitation La Mahaudière, coordination avec les libres de couleur",
  lieu: "Habitation La Mahaudière (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels de purification avant les combats, invocation de *Nzambi* pour la victoire",
  tags: ["**lutte pour la dignité : refus de l’oppression malgré les risques", "solidarité entre esclaves**", "habitation la mahaudière (basse-terre)"],
  },
  {
  id: "1794-premiereabolitiondelescl-19",
  periode: "**1794**",
  faitHistorique: "**Première abolition de l’esclavage par Victor Hugues**",
  porteeSymbolique: "**Victoire arrachée par la lutte : preuve que la résistance porte ses fruits, mais liberté temporaire**",
  actionsMenees: "Participation aux combats aux côtés des commissaires Sonthonax et Polverel, création de milices noires",
  lieu: "Basse-Terre (siège du pouvoir révolutionnaire)",
  pratiquesSpirituelles: "Vaudou Rada : célébrations avec des *Léwoz*, culte de *Damballa* pour la paix",
  tags: ["**victoire arrachée par la lutte : preuve que la résistance porte ses fruits", "mais liberté temporaire**", "basse-terre (siège du pouvoir révolutionnaire)"],
  },
  {
  id: "1794-liberationtemporairedeses-20",
  periode: "**1794**",
  faitHistorique: "**Libération temporaire des esclaves**",
  porteeSymbolique: "**Période de liberté relative : développement culturel et social, mais menace constante de retour en arrière**",
  actionsMenees: "Ouverture d’écoles pour les anciens esclaves (ex. : à Basse-Terre), développement de l’artisanat",
  lieu: "Basse-Terre, Pointe-à-Pitre, zones urbaines et rurales",
  pratiquesSpirituelles: "Vaudou de la reconstruction : rituels pour bénir les nouvelles terres cultivées, culte de *Legba*",
  tags: ["**période de liberté relative : développement culturel et social", "mais menace constante de retour en arrière**", "basse-terre", "pointe-à-pitre", "zones urbaines et rurales"],
  },
  {
  id: "1794-participationdesancienses-21",
  periode: "**1794**",
  faitHistorique: "**Participation des anciens esclaves à la vie politique**",
  porteeSymbolique: "**Affirmation de la citoyenneté : premier pas vers l’égalité, mais exclusion persistante**",
  actionsMenees: "Élection de représentants noirs (ex. : Jean-Baptiste Mars), revendications pour l’égalité des droits",
  lieu: "Basse-Terre (centre administratif), Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour protéger les leaders noirs (ex. : *pwen de protection*)",
  tags: ["**affirmation de la citoyenneté : premier pas vers l’égalité", "mais exclusion persistante**", "basse-terre (centre administratif)", "pointe-à-pitre"],
  },
  {
  id: "17941802-developpementdelaculture-22",
  periode: "**1794–1802**",
  faitHistorique: "**Développement de la culture créole et des traditions**",
  porteeSymbolique: "**Résistance culturelle : préservation de l’identité malgré l’oppression, création d’une culture métissée**",
  actionsMenees: "Création de chants en créole (ex. : *Chanté Nwèl*), transmission orale des histoires de résistance",
  lieu: "Toute l’île, surtout zones rurales (Les Abymes, Baie-Mahault)",
  pratiquesSpirituelles: "Vaudou Rada : intégration des chants en créole dans les rituels, culte de *Ezili*",
  tags: ["**résistance culturelle : préservation de l’identité malgré l’oppression", "création d’une culture métissée**", "toute l’île", "surtout zones rurales (les abymes", "baie-mahault)"],
  },
  {
  id: "17941802-educationetalphabetisation-23",
  periode: "**1794–1802**",
  faitHistorique: "**Éducation et alphabétisation des anciens esclaves**",
  porteeSymbolique: "**Outils pour l’émancipation : préparation à une liberté durable, mais accès limité**",
  actionsMenees: "Ouverture d’écoles clandestines (ex. : à Les Abymes), apprentissage de la lecture et de l’écriture",
  lieu: "Les Abymes, Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou de l’éducation : rituels pour bénir les livres et les outils d’écriture",
  tags: ["**outils pour l’émancipation : préparation à une liberté durable", "mais accès limité**", "les abymes", "pointe-à-pitre"],
  },
  {
  id: "1802-retablissementdelesclavag-24",
  periode: "**1802**",
  faitHistorique: "**Rétablissement de l’esclavage par Napoléon**",
  porteeSymbolique: "**Trahison révolutionnaire : retour à la barbarie, choc traumatique pour les Guadeloupéens**",
  actionsMenees: "Révolte générale de 1802, menée par Louis Delgrès et Joseph Ignace, tactique de la terre brûlée",
  lieu: "Matouba (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels de guerre avant le combat (ex. : *bain de protection* avec des herbes)",
  tags: ["**trahison révolutionnaire : retour à la barbarie", "choc traumatique pour les guadeloupéens**", "matouba (basse-terre)"],
  },
  {
  id: "1802-repressionbrutaledesrevol-25",
  periode: "**1802**",
  faitHistorique: "**Répression brutale des révoltes (ex. : Pointe-à-Pitre)**",
  porteeSymbolique: "**Massacres : renforcement de la détermination à résister, mémoire des martyrs**",
  actionsMenees: "Résistance jusqu’à la mort (ex. : suicide collectif de Delgrès et ses hommes à Matouba)",
  lieu: "Matouba (Basse-Terre), Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Gede : rituels pour honorer les martyrs (ex. : invocation des *Gede* pour apaiser les esprits)",
  tags: ["**massacres : renforcement de la détermination à résister", "mémoire des martyrs**", "matouba (basse-terre)", "pointe-à-pitre"],
  },
  {
  id: "1802-resistancedelouisdelgres-26",
  periode: "**1802**",
  faitHistorique: "**Résistance de Louis Delgrès et ses compagnons**",
  porteeSymbolique: "**Symbole du courage : refus de la reddition, sacrifice pour la liberté**",
  actionsMenees: "Combat jusqu’au bout à Matouba, utilisation de la tactique de la terre brûlée",
  lieu: "Matouba (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels de sacrifice (ex. : offrandes de rhum et de poulets noirs)",
  tags: ["**symbole du courage : refus de la reddition", "sacrifice pour la liberté**", "matouba (basse-terre)"],
  },
  {
  id: "1802-lamulatressesolitudehero-27",
  periode: "**1802**",
  faitHistorique: "**La mulâtresse Solitude, héroïne de la résistance**",
  porteeSymbolique: "**Incarne la lutte des femmes : courage, détermination, mémoire de la résistance héroïque**",
  actionsMenees: "Participation active aux combats, cri de guerre : *« Vivre libre ou mourir ! »*",
  lieu: "Matouba et ses environs (Basse-Terre)",
  pratiquesSpirituelles: "Vaudou Ezili : rituels pour honorer les femmes résistantes (ex. : culte de *Ezili Danto*)",
  tags: ["**incarne la lutte des femmes : courage", "détermination", "mémoire de la résistance héroïque**", "matouba et ses environs (basse-terre)"],
  },
  {
  id: "18021815-resistancepassivemarronn-28",
  periode: "**1802–1815**",
  faitHistorique: "**Résistance passive : marronnage, sabotage des outils**",
  porteeSymbolique: "**Stratégies de survie : préservation de la dignité au quotidien, défi contre le système**",
  actionsMenees: "Fuite massive vers les mornes (ex. : La Soufrière), création de villages de marrons",
  lieu: "Mornes de la Soufrière (Basse-Terre), zones reculées de Grande-Terre",
  pratiquesSpirituelles: "Vaudou des marrons : rituels de protection des villages cachés (ex. : *pwen* enterrés aux entrées)",
  tags: ["**stratégies de survie : préservation de la dignité au quotidien", "défi contre le système**", "mornes de la soufrière (basse-terre)", "zones reculées de grande-terre"],
  },
  {
  id: "18021815-transmissionoraledeshisto-29",
  periode: "**1802–1815**",
  faitHistorique: "**Transmission orale des histoires et chants de résistance**",
  porteeSymbolique: "**Mémoire collective : outils pour maintenir l’espoir, transmission des valeurs**",
  actionsMenees: "Création de contes (ex. : *Ti-Jean et le Diable*), chants codés (ex. : *Lavwa Deyè*)",
  lieu: "Toute l’île, surtout communautés de marrons et zones rurales",
  pratiquesSpirituelles: "Vaudou Rada : utilisation des chants et des contes dans les rituels",
  tags: ["**mémoire collective : outils pour maintenir l’espoir", "transmission des valeurs**", "toute l’île", "surtout communautés de marrons et zones rurales"],
  },
  {
  id: "18021815-developpementdugwokacomme-30",
  periode: "**1802–1815**",
  faitHistorique: "**Développement du Gwoka comme moyen d’expression**",
  porteeSymbolique: "**Arme culturelle : défi contre l’assimilation forcée, affirmation de l’identité**",
  actionsMenees: "Création des premiers rythmes Gwoka (ex. : *Léwoz*), utilisation des tambours *ka*",
  lieu: "Zones rurales (Sainte-Rose, Deshaies)",
  pratiquesSpirituelles: "Vaudou Petwo : intégration des rythmes Gwoka dans les rituels (ex. : *tambour Salé*)",
  tags: ["**arme culturelle : défi contre l’assimilation forcée", "affirmation de l’identité**", "zones rurales (sainte-rose", "deshaies)"],
  },
  {
  id: "18151848-persistancedesrevoltesloc-31",
  periode: "**1815–1848**",
  faitHistorique: "**Persistance des révoltes locales contre l’esclavage**",
  porteeSymbolique: "**Pression constante : rappel que la liberté est un droit inaliénable, refus de l’oppression**",
  actionsMenees: "Révoltes en 1822 (ex. : à La Grande Anse) et 1831, coordination avec Cyrille Bissette",
  lieu: "La Grande Anse (Basse-Terre), plantations de la Côte-sous-le-Vent",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels de rébellion (ex. : *pwen de révolte* enterrés dans les champs)",
  tags: ["**pression constante : rappel que la liberté est un droit inaliénable", "refus de l’oppression**", "la grande anse (basse-terre)", "plantations de la côte-sous-le-vent"],
  },
  {
  id: "18151848-influencedesmouvementsabo-32",
  periode: "**1815–1848**",
  faitHistorique: "**Influence des mouvements abolitionnistes en France**",
  porteeSymbolique: "**Espoir renouvelé : soutien extérieur à la lutte, pression sur le système colonial**",
  actionsMenees: "Envoi de pétitions aux autorités françaises, collaboration avec Victor Schœlcher",
  lieu: "Pointe-à-Pitre (centre administratif), Basse-Terre",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour bénir les pétitions (ex. : offrandes à *Legba*)",
  tags: ["**espoir renouvelé : soutien extérieur à la lutte", "pression sur le système colonial**", "pointe-à-pitre (centre administratif)", "basse-terre"],
  },
  {
  id: "18151848-resistanceculturellecont-33",
  periode: "**1815–1848**",
  faitHistorique: "**Résistance culturelle : contes, musique, religion**",
  porteeSymbolique: "**Préservation de l’identité : défi contre l’oppression, transmission des traditions**",
  actionsMenees: "Pratique secrète du vaudou (ex. : cérémonies pour *Papa Legba*), organisation de veillées",
  lieu: "Forêts de Basse-Terre (Soufrière)",
  pratiquesSpirituelles: "Vaudou Ibo : rituels de divination (ex. : *tire kart*) pour prédire les révoltes",
  tags: ["**préservation de l’identité : défi contre l’oppression", "transmission des traditions**", "forêts de basse-terre (soufrière)"],
  },
  {
  id: "18151848-conditionsdevieprecaires-34",
  periode: "**1815–1848**",
  faitHistorique: "**Conditions de vie précaires pour les esclaves**",
  porteeSymbolique: "**Résilience : survie malgré les privations et la violence, solidarité communautaire**",
  actionsMenees: "Entraide entre esclaves (ex. : partage de la *provision*), utilisation de plantes médicinales",
  lieu: "Toutes les plantations, surtout zones rurales",
  pratiquesSpirituelles: "Vaudou de la survie : rituels de guérison (ex. : *bain de feuilles* pour soigner les maladies)",
  tags: ["**résilience : survie malgré les privations et la violence", "solidarité communautaire**", "toutes les plantations", "surtout zones rurales"],
  },
  {
  id: "1848-revoltesdesclavesenmai1-35",
  periode: "**1848**",
  faitHistorique: "**Révoltes d’esclaves en mai 1848 (inspirées par la Martinique)**",
  porteeSymbolique: "**Dernier effort pour la liberté : pression décisive pour l’abolition, solidarité inter-îles**",
  actionsMenees: "Soulèvement généralisé en mai 1848, occupation des plantations (ex. : Habitation La Grivelière)",
  lieu: "Habitation La Grivelière (Basse-Terre), toute l’île",
  pratiquesSpirituelles: "Vaudou Petwo : rituels de libération (ex. : *pwen de rupture* pour briser les chaînes symboliques)",
  tags: ["**dernier effort pour la liberté : pression décisive pour l’abolition", "solidarité inter-îles**", "habitation la grivelière (basse-terre)", "toute l’île"],
  },
  {
  id: "27avril1848-deuxiemeabolitiondelescl-36",
  periode: "**27 avril 1848**",
  faitHistorique: "**Deuxième abolition de l’esclavage (décret Schœlcher)**",
  porteeSymbolique: "**Libération officielle, mais sans réparations : liberté politique sans justice économique**",
  actionsMenees: "Célébrations massives avec des *Léwoz*, revendications de terres et d’indemnisations",
  lieu: "Toute l’île, surtout Pointe-à-Pitre et Basse-Terre",
  pratiquesSpirituelles: "Vaudou Rada : grandes cérémonies de remerciement (ex. : offrandes collectives à *Damballa* et *Ezili*)",
  tags: ["**libération officielle", "mais sans réparations : liberté politique sans justice économique**", "toute l’île", "surtout pointe-à-pitre et basse-terre"],
  },
  {
  id: "27avril1848-liberationdes87000esclav-37",
  periode: "**27 avril 1848**",
  faitHistorique: "**Libération des 87 000 esclaves en Guadeloupe**",
  porteeSymbolique: "**Fin de l’esclavage, mais début d’une nouvelle lutte : transition difficile vers une liberté réelle**",
  actionsMenees: "Création de coopératives agricoles (ex. : à Capesterre), tentative de rachat de terres",
  lieu: "Capesterre (Basse-Terre), zones rurales de Grande-Terre",
  pratiquesSpirituelles: "Vaudou de la reconstruction : rituels pour bénir les nouvelles terres (ex. : *pwen de fertilité*)",
  tags: ["**fin de l’esclavage", "mais début d’une nouvelle lutte : transition difficile vers une liberté réelle**", "capesterre (basse-terre)", "zones rurales de grande-terre"],
  },
  {
  id: "27avril1848-transitiondifficileversle-38",
  periode: "**27 avril 1848**",
  faitHistorique: "**Transition difficile vers le travail salarié**",
  porteeSymbolique: "**Exploitation continue : conditions précaires, persistance des inégalités**",
  actionsMenees: "Grèves pour de meilleurs salaires (ex. : grève des ouvriers agricoles de 1849), refus des contrats abusifs",
  lieu: "Plantations de Grande-Terre (Le Moule, Sainte-Anne)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels contre l’exploitation (ex. : *pwen de justice* pour punir les anciens colons)",
  tags: ["**exploitation continue : conditions précaires", "persistance des inégalités**", "plantations de grande-terre (le moule", "sainte-anne)"],
  },
  {
  id: "27avril1848-affirmationdelaculturecr-39",
  periode: "**27 avril 1848**",
  faitHistorique: "**Affirmation de la culture créole et africaine**",
  porteeSymbolique: "**Victoire culturelle : reconnaissance de l’identité guadeloupéenne, mais lutte persistante contre le racisme**",
  actionsMenees: "Développement du Gwoka et du *Bigi Poko*, organisation de fêtes (ex. : *Fête des Morts*)",
  lieu: "Toute l’île, surtout zones rurales (Les Abymes, Baie-Mahault)",
  pratiquesSpirituelles: "Vaudou Rada : intégration du Gwoka dans les rituels (ex. : *tambour Assotor*)",
  tags: ["**victoire culturelle : reconnaissance de l’identité guadeloupéenne", "mais lutte persistante contre le racisme**", "toute l’île", "surtout zones rurales (les abymes", "baie-mahault)"],
  },
  {
  id: "27avril1848-celebrationdu27maicomme-40",
  periode: "**27 avril 1848**",
  faitHistorique: "**Célébration du 27 mai comme jour de la liberté**",
  porteeSymbolique: "**Mémoire collective : hommage aux luttes passées, transmission aux générations futures**",
  actionsMenees: "Création de chants (ex. : *Chanté 27 Mèy*) et de danses pour commémorer l’abolition",
  lieu: "Toute l’île, surtout villages (Sainte-Rose, Deshaies)",
  pratiquesSpirituelles: "Vaudou Gede : rituels pour honorer les ancêtres (ex. : *Gede Nibo* invoqué pour apaiser les esprits)",
  tags: ["**mémoire collective : hommage aux luttes passées", "transmission aux générations futures**", "toute l’île", "surtout villages (sainte-rose", "deshaies)"],
  },
  {
  id: "18481900-persistancedesinegalitese-41",
  periode: "**1848–1900**",
  faitHistorique: "**Persistance des inégalités économiques et sociales**",
  porteeSymbolique: "**Héritage de l’esclavage : lutte continue pour la justice sociale et économique**",
  actionsMenees: "Création de syndicats (ex. : *Union des Travailleurs Agricoles*), revendications pour l’égalité des salaires",
  lieu: "Pointe-à-Pitre (centre économique), zones rurales de Grande-Terre",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels pour la justice sociale (ex. : *pwen de solidarité* dans les syndicats)",
  tags: ["**héritage de l’esclavage : lutte continue pour la justice sociale et économique**", "pointe-à-pitre (centre économique)", "zones rurales de grande-terre"],
  },
  {
  id: "18481900-developpementdescommunaute-42",
  periode: "**1848–1900**",
  faitHistorique: "**Développement des communautés libres mais appauvries**",
  porteeSymbolique: "**Résilience : reconstruction malgré l’absence de réparations, solidarité communautaire**",
  actionsMenees: "Entraide communautaire (ex. : *Koudmen*), création de caisses de solidarité",
  lieu: "Zones rurales (Les Abymes, Petit-Bourg), villages de pêcheurs",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour la prospérité collective (ex. : offrandes à *Damballa*)",
  tags: ["**résilience : reconstruction malgré l’absence de réparations", "solidarité communautaire**", "zones rurales (les abymes", "petit-bourg)", "villages de pêcheurs"],
  },
  {
  id: "18481900-transmissiondesrecitsder-43",
  periode: "**1848–1900**",
  faitHistorique: "**Transmission des récits de résistance aux générations suivantes**",
  porteeSymbolique: "**Éducation militante : perpétuation de la mémoire, transmission des valeurs de lutte**",
  actionsMenees: "Récits oraux aux enfants sur les héros (ex. : Delgrès, Solitude), écriture de poèmes en créole",
  lieu: "Foyers familiaux, écoles communautaires (Les Abymes)",
  pratiquesSpirituelles: "Vaudou de la mémoire : rituels pour honorer les héros (ex. : *pwen de courage* sur les tombes)",
  tags: ["**éducation militante : perpétuation de la mémoire", "transmission des valeurs de lutte**", "foyers familiaux", "écoles communautaires (les abymes)"],
  },
  {
  id: "18481900-legwokadevientunsymbole-44",
  periode: "**1848–1900**",
  faitHistorique: "**Le Gwoka devient un symbole de résistance**",
  porteeSymbolique: "**Patrimoine immatériel : reconnaissance de la lutte des ancêtres, outil de résistance culturelle**",
  actionsMenees: "Organisation de *Léwoz* (cérémonies de Gwoka), utilisation de la musique comme outil politique",
  lieu: "Zones rurales (Sainte-Rose, Deshaies)",
  pratiquesSpirituelles: "Vaudou Petwo : fusion du Gwoka et des rituels Petwo (ex. : *tambour Fundeh*)",
  tags: ["**patrimoine immatériel : reconnaissance de la lutte des ancêtres", "outil de résistance culturelle**", "zones rurales (sainte-rose", "deshaies)"],
  },
  {
  id: "18481900-constructiondumemorialact-45",
  periode: "**1848–1900**",
  faitHistorique: "**Construction du Mémorial ACTe (symbolique)**",
  porteeSymbolique: "**Lieu de mémoire : hommage aux résistants et aux victimes, rappel des crimes coloniaux**",
  actionsMenees: "Participation aux cérémonies commémoratives, transmission de l’histoire aux écoles",
  lieu: "Pointe-à-Pitre (Mémorial ACTe, centre-ville)",
  pratiquesSpirituelles: "Vaudou Gede : rituels annuels au Mémorial ACTe (ex. : invocation des *Gede* pour les victimes)",
  tags: ["**lieu de mémoire : hommage aux résistants et aux victimes", "rappel des crimes coloniaux**", "pointe-à-pitre (mémorial acte", "centre-ville)"],
  },
  {
  id: "19001946-developpementdesmouvements-46",
  periode: "**1900–1946**",
  faitHistorique: "**Développement des mouvements ouvriers**",
  porteeSymbolique: "**Lutte pour les droits sociaux : héritage de la résistance, affirmation des travailleurs**",
  actionsMenees: "Grèves massives (ex. : grève des dockers de 1910 à Pointe-à-Pitre), création de syndicats",
  lieu: "Pointe-à-Pitre (port), zones industrielles",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la justice sociale (ex. : *pwen* dans les lieux de grève)",
  tags: ["**lutte pour les droits sociaux : héritage de la résistance", "affirmation des travailleurs**", "pointe-à-pitre (port)", "zones industrielles"],
  },
  {
  id: "19001946-migrationverslametropole-47",
  periode: "**1900–1946**",
  faitHistorique: "**Migration vers la métropole et les Antilles voisines**",
  porteeSymbolique: "**Diaspora guadeloupéenne : recherche de meilleures conditions, mais maintien des liens culturels**",
  actionsMenees: "Création de réseaux associatifs (ex. : *Amicales antillaises* en France), envoi de colis aux familles",
  lieu: "Pointe-à-Pitre (port de départ), Paris (quartiers antillais)",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour protéger les migrants (ex. : *pwen de voyage* dans les valises)",
  tags: ["**diaspora guadeloupéenne : recherche de meilleures conditions", "mais maintien des liens culturels**", "pointe-à-pitre (port de départ)", "paris (quartiers antillais)"],
  },
  {
  id: "19001946-affirmationdugwokacommes-48",
  periode: "**1900–1946**",
  faitHistorique: "**Affirmation du Gwoka comme symbole identitaire**",
  porteeSymbolique: "**Reconnaissance culturelle : le Gwoka devient un marqueur de l’identité guadeloupéenne**",
  actionsMenees: "Organisation de festivals (ex. : *Festival Terre de Blues*), enregistrement des chants traditionnels",
  lieu: "Sainte-Rose, Deshaies, Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Petwo : intégration du Gwoka dans les rituels (ex. : *tambour Fundeh* pour les cérémonies)",
  tags: ["**reconnaissance culturelle : le gwoka devient un marqueur de l’identité guadeloupéenne**", "sainte-rose", "deshaies", "pointe-à-pitre"],
  },
  {
  id: "1946-departementalisationdelag-49",
  periode: "**1946**",
  faitHistorique: "**Départementalisation de la Guadeloupe**",
  porteeSymbolique: "**Intégration à la France : fin du statut colonial, mais persistance des inégalités**",
  actionsMenees: "Participation aux élections locales, revendications pour l’autonomie économique",
  lieu: "Toute l’île",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour bénir la nouvelle ère (ex. : offrandes à *Legba* pour l’avenir)",
  tags: ["**intégration à la france : fin du statut colonial", "mais persistance des inégalités**", "toute l’île"],
  },
  {
  id: "19461967-developpementeconomiqueet-50",
  periode: "**1946–1967**",
  faitHistorique: "**Développement économique et migrations internes**",
  porteeSymbolique: "**Modernisation : urbanisation, mais maintien des traditions rurales**",
  actionsMenees: "Création de coopératives agricoles, développement du tourisme culturel",
  lieu: "Pointe-à-Pitre, Les Abymes, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels pour la prospérité économique (ex. : *pwen* dans les entreprises locales)",
  tags: ["**modernisation : urbanisation", "mais maintien des traditions rurales**", "pointe-à-pitre", "les abymes", "basse-terre"],
  },
  {
  id: "19461967-monteedestensionssociales-51",
  periode: "**1946–1967**",
  faitHistorique: "**Montée des tensions sociales**",
  porteeSymbolique: "**Inégalités persistantes : exploitation économique, racisme, absence de droits**",
  actionsMenees: "Organisation de manifestations pour l’égalité des droits, développement des mouvements syndicaux",
  lieu: "Pointe-à-Pitre, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la justice sociale (ex. : invocation de *Ogoun* pour la force)",
  tags: ["**inégalités persistantes : exploitation économique", "racisme", "absence de droits**", "pointe-à-pitre", "basse-terre"],
  },
  {
  id: "19141918-premiereguerremondiale-52",
  periode: "**1914–1918**",
  faitHistorique: "**Première Guerre mondiale**",
  porteeSymbolique: "**Mobilisation des Guadeloupéens : participation aux combats en Europe, mais aussi maintien des traditions culturelles**",
  actionsMenees: "Envoi de soldats guadeloupéens dans les tranchées, participation aux efforts de guerre, mais aussi résistance culturelle à travers la musique et les rituels",
  lieu: "Pointe-à-Pitre (port de départ), France (champs de bataille)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la protection des soldats (ex. : *pwen* dans les uniformes)",
  tags: ["**mobilisation des guadeloupéens : participation aux combats en europe", "mais aussi maintien des traditions culturelles**", "pointe-à-pitre (port de départ)", "france (champs de bataille)"],
  },
  {
  id: "19141918-resistanceculturellependan-53",
  periode: "**1914–1918**",
  faitHistorique: "**Résistance culturelle pendant la guerre**",
  porteeSymbolique: "**Maintien des traditions : le Gwoka et le vaudou deviennent des symboles de résistance et d’identité**",
  actionsMenees: "Organisation de cérémonies vaudou pour les soldats, transmission des savoirs traditionnels",
  lieu: "Pointe-à-Pitre, zones rurales",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour la paix et la résilience (ex. : offrandes à *Damballa*)",
  tags: ["**maintien des traditions : le gwoka et le vaudou deviennent des symboles de résistance et d’identité**", "pointe-à-pitre", "zones rurales"],
  },
  {
  id: "19181939-periodeentre-deux-guerres-54",
  periode: "**1918–1939**",
  faitHistorique: "**Période entre-deux-guerres**",
  porteeSymbolique: "**Reconstruction et affirmation identitaire : développement des mouvements ouvriers et culturels**",
  actionsMenees: "Création de syndicats, développement du tourisme culturel, affirmation du Gwoka",
  lieu: "Pointe-à-Pitre, Les Abymes, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels pour la prospérité économique (ex. : *pwen* dans les entreprises locales)",
  tags: ["**reconstruction et affirmation identitaire : développement des mouvements ouvriers et culturels**", "pointe-à-pitre", "les abymes", "basse-terre"],
  },
  {
  id: "19391945-secondeguerremondiale-55",
  periode: "**1939–1945**",
  faitHistorique: "**Seconde Guerre mondiale**",
  porteeSymbolique: "**Mobilisation et résistance : participation aux combats, mais aussi résistance contre l’oppression coloniale**",
  actionsMenees: "Envoi de soldats guadeloupéens dans les forces françaises, participation aux mouvements de résistance",
  lieu: "Pointe-à-Pitre (port de départ), France (champs de bataille)",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la protection des soldats (ex. : *bain de force* avec des herbes)",
  tags: ["**mobilisation et résistance : participation aux combats", "mais aussi résistance contre l’oppression coloniale**", "pointe-à-pitre (port de départ)", "france (champs de bataille)"],
  },
  {
  id: "19391945-resistanceculturelleetpol-56",
  periode: "**1939–1945**",
  faitHistorique: "**Résistance culturelle et politique**",
  porteeSymbolique: "**Maintien des traditions : le Gwoka et le vaudou deviennent des symboles de la résistance et de l’identité guadeloupéenne**",
  actionsMenees: "Organisation de cérémonies vaudou pour les soldats, transmission des savoirs traditionnels",
  lieu: "Pointe-à-Pitre, zones rurales",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour la paix et la résilience (ex. : offrandes à *Damballa*)",
  tags: ["**maintien des traditions : le gwoka et le vaudou deviennent des symboles de la résistance et de l’identité guadeloupéenne**", "pointe-à-pitre", "zones rurales"],
  },
  {
  id: "19451967-apres-secondeguerremondial-57",
  periode: "**1945–1967**",
  faitHistorique: "**Après-Seconde Guerre mondiale**",
  porteeSymbolique: "**Reconstruction et montée des tensions sociales : développement économique, mais persistance des inégalités**",
  actionsMenees: "Création de coopératives agricoles, développement du tourisme culturel, revendications pour l’autonomie",
  lieu: "Pointe-à-Pitre, Les Abymes, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la justice sociale (ex. : invocation de *Ogoun* pour la force)",
  tags: ["**reconstruction et montée des tensions sociales : développement économique", "mais persistance des inégalités**", "pointe-à-pitre", "les abymes", "basse-terre"],
  },
  {
  id: "19451967-developpementdesmouvements-58",
  periode: "**1945–1967**",
  faitHistorique: "**Développement des mouvements indépendantistes**",
  porteeSymbolique: "**Lutte pour l’autodétermination : naissance de groupes armés (ex. : *Groupe de Libération Nationale – GLN*)**",
  actionsMenees: "Attentats symboliques contre les symboles du colonialisme (ex. : statues, bâtiments administratifs), propagation de la pensée révolutionnaire",
  lieu: "Pointe-à-Pitre, Basse-Terre, zones rurales",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels de libération (ex. : invocation de *Nzambi* pour la victoire finale)",
  tags: ["**lutte pour l’autodétermination : naissance de groupes armés (ex. : *groupe de libération nationale – gln*)**", "pointe-à-pitre", "basse-terre", "zones rurales"],
  },
  {
  id: "mai1967-revoltepopulairedemai67-59",
  periode: "**Mai 1967**",
  faitHistorique: "**Révolte populaire de Mai 67**",
  porteeSymbolique: "**Lutte pour la dignité et contre l’exploitation coloniale : rébellion contre les *Békés* (élite blanche créole), le racisme, et les inégalités économiques**",
  actionsMenees: "Grèves générales, émeutes, barricades, affrontements avec les forces de l’ordre, occupation des villes",
  lieu: "Pointe-à-Pitre (centre-ville, quartiers populaires comme *Berthé* et *Caraïbes*), Basse-Terre, Les Abymes",
  pratiquesSpirituelles: "**Vaudou Petwo et Rada** :",
  tags: ["**lutte pour la dignité et contre l’exploitation coloniale : rébellion contre les *békés* (élite blanche créole)", "le racisme", "et les inégalités économiques**", "pointe-à-pitre (centre-ville", "quartiers populaires comme *berthé* et *caraïbes*)", "basse-terre", "les abymes"],
  },
  {
  id: "mai1967-repressionsanglante-60",
  periode: "**Mai 1967**",
  faitHistorique: "**Répression sanglante**",
  porteeSymbolique: "**Violence d’État : 7 morts officiels (dont Jacques Nestor), des dizaines de blessés, arrestations arbitraires**",
  actionsMenees: "Résistance jusqu’au bout : barricades, jets de pierres, utilisation de cocktails Molotov contre les forces de l’ordre",
  lieu: "Pointe-à-Pitre (quartiers populaires), routes bloquées entre Pointe-à-Pitre et Les Abymes",
  pratiquesSpirituelles: "**Vaudou Gede** :",
  tags: ["**violence d’état : 7 morts officiels (dont jacques nestor)", "des dizaines de blessés", "arrestations arbitraires**", "pointe-à-pitre (quartiers populaires)", "routes bloquées entre pointe-à-pitre et les abymes"],
  },
  {
  id: "mai1967-solidaritecommunautaire-61",
  periode: "**Mai 1967**",
  faitHistorique: "**Solidarité communautaire**",
  porteeSymbolique: "**Unité du peuple guadeloupéen : alliance entre ouvriers, étudiants, et chômeurs contre le système colonial**",
  actionsMenees: "Organisation de comités de quartier, distribution de nourriture, soins aux blessés dans les églises et les *lakou* (cours intérieures)",
  lieu: "Quartiers populaires de Pointe-à-Pitre, Les Abymes, Baie-Mahault",
  pratiquesSpirituelles: "**Vaudou Rada** :",
  tags: ["**unité du peuple guadeloupéen : alliance entre ouvriers", "étudiants", "et chômeurs contre le système colonial**", "quartiers populaires de pointe-à-pitre", "les abymes", "baie-mahault"],
  },
  {
  id: "19671980-repressionetetatdurgence-62",
  periode: "**1967–1980**",
  faitHistorique: "**Répression et état d’urgence**",
  porteeSymbolique: "**Terreur d’État : censure, arrestations, exils forcés de militants**",
  actionsMenees: "Clandestinité des mouvements révolutionnaires, exils vers la France et les pays africains (ex. : Algérie, Congo)",
  lieu: "Pointe-à-Pitre, Basse-Terre, Paris (pour les exilés)",
  pratiquesSpirituelles: "**Vaudou Petwo** :",
  tags: ["**terreur d’état : censure", "arrestations", "exils forcés de militants**", "pointe-à-pitre", "basse-terre", "paris (pour les exilés)"],
  },
  {
  id: "19671980-radicalisationdesmouvement-63",
  periode: "**1967–1980**",
  faitHistorique: "**Radicalisation des mouvements indépendantistes**",
  porteeSymbolique: "**Lutte pour l’autodétermination : naissance de groupes armés (ex. : *Groupe de Libération Nationale – GLN*)**",
  actionsMenees: "Attentats symboliques contre les symboles du colonialisme (ex. : statues, bâtiments administratifs), propagation de la pensée révolutionnaire",
  lieu: "Pointe-à-Pitre, Basse-Terre, zones rurales",
  pratiquesSpirituelles: "**Vaudou Kongolais** :",
  tags: ["**lutte pour l’autodétermination : naissance de groupes armés (ex. : *groupe de libération nationale – gln*)**", "pointe-à-pitre", "basse-terre", "zones rurales"],
  },
  {
  id: "1980-amnistiedesmilitantsdema-64",
  periode: "**1980**",
  faitHistorique: "**Amnistie des militants de Mai 67**",
  porteeSymbolique: "**Reconnaissance partielle des torts : retour des exilés, mais impunité pour les crimes d’État**",
  actionsMenees: "Retour des militants, création d’associations mémorielles (ex. : *Comité Mai 67*)",
  lieu: "Pointe-à-Pitre, Les Abymes",
  pratiquesSpirituelles: "**Vaudou Gede** :",
  tags: ["**reconnaissance partielle des torts : retour des exilés", "mais impunité pour les crimes d’état**", "pointe-à-pitre", "les abymes"],
  },
  {
  id: "19802000-reconnaissancedugwokacomm-65",
  periode: "**1980–2000**",
  faitHistorique: "**Reconnaissance du Gwoka comme patrimoine culturel**",
  porteeSymbolique: "**Victoire culturelle : le Gwoka est inscrit comme patrimoine immatériel de l’humanité (UNESCO, 2014)**",
  actionsMenees: "Organisation de festivals internationaux (ex. : *Festival Terre de Blues*), transmission aux jeunes générations",
  lieu: "Sainte-Rose, Deshaies, Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour célébrer la reconnaissance (ex. : *Léwoz* pour l’UNESCO)",
  tags: ["**victoire culturelle : le gwoka est inscrit comme patrimoine immatériel de l’humanité (unesco", "2014)**", "sainte-rose", "deshaies", "pointe-à-pitre"],
  },
  {
  id: "19802000-developpementdutourismecu-66",
  periode: "**1980–2000**",
  faitHistorique: "**Développement du tourisme culturel**",
  porteeSymbolique: "**Valorisation du patrimoine : le vaudou et le Gwoka deviennent des attractifs touristiques**",
  actionsMenees: "Création de musées (ex. : *Mémorial ACTe*), visites guidées sur les sites historiques",
  lieu: "Pointe-à-Pitre (Mémorial ACTe), Basse-Terre",
  pratiquesSpirituelles: "Vaudou Gede : rituels pour honorer les ancêtres dans les musées",
  tags: ["**valorisation du patrimoine : le vaudou et le gwoka deviennent des attractifs touristiques**", "pointe-à-pitre (mémorial acte)", "basse-terre"],
  },
  {
  id: "20002026-luttespourlareconnaissanc-67",
  periode: "**2000–2026**",
  faitHistorique: "**Luttes pour la reconnaissance des crimes de l’esclavage**",
  porteeSymbolique: "**Mémoire et réparation : reconnaissance officielle de l’esclavage comme crime contre l’humanité**",
  actionsMenees: "Participation aux cérémonies du *10 mai* (Journée nationale des mémoires de la traite, de l’esclavage et de leurs abolitions)",
  lieu: "Toute l’île, surtout Pointe-à-Pitre et Basse-Terre",
  pratiquesSpirituelles: "Vaudou Gede : rituels annuels pour les victimes (ex. : *cérémonies Gede* le 27 mai)",
  tags: ["**mémoire et réparation : reconnaissance officielle de l’esclavage comme crime contre l’humanité**", "toute l’île", "surtout pointe-à-pitre et basse-terre"],
  },
  {
  id: "20002026-developpementdesmediasloc-68",
  periode: "**2000–2026**",
  faitHistorique: "**Développement des médias locaux et de la culture créole**",
  porteeSymbolique: "**Affirmation identitaire : promotion de la langue et de la culture créoles**",
  actionsMenees: "Création de radios en créole (ex. : *Radio Guadeloupe*), publication de livres en créole",
  lieu: "Pointe-à-Pitre, Les Abymes",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour bénir les médias (ex. : *pwen* dans les studios de radio)",
  tags: ["**affirmation identitaire : promotion de la langue et de la culture créoles**", "pointe-à-pitre", "les abymes"],
  },
  {
  id: "20002026-luttespourlautonomieetl-69",
  periode: "**2000–2026**",
  faitHistorique: "**Luttes pour l’autonomie et la décolonisation**",
  porteeSymbolique: "**Héritage de la résistance : revendications pour une plus grande autonomie politique**",
  actionsMenees: "Manifestations pour l’autonomie, création de mouvements politiques (ex. : *LKP en 2009*)",
  lieu: "Pointe-à-Pitre, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la souveraineté (ex. : invocation de *Ogoun* pour la force politique)",
  tags: ["**héritage de la résistance : revendications pour une plus grande autonomie politique**", "pointe-à-pitre", "basse-terre"],
  },
  {
  id: "2009-grevegeneraledulkpliyan-70",
  periode: "**2009**",
  faitHistorique: "**Grève générale du LKP (Liyannaj Kont Pwofitasyon)**",
  porteeSymbolique: "**Lutte contre l’exploitation économique : mobilisation massive pour la justice sociale**",
  actionsMenees: "Grève générale de 44 jours, blocage de l’économie, revendications pour la hausse des salaires",
  lieu: "Toute l’île, surtout Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Petwo : rituels pour la justice économique (ex. : *pwen* dans les lieux de grève)",
  tags: ["**lutte contre l’exploitation économique : mobilisation massive pour la justice sociale**", "toute l’île", "surtout pointe-à-pitre"],
  },
  {
  id: "20152026-reconnaissanceinternational-71",
  periode: "**2015–2026**",
  faitHistorique: "**Reconnaissance internationale du Gwoka**",
  porteeSymbolique: "**Patrimoine mondial : le Gwoka est reconnu comme symbole de la résistance culturelle**",
  actionsMenees: "Participation à des festivals internationaux, transmission aux jeunes générations",
  lieu: "Sainte-Rose, Deshaies, Pointe-à-Pitre",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour célébrer la reconnaissance (ex. : *Léwoz* pour l’UNESCO)",
  tags: ["**patrimoine mondial : le gwoka est reconnu comme symbole de la résistance culturelle**", "sainte-rose", "deshaies", "pointe-à-pitre"],
  },
  {
  id: "2017-ouraganmaria-72",
  periode: "**2017**",
  faitHistorique: "**Ouragan Maria**",
  porteeSymbolique: "**Résilience face aux catastrophes naturelles : solidarité communautaire et reconstruction**",
  actionsMenees: "Organisation de collectes de fonds, reconstruction des villages détruits",
  lieu: "Toute l’île, surtout Basse-Terre et Grande-Terre",
  pratiquesSpirituelles: "Vaudou Rada : rituels pour la protection contre les ouragans (ex. : invocation de *Damballa* pour la paix)",
  tags: ["**résilience face aux catastrophes naturelles : solidarité communautaire et reconstruction**", "toute l’île", "surtout basse-terre et grande-terre"],
  },
  {
  id: "20202026-luttespourlajusticeenvir-73",
  periode: "**2020–2026**",
  faitHistorique: "**Luttes pour la justice environnementale**",
  porteeSymbolique: "**Protection de la terre : résistance contre l’exploitation des ressources naturelles**",
  actionsMenees: "Manifestations contre les projets polluants (ex. : lutte contre la déforestation), promotion de l’agriculture biologique",
  lieu: "Basse-Terre (parc national), Grande-Terre",
  pratiquesSpirituelles: "Vaudou Kongolais : rituels pour la protection de la nature (ex. : *pwen* dans les forêts)",
  tags: ["**protection de la terre : résistance contre l’exploitation des ressources naturelles**", "basse-terre (parc national)", "grande-terre"],
  },
  {
  id: "20202026-developpementdutourismesp-74",
  periode: "**2020–2026**",
  faitHistorique: "**Développement du tourisme spirituel**",
  porteeSymbolique: "**Valorisation du vaudou : attrait pour les visiteurs en quête de spiritualité**",
  actionsMenees: "Organisation de cérémonies vaudou pour les touristes, transmission des savoirs traditionnels",
  lieu: "Pointe-à-Pitre, Basse-Terre, Les Saintes",
  pratiquesSpirituelles: "Vaudou Rada et Petwo : rituels adaptés pour les visiteurs (ex. : *Léwoz* touristiques)",
  tags: ["**valorisation du vaudou : attrait pour les visiteurs en quête de spiritualité**", "pointe-à-pitre", "basse-terre", "les saintes"],
  },
  {
  id: "20202026-mouvementspourlareparatio-75",
  periode: "**2020–2026**",
  faitHistorique: "**Mouvements pour la réparation de l’esclavage**",
  porteeSymbolique: "**Justice historique : revendications pour des réparations financières et symboliques**",
  actionsMenees: "Participation aux conférences internationales, création de collectifs (ex. : *Collectif pour la Mémoire et la Réparation*)",
  lieu: "Pointe-à-Pitre, Basse-Terre",
  pratiquesSpirituelles: "Vaudou Gede : rituels pour la justice historique (ex. : invocation des *Gede* pour les victimes)",
  tags: ["**justice historique : revendications pour des réparations financières et symboliques**", "pointe-à-pitre", "basse-terre"],
  }
];

// Index pour recherche rapide
export const histoireIndex: Record<string, HistoireEntry> = {
  "avant300avj-c-peuplementinitialdelaguade-0": histoireData.find(p => p.id === "avant300avj-c-peuplementinitialdelaguade-0")!,
  "300avj-c300apj-c-arriveedestainosarawaks-1": histoireData.find(p => p.id === "300avj-c300apj-c-arriveedestainosarawaks-1")!,
  "6001500apj-c-traitetranssaharienneetro-2": histoireData.find(p => p.id === "6001500apj-c-traitetranssaharienneetro-2")!,
  "1635-prisedepossessionfrancais-3": histoireData.find(p => p.id === "1635-prisedepossessionfrancais-3")!,
  "1635-debutdelatraitenegriere-4": histoireData.find(p => p.id === "1635-debutdelatraitenegriere-4")!,
  "16351650-introductiondespremierses-5": histoireData.find(p => p.id === "16351650-introductiondespremierses-5")!,
  "16351650-developpementdesplantation-6": histoireData.find(p => p.id === "16351650-developpementdesplantation-6")!,
  "16501685-transitionverslesplantati-7": histoireData.find(p => p.id === "16501685-transitionverslesplantati-7")!,
  "1685-publicationducodenoir-8": histoireData.find(p => p.id === "1685-publicationducodenoir-8")!,
  "1685-lecodenoirinterditlesma-9": histoireData.find(p => p.id === "1685-lecodenoirinterditlesma-9")!,
  "1685-lecodenoirautoriselesch-10": histoireData.find(p => p.id === "1685-lecodenoirautoriselesch-10")!,
  "16851759-laguadeloupedevientuneco-11": histoireData.find(p => p.id === "16851759-laguadeloupedevientuneco-11")!,
  "16851759-expansiondesplantationsde-12": histoireData.find(p => p.id === "16851759-expansiondesplantationsde-12")!,
  "17591763-occupationbritanniquedela-13": histoireData.find(p => p.id === "17591763-occupationbritanniquedela-13")!,
  "17591763-resistancedesesclavessous-14": histoireData.find(p => p.id === "17591763-resistancedesesclavessous-14")!,
  "1763-restitutiondelaguadeloupe-15": histoireData.find(p => p.id === "1763-restitutiondelaguadeloupe-15")!,
  "17631789-renforcementdusystemeplan-16": histoireData.find(p => p.id === "17631789-renforcementdusystemeplan-16")!,
  "1789-influencedesideesrevoluti-17": histoireData.find(p => p.id === "1789-influencedesideesrevoluti-17")!,
  "17891794-revoltesdesclavesinspiree-18": histoireData.find(p => p.id === "17891794-revoltesdesclavesinspiree-18")!,
  "1794-premiereabolitiondelescl-19": histoireData.find(p => p.id === "1794-premiereabolitiondelescl-19")!,
  "1794-liberationtemporairedeses-20": histoireData.find(p => p.id === "1794-liberationtemporairedeses-20")!,
  "1794-participationdesancienses-21": histoireData.find(p => p.id === "1794-participationdesancienses-21")!,
  "17941802-developpementdelaculture-22": histoireData.find(p => p.id === "17941802-developpementdelaculture-22")!,
  "17941802-educationetalphabetisation-23": histoireData.find(p => p.id === "17941802-educationetalphabetisation-23")!,
  "1802-retablissementdelesclavag-24": histoireData.find(p => p.id === "1802-retablissementdelesclavag-24")!,
  "1802-repressionbrutaledesrevol-25": histoireData.find(p => p.id === "1802-repressionbrutaledesrevol-25")!,
  "1802-resistancedelouisdelgres-26": histoireData.find(p => p.id === "1802-resistancedelouisdelgres-26")!,
  "1802-lamulatressesolitudehero-27": histoireData.find(p => p.id === "1802-lamulatressesolitudehero-27")!,
  "18021815-resistancepassivemarronn-28": histoireData.find(p => p.id === "18021815-resistancepassivemarronn-28")!,
  "18021815-transmissionoraledeshisto-29": histoireData.find(p => p.id === "18021815-transmissionoraledeshisto-29")!,
  "18021815-developpementdugwokacomme-30": histoireData.find(p => p.id === "18021815-developpementdugwokacomme-30")!,
  "18151848-persistancedesrevoltesloc-31": histoireData.find(p => p.id === "18151848-persistancedesrevoltesloc-31")!,
  "18151848-influencedesmouvementsabo-32": histoireData.find(p => p.id === "18151848-influencedesmouvementsabo-32")!,
  "18151848-resistanceculturellecont-33": histoireData.find(p => p.id === "18151848-resistanceculturellecont-33")!,
  "18151848-conditionsdevieprecaires-34": histoireData.find(p => p.id === "18151848-conditionsdevieprecaires-34")!,
  "1848-revoltesdesclavesenmai1-35": histoireData.find(p => p.id === "1848-revoltesdesclavesenmai1-35")!,
  "27avril1848-deuxiemeabolitiondelescl-36": histoireData.find(p => p.id === "27avril1848-deuxiemeabolitiondelescl-36")!,
  "27avril1848-liberationdes87000esclav-37": histoireData.find(p => p.id === "27avril1848-liberationdes87000esclav-37")!,
  "27avril1848-transitiondifficileversle-38": histoireData.find(p => p.id === "27avril1848-transitiondifficileversle-38")!,
  "27avril1848-affirmationdelaculturecr-39": histoireData.find(p => p.id === "27avril1848-affirmationdelaculturecr-39")!,
  "27avril1848-celebrationdu27maicomme-40": histoireData.find(p => p.id === "27avril1848-celebrationdu27maicomme-40")!,
  "18481900-persistancedesinegalitese-41": histoireData.find(p => p.id === "18481900-persistancedesinegalitese-41")!,
  "18481900-developpementdescommunaute-42": histoireData.find(p => p.id === "18481900-developpementdescommunaute-42")!,
  "18481900-transmissiondesrecitsder-43": histoireData.find(p => p.id === "18481900-transmissiondesrecitsder-43")!,
  "18481900-legwokadevientunsymbole-44": histoireData.find(p => p.id === "18481900-legwokadevientunsymbole-44")!,
  "18481900-constructiondumemorialact-45": histoireData.find(p => p.id === "18481900-constructiondumemorialact-45")!,
  "19001946-developpementdesmouvements-46": histoireData.find(p => p.id === "19001946-developpementdesmouvements-46")!,
  "19001946-migrationverslametropole-47": histoireData.find(p => p.id === "19001946-migrationverslametropole-47")!,
  "19001946-affirmationdugwokacommes-48": histoireData.find(p => p.id === "19001946-affirmationdugwokacommes-48")!,
  "1946-departementalisationdelag-49": histoireData.find(p => p.id === "1946-departementalisationdelag-49")!,
  "19461967-developpementeconomiqueet-50": histoireData.find(p => p.id === "19461967-developpementeconomiqueet-50")!,
  "19461967-monteedestensionssociales-51": histoireData.find(p => p.id === "19461967-monteedestensionssociales-51")!,
  "19141918-premiereguerremondiale-52": histoireData.find(p => p.id === "19141918-premiereguerremondiale-52")!,
  "19141918-resistanceculturellependan-53": histoireData.find(p => p.id === "19141918-resistanceculturellependan-53")!,
  "19181939-periodeentre-deux-guerres-54": histoireData.find(p => p.id === "19181939-periodeentre-deux-guerres-54")!,
  "19391945-secondeguerremondiale-55": histoireData.find(p => p.id === "19391945-secondeguerremondiale-55")!,
  "19391945-resistanceculturelleetpol-56": histoireData.find(p => p.id === "19391945-resistanceculturelleetpol-56")!,
  "19451967-apres-secondeguerremondial-57": histoireData.find(p => p.id === "19451967-apres-secondeguerremondial-57")!,
  "19451967-developpementdesmouvements-58": histoireData.find(p => p.id === "19451967-developpementdesmouvements-58")!,
  "mai1967-revoltepopulairedemai67-59": histoireData.find(p => p.id === "mai1967-revoltepopulairedemai67-59")!,
  "mai1967-repressionsanglante-60": histoireData.find(p => p.id === "mai1967-repressionsanglante-60")!,
  "mai1967-solidaritecommunautaire-61": histoireData.find(p => p.id === "mai1967-solidaritecommunautaire-61")!,
  "19671980-repressionetetatdurgence-62": histoireData.find(p => p.id === "19671980-repressionetetatdurgence-62")!,
  "19671980-radicalisationdesmouvement-63": histoireData.find(p => p.id === "19671980-radicalisationdesmouvement-63")!,
  "1980-amnistiedesmilitantsdema-64": histoireData.find(p => p.id === "1980-amnistiedesmilitantsdema-64")!,
  "19802000-reconnaissancedugwokacomm-65": histoireData.find(p => p.id === "19802000-reconnaissancedugwokacomm-65")!,
  "19802000-developpementdutourismecu-66": histoireData.find(p => p.id === "19802000-developpementdutourismecu-66")!,
  "20002026-luttespourlareconnaissanc-67": histoireData.find(p => p.id === "20002026-luttespourlareconnaissanc-67")!,
  "20002026-developpementdesmediasloc-68": histoireData.find(p => p.id === "20002026-developpementdesmediasloc-68")!,
  "20002026-luttespourlautonomieetl-69": histoireData.find(p => p.id === "20002026-luttespourlautonomieetl-69")!,
  "2009-grevegeneraledulkpliyan-70": histoireData.find(p => p.id === "2009-grevegeneraledulkpliyan-70")!,
  "20152026-reconnaissanceinternational-71": histoireData.find(p => p.id === "20152026-reconnaissanceinternational-71")!,
  "2017-ouraganmaria-72": histoireData.find(p => p.id === "2017-ouraganmaria-72")!,
  "20202026-luttespourlajusticeenvir-73": histoireData.find(p => p.id === "20202026-luttespourlajusticeenvir-73")!,
  "20202026-developpementdutourismesp-74": histoireData.find(p => p.id === "20202026-developpementdutourismesp-74")!,
  "20202026-mouvementspourlareparatio-75": histoireData.find(p => p.id === "20202026-mouvementspourlareparatio-75")!
};

// Fonction utilitaire - chercher par période
export function getHistoireByPeriode(periode: string): HistoireEntry | undefined {
  return histoireData.find(p => 
    p.periode.toLowerCase().includes(periode.toLowerCase())
  );
}

// Fonction utilitaire - chercher par mots-clés
export function getHistoireByMotCle(mot: string): HistoireEntry | undefined {
  const motLower = mot.toLowerCase();
  return histoireData.find(p => 
    p.faitHistorique.toLowerCase().includes(motLower) ||
    p.porteeSymbolique.toLowerCase().includes(motLower) ||
    p.lieu.toLowerCase().includes(motLower)
  );
}

// Fonction utilitaire - obtenir toutes les entrées d'une période
 export function getHistoireByPeriodeAll(periode: string): HistoireEntry[] {
  const periodeLower = periode.toLowerCase();
  return histoireData.filter(p => 
    p.periode.toLowerCase().includes(periodeLower)
  );
}
