export interface KreyolEntry {
  id: string;
  famille: string;
  nomCreole: string;
  nomFrancais: string;
  nomScientifique: string;
  typeResistance?: string;
  resistanceDescription?: string;
  dimensionCulturelle: string;
  tags: string[];
}


// Données générées automatiquement depuis kreyol_resistance_symbol_ref.md
// NE PAS MODIFIER MANUELLEMENT - Exécuter 'npm run kreyol:parse' pour mettre à jour
export const kreyolData: KreyolEntry[] = [
  {
  id: "igwann-pyi-igu",
  famille: "animaux-symboles de résistance",
  nomCreole: "Igwann péyi",
  nomFrancais: "Iguane des Petites Antilles",
  nomScientifique: "Iguana delicatissima",
  typeResistance: "TOTEM DE RÉSISTANCE Animal totem des Arawaks. Symbole de sagesse et de persévérance. Les esclaves marrons s'identifiaient à lui : immobile et invisible dans la forêt, il sait attendre, observer et survivre. Sa couleur qui se fond dans le décor est une métaphore du marronage.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Animal totem des Arawaks. Symbole de sagesse et de persévérance. Les esclaves marrons s'identifiaient à lui : immobile et invisible dans la forêt, il sait attendre, observer et survivre. Sa couleur qui se fond dans le décor est une métaphore du marronage.",
  tags: ["animaux — symboles de résistance", "resistance", "totem-de-résistance-animal-totem-des-arawaks.-symbole-de-sagesse-et-de-persévérance.-les-esclaves-marrons-s'identifiaient-à-lui-:-immobile-et-invisible-dans-la-forêt,-il-sait-attendre,-observer-et-survivre.-sa-couleur-qui-se-fond-dans-le-décor-est-une-métaphore-du-marronage."],
  },
  {
  id: "zandoli-anoli-ano",
  famille: "animaux-symboles de résistance",
  nomCreole: "Zandoli / Anoli",
  nomFrancais: "Anoli marbré",
  nomScientifique: "Anolis marmoratus",
  typeResistance: "TOTEM DE RÉSISTANCE Symbole de résilience et de liberté dans la culture créole. Présent sur chaque île avec une sous-espèce différente — il s'est adapté à chaque territoire comme les Guadeloupéens ont su s'adapter à chaque épreuve. Impossible à capturer durablement : il lâche sa queue et repart.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Symbole de résilience et de liberté dans la culture créole. Présent sur chaque île avec une sous-espèce différente — il s'est adapté à chaque territoire comme les Guadeloupéens ont su s'adapter à chaque épreuve. Impossible à capturer durablement : il lâche sa queue et repart.",
  tags: ["animaux — symboles de résistance", "resistance", "totem-de-résistance-symbole-de-résilience-et-de-liberté-dans-la-culture-créole.-présent-sur-chaque-île-avec-une-sous-espèce-différente-—-il-s'est-adapté-à-chaque-territoire-comme-les-guadeloupéens-ont-su-s'adapter-à-chaque-épreuve.-impossible-à-capturer-durablement-:-il-lâche-sa-queue-et-repart."],
  },
  {
  id: "urakan-frgate-fre",
  famille: "animaux-symboles de résistance",
  nomCreole: "Urakan / Frégate",
  nomFrancais: "Frégate superbe",
  nomScientifique: "Fregata magnificens",
  typeResistance: "LIBERTÉ Oiseau qui ne se pose presque jamais, vole pendant des jours sans toucher terre. Symbole du marronnage aérien, de la liberté absolue et de l'insoumission. Associé aux esprits qui ne peuvent être enchaînés.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Oiseau qui ne se pose presque jamais, vole pendant des jours sans toucher terre. Symbole du marronnage aérien, de la liberté absolue et de l'insoumission. Associé aux esprits qui ne peuvent être enchaînés.",
  tags: ["animaux — symboles de résistance", "resistance", "liberté-oiseau-qui-ne-se-pose-presque-jamais,-vole-pendant-des-jours-sans-toucher-terre.-symbole-du-marronnage-aérien,-de-la-liberté-absolue-et-de-l'insoumission.-associé-aux-esprits-qui-ne-peuvent-être-enchaînés."],
  },
  {
  id: "gouti-das",
  famille: "animaux-symboles de résistance",
  nomCreole: "Gouti",
  nomFrancais: "Agouti doré",
  nomScientifique: "Dasyprocta leporina",
  typeResistance: "RÉSISTANCE Introduit par les Arawaks eux-mêmes bien avant la colonisation. Survit dans la forêt malgré des siècles de chasse. Symbole de la continuité amérindienne et de la capacité à se nourrir en dehors du système colonial.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Introduit par les Arawaks eux-mêmes bien avant la colonisation. Survit dans la forêt malgré des siècles de chasse. Symbole de la continuité amérindienne et de la capacité à se nourrir en dehors du système colonial.",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-introduit-par-les-arawaks-eux-mêmes-bien-avant-la-colonisation.-survit-dans-la-forêt-malgré-des-siècles-de-chasse.-symbole-de-la-continuité-amérindienne-et-de-la-capacité-à-se-nourrir-en-dehors-du-système-colonial."],
  },
  {
  id: "foumi-manyok-acr",
  famille: "animaux-symboles de résistance",
  nomCreole: "Foumi manyok",
  nomFrancais: "Fourmi manioc",
  nomScientifique: "Acromyrmex octospinosus",
  typeResistance: "RÉSISTANCE COLLECTIVE Colonie organisée, invisible, travaillant dans l'ombre et construisant sans relâche. Symbole de la résistance collective et silencieuse des esclaves. Les anciens disaient : « Foumi ka travay, foumi ka manyé » — la fourmi travaille, la fourmi mange.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Colonie organisée, invisible, travaillant dans l'ombre et construisant sans relâche. Symbole de la résistance collective et silencieuse des esclaves. Les anciens disaient : « Foumi ka travay, foumi ka manyé » — la fourmi travaille, la fourmi mange.",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-collective-colonie-organisée,-invisible,-travaillant-dans-l'ombre-et-construisant-sans-relâche.-symbole-de-la-résistance-collective-et-silencieuse-des-esclaves.-les-anciens-disaient-:-«-foumi-ka-travay,-foumi-ka-manyé-»-—-la-fourmi-travaille,-la-fourmi-mange."],
  },
  {
  id: "raz-rat",
  famille: "animaux-symboles de résistance",
  nomCreole: "Razè",
  nomFrancais: "Rat des champs",
  nomScientifique: "*Rattus rattus*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Animal abondant dans les champs de canne, capturé et consommé en cachette. Symbole de la débrouillardise et de la survie malgré les privations (rapport de plantation, 1785).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Animal abondant dans les champs de canne, capturé et consommé en cachette. Symbole de la débrouillardise et de la survie malgré les privations (rapport de plantation, 1785).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-alimentaire-animal-abondant-dans-les-champs-de-canne,-capturé-et-consommé-en-cachette.-symbole-de-la-débrouillardise-et-de-la-survie-malgré-les-privations-(rapport-de-plantation,-1785)."],
  },
  {
  id: "manikou-did",
  famille: "animaux-symboles de résistance",
  nomCreole: "Manikou",
  nomFrancais: "Opossum",
  nomScientifique: "*Didelphis marsupialis*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Chassé par les marrons pour sa viande et sa peau, utilisée pour fabriquer des sacs. Symbole de l'adaptation à la vie en forêt (Bangou 1992).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Chassé par les marrons pour sa viande et sa peau, utilisée pour fabriquer des sacs. Symbole de l'adaptation à la vie en forêt (Bangou 1992).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-alimentaire-chassé-par-les-marrons-pour-sa-viande-et-sa-peau,-utilisée-pour-fabriquer-des-sacs.-symbole-de-l'adaptation-à-la-vie-en-forêt-(bangou-1992)."],
  },
  {
  id: "serpant-boa",
  famille: "animaux-symboles de résistance",
  nomCreole: "Serpant",
  nomFrancais: "Couleuvre",
  nomScientifique: "*Boa constrictor*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Vénéré dans le vaudou comme esprit protecteur. Les esclaves croyaient qu'elle éloignait les maîtres (Boucher 2008).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Vénéré dans le vaudou comme esprit protecteur. Les esclaves croyaient qu'elle éloignait les maîtres (Boucher 2008).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-spirituelle-vénéré-dans-le-vaudou-comme-esprit-protecteur.-les-esclaves-croyaient-qu'elle-éloignait-les-maîtres-(boucher-2008)."],
  },
  {
  id: "kolibri-tro",
  famille: "animaux-symboles de résistance",
  nomCreole: "Kolibri",
  nomFrancais: "Colibri",
  nomScientifique: "*Trochilidae*",
  typeResistance: "RÉSISTANCE CULTURELLE Oiseau sacré des Arawaks, symbole de liberté et de résilience. Les esclaves l'associaient à l'espoir de libération (Simpson 1970).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Oiseau sacré des Arawaks, symbole de liberté et de résilience. Les esclaves l'associaient à l'espoir de libération (Simpson 1970).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-culturelle-oiseau-sacré-des-arawaks,-symbole-de-liberté-et-de-résilience.-les-esclaves-l'associaient-à-l'espoir-de-libération-(simpson-1970)."],
  },
  {
  id: "pijon-col",
  famille: "animaux-symboles de résistance",
  nomCreole: "Pijon",
  nomFrancais: "Pigeon voyageur",
  nomScientifique: "*Columba livia*",
  typeResistance: "RÉSISTANCE COLLECTIVE Utilisé pour transmettre des messages entre plantations. Symbole de la résistance par l'organisation (archives ADG).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Utilisé pour transmettre des messages entre plantations. Symbole de la résistance par l'organisation (archives ADG).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-collective-utilisé-pour-transmettre-des-messages-entre-plantations.-symbole-de-la-résistance-par-l'organisation-(archives-adg)."],
  },
  {
  id: "kabrit-cap",
  famille: "animaux-symboles de résistance",
  nomCreole: "Kabrit",
  nomFrancais: "Chèvre",
  nomScientifique: "*Capra aegagrus hircus*",
  typeResistance: "RÉSISTANCE ÉCONOMIQUE Élevée en secret pour sa viande et son lait. Symbole de l'autonomie alimentaire (Wiltgen 1994).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Élevée en secret pour sa viande et son lait. Symbole de l'autonomie alimentaire (Wiltgen 1994).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-économique-élevée-en-secret-pour-sa-viande-et-son-lait.-symbole-de-l'autonomie-alimentaire-(wiltgen-1994)."],
  },
  {
  id: "chien-marron-can",
  famille: "animaux-symboles de résistance",
  nomCreole: "Chien marron",
  nomFrancais: "Chien sauvage",
  nomScientifique: "*Canis lupus familiaris*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Devenu sauvage, il était craint et respecté par les marrons, qui y voyaient un protecteur des forêts (Bangou 1992).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Devenu sauvage, il était craint et respecté par les marrons, qui y voyaient un protecteur des forêts (Bangou 1992).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-spirituelle-devenu-sauvage,-il-était-craint-et-respecté-par-les-marrons,-qui-y-voyaient-un-protecteur-des-forêts-(bangou-1992)."],
  },
  {
  id: "coq-gal",
  famille: "animaux-symboles de résistance",
  nomCreole: "Coq",
  nomFrancais: "Coq",
  nomScientifique: "*Gallus gallus domesticus*",
  typeResistance: "RÉSISTANCE CULTURELLE Élevé pour ses chants, associés aux rituels de protection. Symbole de la résistance par la préservation des traditions (Giberti 1989).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Élevé pour ses chants, associés aux rituels de protection. Symbole de la résistance par la préservation des traditions (Giberti 1989).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-culturelle-élevé-pour-ses-chants,-associés-aux-rituels-de-protection.-symbole-de-la-résistance-par-la-préservation-des-traditions-(giberti-1989)."],
  },
  {
  id: "chauve-souris-mol",
  famille: "animaux-symboles de résistance",
  nomCreole: "Chauve-souris",
  nomFrancais: "Chauve-souris",
  nomScientifique: "*Molossus molossus*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Associée aux esprits ancestraux dans le vaudou. Symbole de la connexion avec les ancêtres (Boucher 2008).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Associée aux esprits ancestraux dans le vaudou. Symbole de la connexion avec les ancêtres (Boucher 2008).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-spirituelle-associée-aux-esprits-ancestraux-dans-le-vaudou.-symbole-de-la-connexion-avec-les-ancêtres-(boucher-2008)."],
  },
  {
  id: "crab-car",
  famille: "animaux-symboles de résistance",
  nomCreole: "Crab",
  nomFrancais: "Crabe de terre",
  nomScientifique: "*Cardisoma guanhumi*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Capturé dans les mangroves, il complétait l'alimentation des esclaves. Symbole de la résistance par l'ingéniosité (archives DASSA).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Capturé dans les mangroves, il complétait l'alimentation des esclaves. Symbole de la résistance par l'ingéniosité (archives DASSA).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-alimentaire-capturé-dans-les-mangroves,-il-complétait-l'alimentation-des-esclaves.-symbole-de-la-résistance-par-l'ingéniosité-(archives-dassa)."],
  },
  {
  id: "loro-ama",
  famille: "animaux-symboles de résistance",
  nomCreole: "Loro",
  nomFrancais: "Perroquet",
  nomScientifique: "*Amazona* spp.",
  typeResistance: "RÉSISTANCE CULTURELLE Son plumage coloré était utilisé dans les parures rituelles. Symbole de la résistance par la beauté et la tradition (Simpson 1970).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Son plumage coloré était utilisé dans les parures rituelles. Symbole de la résistance par la beauté et la tradition (Simpson 1970).",
  tags: ["animaux — symboles de résistance", "resistance", "résistance-culturelle-son-plumage-coloré-était-utilisé-dans-les-parures-rituelles.-symbole-de-la-résistance-par-la-beauté-et-la-tradition-(simpson-1970)."],
  },
  {
  id: "manyk-man",
  famille: "plantes-symboles de résistance",
  nomCreole: "Manyòk",
  nomFrancais: "Manioc",
  nomScientifique: "Manihot esculenta",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Racine sacrée des Arawaks devenue arme de survie des esclaves. Cultivée en secret dans les jardins de case, elle permettait une autonomie alimentaire totale hors du contrôle des maîtres. Transformée en cassave, elle nourrissait les marrons en fuite dans les mornes.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Racine sacrée des Arawaks devenue arme de survie des esclaves. Cultivée en secret dans les jardins de case, elle permettait une autonomie alimentaire totale hors du contrôle des maîtres. Transformée en cassave, elle nourrissait les marrons en fuite dans les mornes.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-alimentaire-racine-sacrée-des-arawaks-devenue-arme-de-survie-des-esclaves.-cultivée-en-secret-dans-les-jardins-de-case,-elle-permettait-une-autonomie-alimentaire-totale-hors-du-contrôle-des-maîtres.-transformée-en-cassave,-elle-nourrissait-les-marrons-en-fuite-dans-les-mornes."],
  },
  {
  id: "vaniy-van",
  famille: "plantes-symboles de résistance",
  nomCreole: "Vaniy",
  nomFrancais: "Vanilier",
  nomScientifique: "Vanilla planifolia",
  typeResistance: "RÉSISTANCE ÉCONOMIQUE Cultivé par les esclaves et les affranchis à Pointe-Noire. La maîtrise de la pollinisation manuelle de la vanille — technique développée en 1841 par Edmond Albius, esclave réunionnais — est un acte de résistance intellectuelle et économique majeur. La vanille cultivée représentait une source de revenus autonomes hors du système de la plantation.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Cultivé par les esclaves et les affranchis à Pointe-Noire. La maîtrise de la pollinisation manuelle de la vanille — technique développée en 1841 par Edmond Albius, esclave réunionnais — est un acte de résistance intellectuelle et économique majeur. La vanille cultivée représentait une source de revenus autonomes hors du système de la plantation.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-économique-cultivé-par-les-esclaves-et-les-affranchis-à-pointe-noire.-la-maîtrise-de-la-pollinisation-manuelle-de-la-vanille-—-technique-développée-en-1841-par-edmond-albius,-esclave-réunionnais-—-est-un-acte-de-résistance-intellectuelle-et-économique-majeur.-la-vanille-cultivée-représentait-une-source-de-revenus-autonomes-hors-du-système-de-la-plantation."],
  },
  {
  id: "iyam-dio",
  famille: "plantes-symboles de résistance",
  nomCreole: "Iyam",
  nomFrancais: "Igname",
  nomScientifique: "Dioscorea alata",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Tubercule africain apporté dans les cales des bateaux négriers — volontairement ou non. Sa culture dans les jardins de case représentait un lien direct avec l'Afrique et une autonomie nutritive essentielle. L'igname est un acte de mémoire autant que de nourriture.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Tubercule africain apporté dans les cales des bateaux négriers — volontairement ou non. Sa culture dans les jardins de case représentait un lien direct avec l'Afrique et une autonomie nutritive essentielle. L'igname est un acte de mémoire autant que de nourriture.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-alimentaire-tubercule-africain-apporté-dans-les-cales-des-bateaux-négriers-—-volontairement-ou-non.-sa-culture-dans-les-jardins-de-case-représentait-un-lien-direct-avec-l'afrique-et-une-autonomie-nutritive-essentielle.-l'igname-est-un-acte-de-mémoire-autant-que-de-nourriture."],
  },
  {
  id: "woucou-roucou-bix",
  famille: "plantes-symboles de résistance",
  nomCreole: "Woucou / Roucou",
  nomFrancais: "Roucou / Annatto",
  nomScientifique: "Bixa orellana",
  typeResistance: "RÉSISTANCE IDENTITAIRE Plante des Arawaks utilisée pour se peindre le corps lors des cérémonies et des combats. Les esclaves l'ont réappropriée comme colorant alimentaire (peau du poulet boucané) et comme marqueur identitaire discret, invisible aux yeux des maîtres.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Plante des Arawaks utilisée pour se peindre le corps lors des cérémonies et des combats. Les esclaves l'ont réappropriée comme colorant alimentaire (peau du poulet boucané) et comme marqueur identitaire discret, invisible aux yeux des maîtres.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-identitaire-plante-des-arawaks-utilisée-pour-se-peindre-le-corps-lors-des-cérémonies-et-des-combats.-les-esclaves-l'ont-réappropriée-comme-colorant-alimentaire-(peau-du-poulet-boucané)-et-comme-marqueur-identitaire-discret,-invisible-aux-yeux-des-maîtres."],
  },
  {
  id: "malom-malnomme-pet",
  famille: "plantes-symboles de résistance",
  nomCreole: "Malomé / Malnommée",
  nomFrancais: "Malnommée",
  nomScientifique: "Petiveria alliacea",
  typeResistance: "RÉSISTANCE SPIRITUELLE Plante de protection spirituelle du quimbois. Plantée aux angles de la case par les esclaves pour se protéger de l'emprise des maîtres. Son odeur forte d'ail était un bouclier invisible. Garder cette plante était un acte de résistance culturelle à la christianisation forcée.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Plante de protection spirituelle du quimbois. Plantée aux angles de la case par les esclaves pour se protéger de l'emprise des maîtres. Son odeur forte d'ail était un bouclier invisible. Garder cette plante était un acte de résistance culturelle à la christianisation forcée.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-plante-de-protection-spirituelle-du-quimbois.-plantée-aux-angles-de-la-case-par-les-esclaves-pour-se-protéger-de-l'emprise-des-maîtres.-son-odeur-forte-d'ail-était-un-bouclier-invisible.-garder-cette-plante-était-un-acte-de-résistance-culturelle-à-la-christianisation-forcée."],
  },
  {
  id: "kanai-canne-sucre-sac",
  famille: "plantes-symboles de résistance",
  nomCreole: "Kanaié / Canne à sucre",
  nomFrancais: "Canne à sucre",
  nomScientifique: "Saccharum officinarum",
  typeResistance: "RÉSISTANCE PARADOXALE La canne est à la fois l'instrument de l'oppression et le lieu de la résistance. C'est dans les champs de canne que les esclaves ont forgé leur langue créole, leurs chants de travail (le Gwo Ka), leur solidarité et leurs réseaux de communication clandestins.",
  resistanceDescription: undefined,
  dimensionCulturelle: "La canne est à la fois l'instrument de l'oppression et le lieu de la résistance. C'est dans les champs de canne que les esclaves ont forgé leur langue créole, leurs chants de travail (le Gwo Ka), leur solidarité et leurs réseaux de communication clandestins.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-paradoxale-la-canne-est-à-la-fois-l'instrument-de-l'oppression-et-le-lieu-de-la-résistance.-c'est-dans-les-champs-de-canne-que-les-esclaves-ont-forgé-leur-langue-créole,-leurs-chants-de-travail-(le-gwo-ka),-leur-solidarité-et-leurs-réseaux-de-communication-clandestins."],
  },
  {
  id: "tabak-nic",
  famille: "plantes-symboles de résistance",
  nomCreole: "Tabak",
  nomFrancais: "Tabac",
  nomScientifique: "Nicotiana tabacum",
  typeResistance: "RÉSISTANCE CULTURELLE Plante sacrée des Arawaks pour les rituels de communication avec les esprits (fumée = message aux ancêtres). Réappropriée par les esclaves comme moment de pause volé au labeur, espace de sociabilité hors du regard des maîtres.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Plante sacrée des Arawaks pour les rituels de communication avec les esprits (fumée = message aux ancêtres). Réappropriée par les esclaves comme moment de pause volé au labeur, espace de sociabilité hors du regard des maîtres.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-culturelle-plante-sacrée-des-arawaks-pour-les-rituels-de-communication-avec-les-esprits-(fumée-=-message-aux-ancêtres).-réappropriée-par-les-esclaves-comme-moment-de-pause-volé-au-labeur,-espace-de-sociabilité-hors-du-regard-des-maîtres."],
  },
  {
  id: "koubari-curcuma-cur",
  famille: "plantes-symboles de résistance",
  nomCreole: "Koubari / Curcuma",
  nomFrancais: "Curcuma",
  nomScientifique: "Curcuma longa",
  typeResistance: "RÉSISTANCE CULTURELLE Épice apportée par les travailleurs indiens engagés après l'abolition (1848). Sa culture et son usage dans le colombo représentent la résistance culturelle des communautés indiennes à l'assimilation forcée.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Épice apportée par les travailleurs indiens engagés après l'abolition (1848). Sa culture et son usage dans le colombo représentent la résistance culturelle des communautés indiennes à l'assimilation forcée.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-culturelle-épice-apportée-par-les-travailleurs-indiens-engagés-après-l'abolition-(1848).-sa-culture-et-son-usage-dans-le-colombo-représentent-la-résistance-culturelle-des-communautés-indiennes-à-l'assimilation-forcée."],
  },
  {
  id: "gommi-blan-bur",
  famille: "plantes-symboles de résistance",
  nomCreole: "Gommié blan",
  nomFrancais: "Gommier blanc",
  nomScientifique: "Bursera simaruba",
  typeResistance: "RÉSISTANCE AMÉRINDIENNE Arbre des Kalinagos utilisé pour creuser les pirogues de guerre et de fuite. Sa résine-encens servait aux rituels de préparation au combat. Arbre de la mobilité, de l'insoumission et du refus de l'enfermement.",
  resistanceDescription: undefined,
  dimensionCulturelle: "Arbre des Kalinagos utilisé pour creuser les pirogues de guerre et de fuite. Sa résine-encens servait aux rituels de préparation au combat. Arbre de la mobilité, de l'insoumission et du refus de l'enfermement.",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-amérindienne-arbre-des-kalinagos-utilisé-pour-creuser-les-pirogues-de-guerre-et-de-fuite.-sa-résine-encens-servait-aux-rituels-de-préparation-au-combat.-arbre-de-la-mobilité,-de-l'insoumission-et-du-refus-de-l'enfermement."],
  },
  {
  id: "zb-omega-eup",
  famille: "plantes-symboles de résistance",
  nomCreole: "Zéb omega",
  nomFrancais: "Herbe à fièvre",
  nomScientifique: "*Euphorbia hirta*",
  typeResistance: "RÉSISTANCE MÉDICINALE Plante africaine introduite par les esclaves Igbo au XVIIIe siècle. Ses feuilles écrasées servaient à désinfecter les plaies des marrons en fuite. Symbole de la pharmacopée clandestine (Wiltgen 1994, archives ADG 1791).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Plante africaine introduite par les esclaves Igbo au XVIIIe siècle. Ses feuilles écrasées servaient à désinfecter les plaies des marrons en fuite. Symbole de la pharmacopée clandestine (Wiltgen 1994, archives ADG 1791).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-médicinale-plante-africaine-introduite-par-les-esclaves-igbo-au-xviiie-siècle.-ses-feuilles-écrasées-servaient-à-désinfecter-les-plaies-des-marrons-en-fuite.-symbole-de-la-pharmacopée-clandestine-(wiltgen-1994,-archives-adg-1791)."],
  },
  {
  id: "bwa-band-ric",
  famille: "plantes-symboles de résistance",
  nomCreole: "Bwa bandé",
  nomFrancais: "Bois bandé",
  nomScientifique: "*Richeria grandis*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Utilisée par les Kalinago pour ses propriétés aphrodisiaques et comme remède contre la fatigue. Les esclaves l'employaient en secret pour renforcer leur endurance lors des travaux forcés (Bangou 1992, archives DASSA).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Utilisée par les Kalinago pour ses propriétés aphrodisiaques et comme remède contre la fatigue. Les esclaves l'employaient en secret pour renforcer leur endurance lors des travaux forcés (Bangou 1992, archives DASSA).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-utilisée-par-les-kalinago-pour-ses-propriétés-aphrodisiaques-et-comme-remède-contre-la-fatigue.-les-esclaves-l'employaient-en-secret-pour-renforcer-leur-endurance-lors-des-travaux-forcés-(bangou-1992,-archives-dassa)."],
  },
  {
  id: "ti-baume-ple",
  famille: "plantes-symboles de résistance",
  nomCreole: "Ti baume",
  nomFrancais: "Petit baume",
  nomScientifique: "*Plectranthus amboinicus*",
  typeResistance: "RÉSISTANCE MÉDICINALE Cultivée dans les jardins de case pour soigner les infections respiratoires. Symbole de la transmission des savoirs africains malgré l'interdiction des pratiques traditionnelles (Boucher 2008, LESC-CNRS).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Cultivée dans les jardins de case pour soigner les infections respiratoires. Symbole de la transmission des savoirs africains malgré l'interdiction des pratiques traditionnelles (Boucher 2008, LESC-CNRS).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-médicinale-cultivée-dans-les-jardins-de-case-pour-soigner-les-infections-respiratoires.-symbole-de-la-transmission-des-savoirs-africains-malgré-l'interdiction-des-pratiques-traditionnelles-(boucher-2008,-lesc-cnrs)."],
  },
  {
  id: "zerbenn-lip",
  famille: "plantes-symboles de résistance",
  nomCreole: "Zerbenn",
  nomFrancais: "Verveine",
  nomScientifique: "*Lippia citriodora*",
  typeResistance: "RÉSISTANCE MÉDICINALE Infusion utilisée pour calmer les douleurs musculaires après les châtiments. Les maîtres tentaient de limiter son usage, la considérant comme une menace à leur autorité (Wiltgen 1994, ADG).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Infusion utilisée pour calmer les douleurs musculaires après les châtiments. Les maîtres tentaient de limiter son usage, la considérant comme une menace à leur autorité (Wiltgen 1994, ADG).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-médicinale-infusion-utilisée-pour-calmer-les-douleurs-musculaires-après-les-châtiments.-les-maîtres-tentaient-de-limiter-son-usage,-la-considérant-comme-une-menace-à-leur-autorité-(wiltgen-1994,-adg)."],
  },
  {
  id: "bwa-pikan-cap",
  famille: "plantes-symboles de résistance",
  nomCreole: "Bwa pikan",
  nomFrancais: "Bois piment",
  nomScientifique: "*Capsicum frutescens*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Piment cultivé en cachette pour relever les plats fades imposés par les plantations. Symbole de résistance culturelle par la préservation des saveurs africaines (Simpson 1970).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Piment cultivé en cachette pour relever les plats fades imposés par les plantations. Symbole de résistance culturelle par la préservation des saveurs africaines (Simpson 1970).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-alimentaire-piment-cultivé-en-cachette-pour-relever-les-plats-fades-imposés-par-les-plantations.-symbole-de-résistance-culturelle-par-la-préservation-des-saveurs-africaines-(simpson-1970)."],
  },
  {
  id: "lalo-ama",
  famille: "plantes-symboles de résistance",
  nomCreole: "Lalo",
  nomFrancais: "Amarante",
  nomScientifique: "*Amaranthus viridis*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Légume-feuille riche en fer, cultivé dans les jardins des esclaves pour lutter contre la malnutrition. Symbole de la débrouillardise alimentaire (Hurbon 1972, archives coloniales).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Légume-feuille riche en fer, cultivé dans les jardins des esclaves pour lutter contre la malnutrition. Symbole de la débrouillardise alimentaire (Hurbon 1972, archives coloniales).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-alimentaire-légume-feuille-riche-en-fer,-cultivé-dans-les-jardins-des-esclaves-pour-lutter-contre-la-malnutrition.-symbole-de-la-débrouillardise-alimentaire-(hurbon-1972,-archives-coloniales)."],
  },
  {
  id: "pwa-konm-caj",
  famille: "plantes-symboles de résistance",
  nomCreole: "Pwa konm",
  nomFrancais: "Pois congo",
  nomScientifique: "*Cajanus cajan*",
  typeResistance: "RÉSISTANCE ÉCONOMIQUE Cultivé en secret pour compléter les rations insuffisantes. Les graines étaient échangées entre esclaves comme monnaie d'échange (Wiltgen 1994).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Cultivé en secret pour compléter les rations insuffisantes. Les graines étaient échangées entre esclaves comme monnaie d'échange (Wiltgen 1994).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-économique-cultivé-en-secret-pour-compléter-les-rations-insuffisantes.-les-graines-étaient-échangées-entre-esclaves-comme-monnaie-d'échange-(wiltgen-1994)."],
  },
  {
  id: "zpin-zan",
  famille: "plantes-symboles de résistance",
  nomCreole: "Zépin",
  nomFrancais: "Épine du Christ",
  nomScientifique: "*Zanthoxylum caribaeum*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Plante sacrée des Arawaks, réappropriée par les esclaves pour les rituels de purification. Symbole de la connexion entre les cultures amérindiennes et africaines (Bangou 1992).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Plante sacrée des Arawaks, réappropriée par les esclaves pour les rituels de purification. Symbole de la connexion entre les cultures amérindiennes et africaines (Bangou 1992).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-plante-sacrée-des-arawaks,-réappropriée-par-les-esclaves-pour-les-rituels-de-purification.-symbole-de-la-connexion-entre-les-cultures-amérindiennes-et-africaines-(bangou-1992)."],
  },
  {
  id: "bwa-matoutou-ran",
  famille: "plantes-symboles de résistance",
  nomCreole: "Bwa matoutou",
  nomFrancais: "Bois matoutou",
  nomScientifique: "*Randia aculeata*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Utilisé dans le quimbois pour protéger les marrons des chiens de chasse. Symbole de la résistance par la ruse (Boucher 2008).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Utilisé dans le quimbois pour protéger les marrons des chiens de chasse. Symbole de la résistance par la ruse (Boucher 2008).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-utilisé-dans-le-quimbois-pour-protéger-les-marrons-des-chiens-de-chasse.-symbole-de-la-résistance-par-la-ruse-(boucher-2008)."],
  },
  {
  id: "koton-pyi-gos",
  famille: "plantes-symboles de résistance",
  nomCreole: "Koton péyi",
  nomFrancais: "Coton pays",
  nomScientifique: "*Gossypium hirsutum*",
  typeResistance: "RÉSISTANCE ÉCONOMIQUE Cultivé en secret pour fabriquer des vêtements traditionnels, interdits par le Code Noir. Symbole de l'autonomie vestimentaire (archives ADG 1785).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Cultivé en secret pour fabriquer des vêtements traditionnels, interdits par le Code Noir. Symbole de l'autonomie vestimentaire (archives ADG 1785).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-économique-cultivé-en-secret-pour-fabriquer-des-vêtements-traditionnels,-interdits-par-le-code-noir.-symbole-de-l'autonomie-vestimentaire-(archives-adg-1785)."],
  },
  {
  id: "latany-thr",
  famille: "plantes-symboles de résistance",
  nomCreole: "Latanyé",
  nomFrancais: "Latanier",
  nomScientifique: "*Thrinax radiata*",
  typeResistance: "RÉSISTANCE CULTURELLE Feuilles utilisées pour tisser des paniers et des chapeaux, vendus clandestinement aux marchés. Symbole de la résistance économique (Simpson 1970).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Feuilles utilisées pour tisser des paniers et des chapeaux, vendus clandestinement aux marchés. Symbole de la résistance économique (Simpson 1970).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-culturelle-feuilles-utilisées-pour-tisser-des-paniers-et-des-chapeaux,-vendus-clandestinement-aux-marchés.-symbole-de-la-résistance-économique-(simpson-1970)."],
  },
  {
  id: "bwa-fouy-cre",
  famille: "plantes-symboles de résistance",
  nomCreole: "Bwa fouyé",
  nomFrancais: "Bois fouillé",
  nomScientifique: "*Crescentia cujete*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Son fruit (calebasse) servait de récipient pour les potions rituelles. Symbole de la préservation des pratiques vaudou (Hurbon 1972).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Son fruit (calebasse) servait de récipient pour les potions rituelles. Symbole de la préservation des pratiques vaudou (Hurbon 1972).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-son-fruit-(calebasse)-servait-de-récipient-pour-les-potions-rituelles.-symbole-de-la-préservation-des-pratiques-vaudou-(hurbon-1972)."],
  },
  {
  id: "zerbenn-mar-sta",
  famille: "plantes-symboles de résistance",
  nomCreole: "Zerbenn maré",
  nomFrancais: "Verveine marine",
  nomScientifique: "*Stachytarpheta jamaicensis*",
  typeResistance: "RÉSISTANCE SPIRITUELLE Utilisée dans les bains de purification pour chasser les esprits malveillants. Symbole de la résistance spirituelle (Giberti 1989).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Utilisée dans les bains de purification pour chasser les esprits malveillants. Symbole de la résistance spirituelle (Giberti 1989).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-spirituelle-utilisée-dans-les-bains-de-purification-pour-chasser-les-esprits-malveillants.-symbole-de-la-résistance-spirituelle-(giberti-1989)."],
  },
  {
  id: "patat-dou-ipo",
  famille: "plantes-symboles de résistance",
  nomCreole: "Patat dou",
  nomFrancais: "Patate douce",
  nomScientifique: "*Ipomoea batatas*",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Introduite par les Amérindiens, adoptée par les esclaves pour sa facilité de culture. Symbole de la résistance par l'adaptation (INAO, archives coloniales).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Introduite par les Amérindiens, adoptée par les esclaves pour sa facilité de culture. Symbole de la résistance par l'adaptation (INAO, archives coloniales).",
  tags: ["plantes — symboles de résistance", "resistance", "résistance-alimentaire-introduite-par-les-amérindiens,-adoptée-par-les-esclaves-pour-sa-facilité-de-culture.-symbole-de-la-résistance-par-l'adaptation-(inao,-archives-coloniales)."],
  },
  {
  id: "jardin-na",
  famille: "lieux-symboles de résistance",
  nomCreole: "Jardin",
  nomFrancais: "Jardin de case",
  nomScientifique: "N/A",
  typeResistance: "RÉSISTANCE ALIMENTAIRE Espace cultivé en secret pour les plantes médicinales et alimentaires. Symbole de la résistance par l'autosuffisance (Wiltgen 1994).",
  resistanceDescription: undefined,
  dimensionCulturelle: "Espace cultivé en secret pour les plantes médicinales et alimentaires. Symbole de la résistance par l'autosuffisance (Wiltgen 1994).",
  tags: ["lieux — symboles de résistance", "resistance", "résistance-alimentaire-espace-cultivé-en-secret-pour-les-plantes-médicinales-et-alimentaires.-symbole-de-la-résistance-par-l'autosuffisance-(wiltgen-1994)."],
  }
];

// Index pour recherche rapide
export const kreyolIndex: Record<string, KreyolEntry> = {
  "igwann-pyi-igu": kreyolData.find(p => p.id === "igwann-pyi-igu")!,
  "zandoli-anoli-ano": kreyolData.find(p => p.id === "zandoli-anoli-ano")!,
  "urakan-frgate-fre": kreyolData.find(p => p.id === "urakan-frgate-fre")!,
  "gouti-das": kreyolData.find(p => p.id === "gouti-das")!,
  "foumi-manyok-acr": kreyolData.find(p => p.id === "foumi-manyok-acr")!,
  "raz-rat": kreyolData.find(p => p.id === "raz-rat")!,
  "manikou-did": kreyolData.find(p => p.id === "manikou-did")!,
  "serpant-boa": kreyolData.find(p => p.id === "serpant-boa")!,
  "kolibri-tro": kreyolData.find(p => p.id === "kolibri-tro")!,
  "pijon-col": kreyolData.find(p => p.id === "pijon-col")!,
  "kabrit-cap": kreyolData.find(p => p.id === "kabrit-cap")!,
  "chien-marron-can": kreyolData.find(p => p.id === "chien-marron-can")!,
  "coq-gal": kreyolData.find(p => p.id === "coq-gal")!,
  "chauve-souris-mol": kreyolData.find(p => p.id === "chauve-souris-mol")!,
  "crab-car": kreyolData.find(p => p.id === "crab-car")!,
  "loro-ama": kreyolData.find(p => p.id === "loro-ama")!,
  "manyk-man": kreyolData.find(p => p.id === "manyk-man")!,
  "vaniy-van": kreyolData.find(p => p.id === "vaniy-van")!,
  "iyam-dio": kreyolData.find(p => p.id === "iyam-dio")!,
  "woucou-roucou-bix": kreyolData.find(p => p.id === "woucou-roucou-bix")!,
  "malom-malnomme-pet": kreyolData.find(p => p.id === "malom-malnomme-pet")!,
  "kanai-canne-sucre-sac": kreyolData.find(p => p.id === "kanai-canne-sucre-sac")!,
  "tabak-nic": kreyolData.find(p => p.id === "tabak-nic")!,
  "koubari-curcuma-cur": kreyolData.find(p => p.id === "koubari-curcuma-cur")!,
  "gommi-blan-bur": kreyolData.find(p => p.id === "gommi-blan-bur")!,
  "zb-omega-eup": kreyolData.find(p => p.id === "zb-omega-eup")!,
  "bwa-band-ric": kreyolData.find(p => p.id === "bwa-band-ric")!,
  "ti-baume-ple": kreyolData.find(p => p.id === "ti-baume-ple")!,
  "zerbenn-lip": kreyolData.find(p => p.id === "zerbenn-lip")!,
  "bwa-pikan-cap": kreyolData.find(p => p.id === "bwa-pikan-cap")!,
  "lalo-ama": kreyolData.find(p => p.id === "lalo-ama")!,
  "pwa-konm-caj": kreyolData.find(p => p.id === "pwa-konm-caj")!,
  "zpin-zan": kreyolData.find(p => p.id === "zpin-zan")!,
  "bwa-matoutou-ran": kreyolData.find(p => p.id === "bwa-matoutou-ran")!,
  "koton-pyi-gos": kreyolData.find(p => p.id === "koton-pyi-gos")!,
  "latany-thr": kreyolData.find(p => p.id === "latany-thr")!,
  "bwa-fouy-cre": kreyolData.find(p => p.id === "bwa-fouy-cre")!,
  "zerbenn-mar-sta": kreyolData.find(p => p.id === "zerbenn-mar-sta")!,
  "patat-dou-ipo": kreyolData.find(p => p.id === "patat-dou-ipo")!,
  "jardin-na": kreyolData.find(p => p.id === "jardin-na")!
};

// Fonction utilitaire
export function getKreyolByNom(nom: string): KreyolEntry | undefined {
  return kreyolData.find(p => 
    p.nomCreole.toLowerCase() === nom.toLowerCase() ||
    p.nomCreole.toLowerCase().includes(nom.toLowerCase()) ||
    p.nomFrancais.toLowerCase() === nom.toLowerCase() ||
    p.nomFrancais.toLowerCase().includes(nom.toLowerCase())
  );
}
