export interface LieuEntry {
  id: string;
  categorie: string;
  sousCategorie: string;
  nom: string;
  localisation: string;
  isResistanceSymbol: boolean;
  resistanceType?: string;
  resistanceDescription?: string;
  sacreSymbolique?: string;
  dimensionCulturelle: string;
  tags: string[];
}


// Données générées automatiquement depuis lieux_spirituels_ref.md
// NE PAS MODIFIER MANUELLEMENT - Exécuter 'npm run lieux:parse' pour mettre à jour
export const lieuxData: LieuEntry[] = [
  {
  id: "la-soufrire-sai",
  categorie: "VOLCANS",
  sousCategorie: "volcan",
  nom: "La Soufrière",
  localisation: "Saint-Claude",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Cœur de la cosmogonie kalinago, puissance tellurique, crainte et vénération. Fumerolles et soufre liés aux forces du monde souterrain dans le quimbois.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Cœur de la cosmogonie kalinago, puissance tellurique, crainte et vénération. Fumerolles et soufre liés aux forces du monde souterrain dans le quimbois.",
  tags: ["volcans", "volcan", "resistance", "sacré", "sacré-cœur-de-la-cosmogonie-kalinago,-puissance-tellurique,-crainte-et-vénération.-fumerolles-et-soufre-liés-aux-forces-du-monde-souterrain-dans-le-quimbois."],
  },
  {
  id: "morne-madeleine-morne-louis-sai",
  categorie: "VOLCANS",
  sousCategorie: "volcan",
  nom: "Morne Madeleine / Morne à Louis",
  localisation: "Saint-Claude",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Flancs du massif volcanique. Lieux de marronage et de rituels discrets des esclaves en fuite. Mémoire de la résistance.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Flancs du massif volcanique. Lieux de marronage et de rituels discrets des esclaves en fuite. Mémoire de la résistance.",
  tags: ["volcans", "volcan", "resistance", "sacré", "emblématique-flancs-du-massif-volcanique.-lieux-de-marronage-et-de-rituels-discrets-des-esclaves-en-fuite.-mémoire-de-la-résistance."],
  },
  {
  id: "bains-jaunes-bains-chauds-de-la-soufrire-sai",
  categorie: "SOURCES THERMALES",
  sousCategorie: "source thermale",
  nom: "Bains Jaunes / Bains chauds de la Soufrière",
  localisation: "Saint-Claude",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Eaux soufrées à 41 °C au pied du volcan. Guérison, purification et ressourcement depuis les Amérindiens. Lieu de passage entre le monde physique et l'invisible.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Eaux soufrées à 41 °C au pied du volcan. Guérison, purification et ressourcement depuis les Amérindiens. Lieu de passage entre le monde physique et l'invisible.",
  tags: ["sources thermales", "source thermale", "resistance", "sacré", "sacré-eaux-soufrées-à-41-°c-au-pied-du-volcan.-guérison,-purification-et-ressourcement-depuis-les-amérindiens.-lieu-de-passage-entre-le-monde-physique-et-l'invisible."],
  },
  {
  id: "bain-des-amours-dol-gou",
  categorie: "SOURCES THERMALES",
  sousCategorie: "source thermale",
  nom: "Bain des Amours / Dolé",
  localisation: "Gourbeyre",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Bassins thermaux en forêt. Énergie amoureuse et thérapeutique. Pèlerinage populaire depuis le XIXe siècle. Lieu de rituels liés à l'amour et à la fertilité.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Bassins thermaux en forêt. Énergie amoureuse et thérapeutique. Pèlerinage populaire depuis le XIXe siècle. Lieu de rituels liés à l'amour et à la fertilité.",
  tags: ["sources thermales", "source thermale", "resistance", "sacré", "sacré-bassins-thermaux-en-forêt.-énergie-amoureuse-et-thérapeutique.-pèlerinage-populaire-depuis-le-xixe-siècle.-lieu-de-rituels-liés-à-l'amour-et-à-la-fertilité."],
  },
  {
  id: "sources-de-sofaa-sai",
  categorie: "SOURCES THERMALES",
  sousCategorie: "source thermale",
  nom: "Sources de Sofaïa",
  localisation: "Sainte-Rose",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Sources sulfureuses en forêt tropicale dense. Ressourcement et reconnexion à la terre. Lieu reculé à forte charge énergétique.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Sources sulfureuses en forêt tropicale dense. Ressourcement et reconnexion à la terre. Lieu reculé à forte charge énergétique.",
  tags: ["sources thermales", "source thermale", "resistance", "sacré", "emblématique-sources-sulfureuses-en-forêt-tropicale-dense.-ressourcement-et-reconnexion-à-la-terre.-lieu-reculé-à-forte-charge-énergétique."],
  },
  {
  id: "douches-de-matouba-sai",
  categorie: "SOURCES THERMALES",
  sousCategorie: "source thermale",
  nom: "Douches de Matouba",
  localisation: "Saint-Claude",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Eaux soufrées à 950 m d'altitude. Purification avant ou après l'ascension de la Soufrière. Matouba est aussi le lieu où Delgrès se fit sauter plutôt que de se rendre.",
  tags: ["sources thermales", "source thermale", "resistance", "sacré", "symbolique"],
  },
  {
  id: "bains-chauds-de-bouillante-bou",
  categorie: "SOURCES THERMALES",
  sousCategorie: "source thermale",
  nom: "Bains chauds de Bouillante",
  localisation: "Bouillante",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Eau géothermale à 42 °C rejetée dans la mer des Caraïbes. Communion eau-feu-mer. Convergence de trois éléments sacrés en un seul lieu.",
  tags: ["sources thermales", "source thermale", "resistance", "sacré", "symbolique"],
  },
  {
  id: "chutes-du-carbet-cap",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "cascade",
  nom: "Chutes du Carbet",
  localisation: "Capesterre-Belle-Eau",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Cascades sacrées des Kalinagos. Lieux de communication avec les zémis, esprits de la nature. Christophe Colomb les aperçut lors de son second voyage.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Cascades sacrées des Kalinagos. Lieux de communication avec les zémis, esprits de la nature. Christophe Colomb les aperçut lors de son second voyage.",
  tags: ["cascades et rivières", "cascade", "resistance", "sacré", "sacré-cascades-sacrées-des-kalinagos.-lieux-de-communication-avec-les-zémis,-esprits-de-la-nature.-christophe-colomb-les-aperçut-lors-de-son-second-voyage."],
  },
  {
  id: "saut-de-la-lzarde-pet",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "rivière",
  nom: "Saut de la Lézarde",
  localisation: "Petit-Bourg",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Bain rituel et ressourcement dans la tradition créole. Lieu populaire de reconnexion à l'eau et à la nature.",
  tags: ["cascades et rivières", "rivière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cascade-aux-crevisses-pet",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "cascade",
  nom: "Cascade aux Écrevisses",
  localisation: "Petit-Bourg",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Vasque naturelle dans la roche. Purification par l'eau. Accessible, fréquentée pour les bains rituels comme ordinaires.",
  tags: ["cascades et rivières", "cascade", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cascade-kalinago-rivire-du-plessis-bai",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "cascade",
  nom: "Cascade Kalinago / rivière du Plessis",
  localisation: "Baillif",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Cascade portant le nom du peuple amérindien. Associée aux roches gravées sacrées (pétroglyphes). Mémoire vivante de la civilisation kalinago.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Cascade portant le nom du peuple amérindien. Associée aux roches gravées sacrées (pétroglyphes). Mémoire vivante de la civilisation kalinago.",
  tags: ["cascades et rivières", "cascade", "resistance", "sacré", "sacré-cascade-portant-le-nom-du-peuple-amérindien.-associée-aux-roches-gravées-sacrées-(pétroglyphes).-mémoire-vivante-de-la-civilisation-kalinago."],
  },
  {
  id: "grand-tang-sai",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "lac",
  nom: "Grand Étang",
  localisation: "Saint-Claude",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Lac de cratère en forêt à 440 m d'altitude. Esprits des eaux, serpents sacrés selon la tradition locale. Lieu de légendes et d'apparitions.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Lac de cratère en forêt à 440 m d'altitude. Esprits des eaux, serpents sacrés selon la tradition locale. Lieu de légendes et d'apparitions.",
  tags: ["cascades et rivières", "lac", "resistance", "sacré", "sacré-lac-de-cratère-en-forêt-à-440-m-d'altitude.-esprits-des-eaux,-serpents-sacrés-selon-la-tradition-locale.-lieu-de-légendes-et-d'apparitions."],
  },
  {
  id: "rivire-du-plessis-bai",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "rivière",
  nom: "Rivière du Plessis",
  localisation: "Baillif / Vieux-Habitants",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Rivière sacrée des Arawaks. Pétroglyphes dans le lit de l'eau. Sanctuaire dédié à l'esprit de l'eau. Mémoire amérindienne gravée dans la roche.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Rivière sacrée des Arawaks. Pétroglyphes dans le lit de l'eau. Sanctuaire dédié à l'esprit de l'eau. Mémoire amérindienne gravée dans la roche.",
  tags: ["cascades et rivières", "rivière", "resistance", "sacré", "sacré-rivière-sacrée-des-arawaks.-pétroglyphes-dans-le-lit-de-l'eau.-sanctuaire-dédié-à-l'esprit-de-l'eau.-mémoire-amérindienne-gravée-dans-la-roche."],
  },
  {
  id: "embouchures-de-rivires-tou",
  categorie: "CASCADES ET RIVIÈRES",
  sousCategorie: "lieu rituel",
  nom: "Embouchures de rivières",
  localisation: "Toute l'île",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Points sacrés du quimbois. Le gadèzafé prélève l'eau mêlée de sel marin aux embouchures pour ses préparations rituelles. Confluent du doux et du salé, du terrestre et du marin.",
  tags: ["cascades et rivières", "lieu rituel", "resistance", "sacré", "symbolique"],
  },
  {
  id: "parc-national-de-la-guadeloupe-bas",
  categorie: "FORÊTS ET MORNES",
  sousCategorie: "forêt / réserve",
  nom: "Parc National de la Guadeloupe",
  localisation: "Basse-Terre intérieure",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Forêt primaire, réserve de biosphère UNESCO. Les mornes étaient les refuges sacrés des esclaves marrons — lieux de survie, de rituels et de transmission du quimbois.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Forêt primaire, réserve de biosphère UNESCO. Les mornes étaient les refuges sacrés des esclaves marrons — lieux de survie, de rituels et de transmission du quimbois.",
  tags: ["forêts et mornes", "forêt / réserve", "resistance", "sacré", "sacré-forêt-primaire,-réserve-de-biosphère-unesco.-les-mornes-étaient-les-refuges-sacrés-des-esclaves-marrons-—-lieux-de-survie,-de-rituels-et-de-transmission-du-quimbois."],
  },
  {
  id: "route-de-la-traverse-bas",
  categorie: "FORÊTS ET MORNES",
  sousCategorie: "axe symbolique",
  nom: "Route de la Traversée",
  localisation: "Basse-Terre",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Axe traversant la forêt tropicale. Symbolique du passage, de la transformation entre les deux faces de l'île. Frontière entre le visible et l'invisible.",
  tags: ["forêts et mornes", "axe symbolique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "les-mornes-de-basse-terre-bas",
  categorie: "FORÊTS ET MORNES",
  sousCategorie: "mornes",
  nom: "Les Mornes de Basse-Terre",
  localisation: "Basse-Terre",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Refuges des esclaves marrons. Lieux de transmission des rituels, des plantes médicinales et des pratiques du quimbois. Mémoire vivante de la liberté reconquise.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Refuges des esclaves marrons. Lieux de transmission des rituels, des plantes médicinales et des pratiques du quimbois. Mémoire vivante de la liberté reconquise.",
  tags: ["forêts et mornes", "mornes", "resistance", "sacré", "sacré-refuges-des-esclaves-marrons.-lieux-de-transmission-des-rituels,-des-plantes-médicinales-et-des-pratiques-du-quimbois.-mémoire-vivante-de-la-liberté-reconquise."],
  },
  {
  id: "pointe-des-chteaux-sai",
  categorie: "POINTES ET FALAISES",
  sousCategorie: "pointe",
  nom: "Pointe des Châteaux",
  localisation: "Saint-François",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Extrémité orientale face à l'Atlantique. Vent, mer, roche volcanique. Recueillement créole face à l'immensité. Lieu de méditation naturelle.",
  tags: ["pointes et falaises", "pointe", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pointe-de-la-grande-vigie-ans",
  categorie: "POINTES ET FALAISES",
  sousCategorie: "falaise",
  nom: "Pointe de la Grande Vigie",
  localisation: "Anse-Bertrand",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Falaises au nord de Grande-Terre face à l'Atlantique. Méditation, communion avec l'infini de l'océan. Vue sur la mer comme métaphore de l'au-delà.",
  tags: ["pointes et falaises", "falaise", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pointe-allgre-sai",
  categorie: "POINTES ET FALAISES",
  sousCategorie: "cap",
  nom: "Pointe Allègre",
  localisation: "Sainte-Rose",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Cap sauvage au nord de Basse-Terre. Rituels discrets liés à la mer et aux vents. Lieu de passage et d'offrandes.",
  tags: ["pointes et falaises", "cap", "resistance", "sacré", "symbolique"],
  },
  {
  id: "rserve-cousteau-lets-pigeon-bou",
  categorie: "MER ET MANGROVE",
  sousCategorie: "fonds marins",
  nom: "Réserve Cousteau / Îlets Pigeon",
  localisation: "Bouillante",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Fonds marins exceptionnels, coraux, tortues, dauphins. Communion avec le monde sous-marin. Lieu de rencontre entre l'humain et les gardiens marins.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Fonds marins exceptionnels, coraux, tortues, dauphins. Communion avec le monde sous-marin. Lieu de rencontre entre l'humain et les gardiens marins.",
  tags: ["mer et mangrove", "fonds marins", "resistance", "sacré", "emblématique-fonds-marins-exceptionnels,-coraux,-tortues,-dauphins.-communion-avec-le-monde-sous-marin.-lieu-de-rencontre-entre-l'humain-et-les-gardiens-marins."],
  },
  {
  id: "grand-cul-de-sac-marin-sai",
  categorie: "MER ET MANGROVE",
  sousCategorie: "mangrove / lagune",
  nom: "Grand Cul-de-Sac Marin",
  localisation: "Sainte-Rose / Lamentin",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ 15 000 hectares. La mangrove, forêt entre deux eaux, symbolise le passage entre le monde des vivants et celui des ancêtres. Espace-frontière cosmologique.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "15 000 hectares. La mangrove, forêt entre deux eaux, symbolise le passage entre le monde des vivants et celui des ancêtres. Espace-frontière cosmologique.",
  tags: ["mer et mangrove", "mangrove / lagune", "resistance", "sacré", "sacré-15-000-hectares.-la-mangrove,-forêt-entre-deux-eaux,-symbolise-le-passage-entre-le-monde-des-vivants-et-celui-des-ancêtres.-espace-frontière-cosmologique."],
  },
  {
  id: "mangrove-de-guadeloupe-tou",
  categorie: "MER ET MANGROVE",
  sousCategorie: "mangrove",
  nom: "Mangrove de Guadeloupe",
  localisation: "Toute l'île (3 700 ha protégés)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Espace-frontière entre terre et mer, entre vivants et esprits. Lieu de passage dans la cosmologie créole. Forêt d'entre-deux-mondes.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Espace-frontière entre terre et mer, entre vivants et esprits. Lieu de passage dans la cosmologie créole. Forêt d'entre-deux-mondes.",
  tags: ["mer et mangrove", "mangrove", "resistance", "sacré", "sacré-espace-frontière-entre-terre-et-mer,-entre-vivants-et-esprits.-lieu-de-passage-dans-la-cosmologie-créole.-forêt-d'entre-deux-mondes."],
  },
  {
  id: "let-macou-mor",
  categorie: "MER ET MANGROVE",
  sousCategorie: "îlet",
  nom: "Îlet Macou",
  localisation: "Morne-à-l'Eau",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Chapelle des marins disparus en mangrove. Mémoire des pêcheurs noyés, connexion aux esprits de la mer. Culte des disparus de l'eau.",
  tags: ["mer et mangrove", "îlet", "resistance", "sacré", "symbolique"],
  },
  {
  id: "rivire-sale-bai",
  categorie: "MER ET MANGROVE",
  sousCategorie: "bras de mer",
  nom: "Rivière Salée",
  localisation: "Baie-Mahault",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Bras de mer séparant Basse-Terre et Grande-Terre. Symbole de division et de réunion. Cœur géographique et spirituel de l'archipel. Lieu du dualisme guadeloupéen.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Bras de mer séparant Basse-Terre et Grande-Terre. Symbole de division et de réunion. Cœur géographique et spirituel de l'archipel. Lieu du dualisme guadeloupéen.",
  tags: ["mer et mangrove", "bras de mer", "resistance", "sacré", "sacré-bras-de-mer-séparant-basse-terre-et-grande-terre.-symbole-de-division-et-de-réunion.-cœur-géographique-et-spirituel-de-l'archipel.-lieu-du-dualisme-guadeloupéen."],
  },
  {
  id: "la-dsirade-dsi",
  categorie: "ÎLES DÉPENDANCES",
  sousCategorie: "île",
  nom: "La Désirade",
  localisation: "Désirade",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Bout du monde, pénitence et purification. Ancienne léproserie. Forte charge symbolique de l'isolement et de la rédemption.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Bout du monde, pénitence et purification. Ancienne léproserie. Forte charge symbolique de l'isolement et de la rédemption.",
  tags: ["îles dépendances", "île", "resistance", "sacré", "sacré-bout-du-monde,-pénitence-et-purification.-ancienne-léproserie.-forte-charge-symbolique-de-l'isolement-et-de-la-rédemption."],
  },
  {
  id: "marie-galante-mar",
  categorie: "ÎLES DÉPENDANCES",
  sousCategorie: "île",
  nom: "Marie-Galante",
  localisation: "Marie-Galante",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Île plate, la grande galette. Spiritualité rurale intense, rituels liés à la canne et à la terre. Temps suspendu, mémoire de l'esclavage agricole.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Île plate, la grande galette. Spiritualité rurale intense, rituels liés à la canne et à la terre. Temps suspendu, mémoire de l'esclavage agricole.",
  tags: ["îles dépendances", "île", "resistance", "sacré", "sacré-île-plate,-la-grande-galette.-spiritualité-rurale-intense,-rituels-liés-à-la-canne-et-à-la-terre.-temps-suspendu,-mémoire-de-l'esclavage-agricole."],
  },
  {
  id: "terre-de-haut-les-saintes-les",
  categorie: "ÎLES DÉPENDANCES",
  sousCategorie: "île",
  nom: "Terre-de-Haut (Les Saintes)",
  localisation: "Les Saintes",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Recueillement naturel et connexion à la mer des Saintes. Isolement insulaire propice à la contemplation.",
  tags: ["îles dépendances", "île", "resistance", "sacré", "symbolique"],
  },
  {
  id: "petite-terre-pet",
  categorie: "ÎLES DÉPENDANCES",
  sousCategorie: "île",
  nom: "Petite-Terre",
  localisation: "Petite-Terre",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Réserve quasi-déserte, iguanas endémiques gardiens de l'île. Lieu de bout du monde, pureté et retrait du monde humain.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Réserve quasi-déserte, iguanas endémiques gardiens de l'île. Lieu de bout du monde, pureté et retrait du monde humain.",
  tags: ["îles dépendances", "île", "resistance", "sacré", "sacré-réserve-quasi-déserte,-iguanas-endémiques-gardiens-de-l'île.-lieu-de-bout-du-monde,-pureté-et-retrait-du-monde-humain."],
  },
  {
  id: "grotte-zimbis-grotte-aux-esprits-pet",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Grotte Zimbis / Grotte aux Esprits",
  localisation: "Petit-Bourg, morne Abymes, 100m au sud du sentier des marrons (16.2345° N, 61.6789° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Grotte abritant des pétroglyphes kalinagos. Lieu de rituels de communication avec les zémis de la mer. Interdit d’accès sans guide spirituel (rapport INAO, 1987 ; Simpson 1970, p. 123-125). Utilisée pour des cérémonies de purification et des offrandes aux esprits marins.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Grotte abritant des pétroglyphes kalinagos. Lieu de rituels de communication avec les zémis de la mer. Interdit d’accès sans guide spirituel (rapport INAO, 1987 ; Simpson 1970, p. 123-125). Utilisée pour des cérémonies de purification et des offrandes aux esprits marins.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "sacré-grotte-abritant-des-pétroglyphes-kalinagos.-lieu-de-rituels-de-communication-avec-les-zémis-de-la-mer.-interdit-d’accès-sans-guide-spirituel-(rapport-inao,-1987-;-simpson-1970,-p.-123-125).-utilisée-pour-des-cérémonies-de-purification-et-des-offrandes-aux-esprits-marins."],
  },
  {
  id: "trou-a-diab-bas",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Trou a Diab’",
  localisation: "Basse-Terre, morne de Dubuisson, 50m au sud du sentier (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Lieu de dépôts d’offrandes pour apaiser les mwon (esprits malveillants). Utilisé par les marrons au XVIIIe siècle pour les rituels de protection (archives DASSA, 1832 ; Bangou 1992, p. 89). Traces de feux rituels et dépôts de coquillages.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Lieu de dépôts d’offrandes pour apaiser les mwon (esprits malveillants). Utilisé par les marrons au XVIIIe siècle pour les rituels de protection (archives DASSA, 1832 ; Bangou 1992, p. 89). Traces de feux rituels et dépôts de coquillages.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "sacré-lieu-de-dépôts-d’offrandes-pour-apaiser-les-mwon-(esprits-malveillants).-utilisé-par-les-marrons-au-xviiie-siècle-pour-les-rituels-de-protection-(archives-dassa,-1832-;-bangou-1992,-p.-89).-traces-de-feux-rituels-et-dépôts-de-coquillages."],
  },
  {
  id: "grotte-de-la-petite-rivire-sale-sai",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Grotte de la Petite Rivière Salée",
  localisation: "Sainte-Marie, morne de 20m d’altitude (16.2500° N, 61.6200° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Refuge kalinago pour rituels de guérison et protection. Plantes médicinales cultivées à l’entrée. Utilisée pour des cérémonies de purification et des rituels de chasse (Simpson 1970, p. 45 ; Hurbon 1972, p. 112).",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Refuge kalinago pour rituels de guérison et protection. Plantes médicinales cultivées à l’entrée. Utilisée pour des cérémonies de purification et des rituels de chasse (Simpson 1970, p. 45 ; Hurbon 1972, p. 112).",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "sacré-refuge-kalinago-pour-rituels-de-guérison-et-protection.-plantes-médicinales-cultivées-à-l’entrée.-utilisée-pour-des-cérémonies-de-purification-et-des-rituels-de-chasse-(simpson-1970,-p.-45-;-hurbon-1972,-p.-112)."],
  },
  {
  id: "abri-sous-roche-de-la-rivire-prou-bas",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Abri sous Roche de la Rivière Pérou",
  localisation: "Basse-Terre, 200m à l’est du pont de la rivière Pérou (16.2000° N, 61.6700° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Abri utilisé par les Arawaks pour des rituels de chasse. Vestiges de poteries et outils en pierre (Giberti 1989, p. 78 ; archives ADG, 1995). Lieu de préparation des chasseurs avant les expéditions.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Abri utilisé par les Arawaks pour des rituels de chasse. Vestiges de poteries et outils en pierre (Giberti 1989, p. 78 ; archives ADG, 1995). Lieu de préparation des chasseurs avant les expéditions.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "emblématique-abri-utilisé-par-les-arawaks-pour-des-rituels-de-chasse.-vestiges-de-poteries-et-outils-en-pierre-(giberti-1989,-p.-78-;-archives-adg,-1995).-lieu-de-préparation-des-chasseurs-avant-les-expéditions."],
  },
  {
  id: "grotte-du-morne-rita-cap",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Grotte du Morne Rita",
  localisation: "Capesterre de Marie-Galante, flanc nord du morne (16.1800° N, 61.5500° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Pétroglyphes arawaks représentant des divinités marines. Lieu de cérémonies pour apaiser les esprits de l’océan (Bangou 1992, p. 67 ; LESC-CNRS, 2001). Utilisée pour des rituels de pêche et de protection des pêcheurs.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Pétroglyphes arawaks représentant des divinités marines. Lieu de cérémonies pour apaiser les esprits de l’océan (Bangou 1992, p. 67 ; LESC-CNRS, 2001). Utilisée pour des rituels de pêche et de protection des pêcheurs.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "emblématique-pétroglyphes-arawaks-représentant-des-divinités-marines.-lieu-de-cérémonies-pour-apaiser-les-esprits-de-l’océan-(bangou-1992,-p.-67-;-lesc-cnrs,-2001).-utilisée-pour-des-rituels-de-pêche-et-de-protection-des-pêcheurs."],
  },
  {
  id: "trou-a-zotrey-tro",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Trou a Zotrey",
  localisation: "Trois-Rivières, près de l’Anse Galets (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Grotte associée aux récits de zimbi (esprits errants). Utilisée pour des rituels de purification (Hurbon 1972, p. 145 ; CRDP Guadeloupe, 1998). Lieu de dépôts d’offrandes pour écarter les esprits malveillants.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "symbolique"],
  },
  {
  id: "grotte-de-la-pointe-allgre-sai",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Grotte de la Pointe Allègre",
  localisation: "Sainte-Rose, morne isolé près de la côte (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu de refuge pour les esclaves marrons. Traces de feux rituels et offrandes de coquillages (archives DASSA, 1841 ; Boucher 2008, p. 201). Utilisée pour des rituels de résistance et de protection.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "symbolique"],
  },
  {
  id: "abri-de-la-ravine-chaude-gou",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Abri de la Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Utilisé par les Kalinagos pour des rituels de pluie. Vestiges de pierres disposées en cercle (Simpson 1970, p. 98 ; INAO, 2005). Lieu de cérémonies pour invoquer la pluie et la fertilité des terres.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "symbolique"],
  },
  {
  id: "grotte-de-la-ravine-malice-cap",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Grotte de la Ravine à Malice",
  localisation: "Capesterre-Belle-Eau, ravine à Malice (16.1000° N, 61.6000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Grotte utilisée pour des rituels de ko minion (communication avec les ancêtres). Traces de peintures naturelles (Boucher 2008, p. 218 ; LESC-CNRS, 2010). Lieu de dépôts d’offrandes pour les esprits des ancêtres.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "symbolique"],
  },
  {
  id: "trou-a-zmis-pet",
  categorie: "GROTTES ET ABRIS",
  sousCategorie: "grotte/abri",
  nom: "Trou a Zémis",
  localisation: "Petit-Bourg, morne Abymes (16.2300° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Grotte associée aux zémis (esprits protecteurs). Lieu de dépôts d’offrandes (Simpson 1970, p. 115 ; Hurbon 1972, p. 140). Utilisée pour des rituels de protection et de purification.",
  tags: ["grottes et abris", "grotte/abri", "resistance", "sacré", "symbolique"],
  },
  {
  id: "kawoubouy-lam",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Kawoubouyé",
  localisation: "Lamentin, intersection route de Dubuisson (16.2600° N, 61.6300° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Carrefour où les pratiques du quimbois de la route sont encore vivaces. Offrandes de rhum et tabac pour écarter les mwon (Simpson, field notes 1968 ; Boucher 2008, p. 156). Lieu de rituels de protection pour les voyageurs.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Carrefour où les pratiques du quimbois de la route sont encore vivaces. Offrandes de rhum et tabac pour écarter les mwon (Simpson, field notes 1968 ; Boucher 2008, p. 156). Lieu de rituels de protection pour les voyageurs.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "sacré-carrefour-où-les-pratiques-du-quimbois-de-la-route-sont-encore-vivaces.-offrandes-de-rhum-et-tabac-pour-écarter-les-mwon-(simpson,-field-notes-1968-;-boucher-2008,-p.-156).-lieu-de-rituels-de-protection-pour-les-voyageurs."],
  },
  {
  id: "carrefour-de-la-croix-mission-les",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Croix-Mission",
  localisation: "Les Abymes, route de la Croix-Mission (16.2400° N, 61.5800° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Lieu de dépôts d’offrandes pour les ancêtres. Rituels de gadèzafé (protection des foyers) attestés (Hurbon 1972, p. 88 ; archives CRDP, 2003). Utilisé pour des cérémonies de mémoire et de protection familiale.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Lieu de dépôts d’offrandes pour les ancêtres. Rituels de gadèzafé (protection des foyers) attestés (Hurbon 1972, p. 88 ; archives CRDP, 2003). Utilisé pour des cérémonies de mémoire et de protection familiale.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "emblématique-lieu-de-dépôts-d’offrandes-pour-les-ancêtres.-rituels-de-gadèzafé-(protection-des-foyers)-attestés-(hurbon-1972,-p.-88-;-archives-crdp,-2003).-utilisé-pour-des-cérémonies-de-mémoire-et-de-protection-familiale."],
  },
  {
  id: "carrefour-de-la-petite-rivire-sale-sai",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Petite Rivière Salée",
  localisation: "Sainte-Marie, intersection chemins rivière-mer (16.2500° N, 61.6200° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Dépôts d’offrandes pour apaiser les esprits des ancêtres kalinagos (Simpson 1970, p. 56 ; Boucher 2008, p. 189). Lieu de rituels de purification et de protection.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-lanse-duqury-tro",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de l’Anse Duquéry",
  localisation: "Trois-Rivières, près de l’Anse Duquéry (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu de rencontre arawak pour rituels de commerce et troc. Offrandes de maïs et poisson (Bangou 1992, p. 112 ; Giberti 1989, p. 92). Utilisé pour des cérémonies de prospérité et d’échange.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-morne-leau-mor",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de Morne-à-l’Eau",
  localisation: "Morne-à-l’Eau, intersection route de la Madeleines (16.2700° N, 61.5700° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Utilisé pour des rituels de pwen (protection contre le mauvais œil). Offrandes de bougies et fleurs (LESC-CNRS, 2010 ; Hurbon 1972, p. 178). Lieu de cérémonies de protection individuelle et collective.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-la-ravine-malice-cap",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Ravine à Malice",
  localisation: "Capesterre-Belle-Eau, ravine à Malice (16.1000° N, 61.6000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu de dépôts d’offrandes pour les esprits de la forêt. Rituels de ko minion (communication avec les ancêtres) (Boucher 2008, p. 210 ; archives ADG, 1988). Utilisé pour des cérémonies de mémoire et de lien avec les ancêtres.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-la-pointe-noire-bas",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Pointe Noire",
  localisation: "Basse-Terre, route de la Pointe Noire (16.1200° N, 61.6600° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Associé aux rituels de protection contre les mwon marins. Offrandes de sel et coquillages (Simpson 1970, p. 134 ; CRDP Guadeloupe, 2005). Lieu de cérémonies pour apaiser les esprits de la mer.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-la-ravine-claire-le",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Ravine Claire",
  localisation: "Le Moule, ravine Claire (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu de dépôts d’offrandes pour les esprits kalinagos. Rituels de protection (Bangou 1992, p. 60 ; Giberti 1989, p. 130). Utilisé pour des cérémonies de purification et de lien avec les esprits autochtones.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "carrefour-de-la-source-pet",
  categorie: "CARREFOURS",
  sousCategorie: "carrefour",
  nom: "Carrefour de la Source",
  localisation: "Petit-Bourg, près de la source de la Rivière Salée (16.2300° N, 61.6700° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Carrefour utilisé pour des rituels de purification. Offrandes d’eau et herbes (LESC-CNRS, 2003 ; Boucher 2008, p. 195). Lieu de cérémonies de nettoyage spirituel.",
  tags: ["carrefours", "carrefour", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pwaz-lavwa-pierre-de-la-loi-sai",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Pwaz Lavwa / Pierre de la Loi",
  localisation: "Sainte-Rose, habitation La Mahaudière (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Pierre plate de 2m de diamètre où les esclaves marrons tenaient leurs assemblées. Lieu de serments et dépôt de pwen pour la justice (archives DASSA, 1832 ; Bangou 1992, p. 45). Utilisée pour des rituels de résistance et de justice sociale.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Pierre plate de 2m de diamètre où les esclaves marrons tenaient leurs assemblées. Lieu de serments et dépôt de pwen pour la justice (archives DASSA, 1832 ; Bangou 1992, p. 45). Utilisée pour des rituels de résistance et de justice sociale.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "sacré-pierre-plate-de-2m-de-diamètre-où-les-esclaves-marrons-tenaient-leurs-assemblées.-lieu-de-serments-et-dépôt-de-pwen-pour-la-justice-(archives-dassa,-1832-;-bangou-1992,-p.-45).-utilisée-pour-des-rituels-de-résistance-et-de-justice-sociale."],
  },
  {
  id: "roche-grave-de-lanse-galets-tro",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Roche Gravée de l’Anse Galets",
  localisation: "Trois-Rivières, plage de l’Anse Galets (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Roche gravée de motifs géométriques et animaux. Rituels de protection et purification arawaks (Bangou 1992, p. 78 ; Giberti 1989, p. 85). Lieu de cérémonies pour apaiser les esprits et protéger les pêcheurs.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Roche gravée de motifs géométriques et animaux. Rituels de protection et purification arawaks (Bangou 1992, p. 78 ; Giberti 1989, p. 85). Lieu de cérémonies pour apaiser les esprits et protéger les pêcheurs.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "emblématique-roche-gravée-de-motifs-géométriques-et-animaux.-rituels-de-protection-et-purification-arawaks-(bangou-1992,-p.-78-;-giberti-1989,-p.-85).-lieu-de-cérémonies-pour-apaiser-les-esprits-et-protéger-les-pêcheurs."],
  },
  {
  id: "roche-grave-de-la-valle-dor-tro",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Roche Gravée de la Vallée d’Or",
  localisation: "Trois-Rivières, vallée d’Or (16.1800° N, 61.6300° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Roche gravée utilisée pour des rituels de fertilité. Motifs liés aux divinités arawaks de l’agriculture (Bangou 1992, p. 92 ; Giberti 1989, p. 101). Lieu de cérémonies pour assurer la fertilité des terres et des récoltes.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Roche gravée utilisée pour des rituels de fertilité. Motifs liés aux divinités arawaks de l’agriculture (Bangou 1992, p. 92 ; Giberti 1989, p. 101). Lieu de cérémonies pour assurer la fertilité des terres et des récoltes.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "emblématique-roche-gravée-utilisée-pour-des-rituels-de-fertilité.-motifs-liés-aux-divinités-arawaks-de-l’agriculture-(bangou-1992,-p.-92-;-giberti-1989,-p.-101).-lieu-de-cérémonies-pour-assurer-la-fertilité-des-terres-et-des-récoltes."],
  },
  {
  id: "menhir-de-la-ravine-claire-le",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Menhir de la Ravine Claire",
  localisation: "Le Moule, ravine Claire (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Menhir naturel de 3m de haut. Lieu de rituels kalinagos pour la chasse et la guerre (Simpson 1970, p. 67 ; INAO, 1999). Utilisé pour des cérémonies de préparation des chasseurs et des guerriers.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Menhir naturel de 3m de haut. Lieu de rituels kalinagos pour la chasse et la guerre (Simpson 1970, p. 67 ; INAO, 1999). Utilisé pour des cérémonies de préparation des chasseurs et des guerriers.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "emblématique-menhir-naturel-de-3m-de-haut.-lieu-de-rituels-kalinagos-pour-la-chasse-et-la-guerre-(simpson-1970,-p.-67-;-inao,-1999).-utilisé-pour-des-cérémonies-de-préparation-des-chasseurs-et-des-guerriers."],
  },
  {
  id: "roche-cupidon-pet",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Roche à Cupidon",
  localisation: "Petit-Canal, près de la rivière (16.2800° N, 61.5500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Roche en forme de cœur, associée aux rituels d’amour et de fertilité. Offrandes de fleurs et fruits (Hurbon 1972, p. 133 ; archives CRDP, 1997). Lieu de cérémonies pour attirer l’amour et la prospérité.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pierre-des-esprits-pwaz-zotrey-gou",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Pierre des Esprits (Pwaz Zotrey)",
  localisation: "Gourbeyre, morne de la Ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Roche plate où les esprits (zotrey) étaient invoqués pour la guérison. Traces de peintures naturelles (LESC-CNRS, 2008 ; Boucher 2008, p. 198). Lieu de rituels de guérison et de communication avec les esprits.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "symbolique"],
  },
  {
  id: "roche-du-serment-bas",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Roche du Serment",
  localisation: "Basse-Terre, morne de la Soufrière (flanc est) (16.1200° N, 61.6600° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu où les marrons prêtaient serment de résistance. Gravures symbolisant la liberté (archives DASSA, 1845 ; Simpson 1970, p. 145). Utilisée pour des cérémonies de résistance et de solidarité.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "symbolique"],
  },
  {
  id: "roche-des-anctres-bas",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Roche des Ancêtres",
  localisation: "Basse-Terre, morne de la Soufrière (flanc ouest) (16.1200° N, 61.6700° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Roche gravée de symboles kalinagos. Lieu de rituels de mémoire des ancêtres (Simpson 1970, p. 72 ; archives INAO, 2000). Utilisée pour des cérémonies de lien avec les ancêtres et de protection.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "symbolique"],
  },
  {
  id: "pierre-du-serment-des-marrons-pet",
  categorie: "PIERRES ET ROCHES",
  sousCategorie: "pierre/roche",
  nom: "Pierre du Serment des Marrons",
  localisation: "Petit-Bourg, forêt de Dubuisson (16.2300° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Pierre où les marrons prêtaient serment de résistance. Gravures symboliques (archives DASSA, 1838 ; Hurbon 1972, p. 165). Lieu de cérémonies de résistance et de mémoire collective.",
  tags: ["pierres et roches", "pierre/roche", "resistance", "sacré", "symbolique"],
  },
  {
  id: "fromager-de-la-case-peser-bas",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Fromager de la Case à Peser",
  localisation: "Basse-Terre, habitation Case à Peser (16.1800° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Fromager centenaire lié aux rituels de quimbois. Lieu de dépôts d’offrandes pour la protection des récoltes (Bangou 1992, p. 56 ; Hurbon 1972, p. 167). Utilisé pour des cérémonies de protection agricole et de fertilité.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Fromager centenaire lié aux rituels de quimbois. Lieu de dépôts d’offrandes pour la protection des récoltes (Bangou 1992, p. 56 ; Hurbon 1972, p. 167). Utilisé pour des cérémonies de protection agricole et de fertilité.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "sacré-fromager-centenaire-lié-aux-rituels-de-quimbois.-lieu-de-dépôts-d’offrandes-pour-la-protection-des-récoltes-(bangou-1992,-p.-56-;-hurbon-1972,-p.-167).-utilisé-pour-des-cérémonies-de-protection-agricole-et-de-fertilité."],
  },
  {
  id: "gommier-de-la-ravine-malice-cap",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Gommier de la Ravine à Malice",
  localisation: "Capesterre-Belle-Eau, ravine à Malice (16.1000° N, 61.6000° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Gommier utilisé pour des rituels de purification. Écorce récoltée pour des remèdes traditionnels (Giberti 1989, p. 112 ; archives ADG, 1991). Lieu de cérémonies de guérison et de purification.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Gommier utilisé pour des rituels de purification. Écorce récoltée pour des remèdes traditionnels (Giberti 1989, p. 112 ; archives ADG, 1991). Lieu de cérémonies de guérison et de purification.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "emblématique-gommier-utilisé-pour-des-rituels-de-purification.-écorce-récoltée-pour-des-remèdes-traditionnels-(giberti-1989,-p.-112-;-archives-adg,-1991).-lieu-de-cérémonies-de-guérison-et-de-purification."],
  },
  {
  id: "mapou-de-la-source-pet",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Mapou de la Source",
  localisation: "Petit-Bourg, près de la source de la Rivière Salée (16.2300° N, 61.6700° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Mapou sacré lié aux rituels de pluie. Offrandes de maïs et rhum (Simpson 1970, p. 89 ; LESC-CNRS, 2003). Utilisé pour des cérémonies d’invocation de la pluie et de protection des cultures.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Mapou sacré lié aux rituels de pluie. Offrandes de maïs et rhum (Simpson 1970, p. 89 ; LESC-CNRS, 2003). Utilisé pour des cérémonies d’invocation de la pluie et de protection des cultures.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "emblématique-mapou-sacré-lié-aux-rituels-de-pluie.-offrandes-de-maïs-et-rhum-(simpson-1970,-p.-89-;-lesc-cnrs,-2003).-utilisé-pour-des-cérémonies-d’invocation-de-la-pluie-et-de-protection-des-cultures."],
  },
  {
  id: "figuier-maudit-tro",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Figuier Maudit",
  localisation: "Trois-Rivières, Parc Archéologique des Roches Gravées (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Figuier associé à des légendes de malédiction. Lieu de rituels de protection contre les mwon (Hurbon 1972, p. 156 ; Boucher 2008, p. 205). Utilisé pour des cérémonies de protection et de purification.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "baobab-de-la-savane-pet",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Baobab de la Savane",
  localisation: "Petit-Canal, Village International du Ka (16.2800° N, 61.5500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Baobab planté en hommage aux ancêtres africains. Lieu de rituels de mémoire et résistance (Simpson 1970, p. 178 ; CRDP Guadeloupe, 2010). Utilisé pour des cérémonies de mémoire collective et de lien avec les ancêtres.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "acoma-de-la-pointe-allgre-sai",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Acoma de la Pointe Allègre",
  localisation: "Sainte-Rose, près de la Pointe Allègre (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Acoma utilisé pour des rituels de protection des pêcheurs. Offrandes de poisson séché (Bangou 1992, p. 103 ; Giberti 1989, p. 125). Lieu de cérémonies de protection des pêcheurs et de leurs familles.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cocotier-de-la-plage-des-raisins-clairs-sai",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Cocotier de la Plage des Raisins Clairs",
  localisation: "Saint-François, plage des Raisins Clairs (16.2500° N, 61.5200° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Cocotier lié aux rituels de protection des voyageurs. Offrandes de noix de coco (archives DASSA, 1850 ; Boucher 2008, p. 215). Utilisé pour des cérémonies de protection des voyageurs et des marins.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "gommier-de-la-fort-de-dubuisson-bas",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Gommier de la Forêt de Dubuisson",
  localisation: "Basse-Terre, forêt de Dubuisson (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Gommier utilisé pour des rituels de protection. Écorce récoltée pour des remèdes (Giberti 1989, p. 110 ; archives ADG, 1990). Lieu de cérémonies de guérison et de protection.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "fromager-de-la-ravine-chaude-gou",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Fromager de la Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Fromager lié aux rituels de fertilité. Offrandes de fruits (Bangou 1992, p. 82 ; LESC-CNRS, 2001). Utilisé pour des cérémonies de fertilité et de prospérité.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "mapou-de-la-pointe-allgre-sai",
  categorie: "ARBRES SACRÉS",
  sousCategorie: "arbre sacré",
  nom: "Mapou de la Pointe Allègre",
  localisation: "Sainte-Rose, Pointe Allègre (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Mapou associé aux rituels de protection des pêcheurs. Offrandes de poisson (Simpson 1970, p. 90 ; CRDP Guadeloupe, 2005). Lieu de cérémonies de protection des pêcheurs et de leurs outils.",
  tags: ["arbres sacrés", "arbre sacré", "resistance", "sacré", "symbolique"],
  },
  {
  id: "source-de-la-grotte-zimbis-pet",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source de la Grotte Zimbis",
  localisation: "Petit-Bourg, morne Abymes (16.2345° N, 61.6789° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Source utilisée pour des rituels de purification et guérison. Eau considérée comme sacrée (dlo zotrey) (Simpson 1970, p. 102 ; INAO, 1987). Lieu de cérémonies de purification et de guérison.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Source utilisée pour des rituels de purification et guérison. Eau considérée comme sacrée (dlo zotrey) (Simpson 1970, p. 102 ; INAO, 1987). Lieu de cérémonies de purification et de guérison.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "sacré-source-utilisée-pour-des-rituels-de-purification-et-guérison.-eau-considérée-comme-sacrée-(dlo-zotrey)-(simpson-1970,-p.-102-;-inao,-1987).-lieu-de-cérémonies-de-purification-et-de-guérison."],
  },
  {
  id: "source-de-la-ravine-chaude-gou",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source de la Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Source thermale discrète utilisée pour des rituels de fertilité. Eau riche en minéraux (Giberti 1989, p. 134 ; archives ADG, 1995). Lieu de cérémonies de fertilité et de régénération.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Source thermale discrète utilisée pour des rituels de fertilité. Eau riche en minéraux (Giberti 1989, p. 134 ; archives ADG, 1995). Lieu de cérémonies de fertilité et de régénération.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "emblématique-source-thermale-discrète-utilisée-pour-des-rituels-de-fertilité.-eau-riche-en-minéraux-(giberti-1989,-p.-134-;-archives-adg,-1995).-lieu-de-cérémonies-de-fertilité-et-de-régénération."],
  },
  {
  id: "source-de-lanse-galets-tro",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source de l’Anse Galets",
  localisation: "Trois-Rivières, grotte de l’Anse Galets (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Source marine utilisée pour des rituels de protection des pêcheurs. Eau salée mélangée à des herbes (Bangou 1992, p. 85 ; CRDP Guadeloupe, 1998). Lieu de cérémonies de protection des pêcheurs et de leurs outils.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "symbolique"],
  },
  {
  id: "source-du-morne-rita-cap",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source du Morne Rita",
  localisation: "Capesterre de Marie-Galante, flanc nord du morne (16.1800° N, 61.5500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Source associée aux rituels arawaks de purification. Eau utilisée pour des offrandes aux zémis (Giberti 1989, p. 98 ; archives INAO, 2005). Lieu de cérémonies de purification et de lien avec les esprits.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "symbolique"],
  },
  {
  id: "source-de-la-ravine-malice-cap",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source de la Ravine à Malice",
  localisation: "Capesterre-Belle-Eau, ravine à Malice (16.1000° N, 61.6000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Source discrète utilisée pour des rituels de ko minion (communication avec les ancêtres). Eau considérée comme porteuse de messages (Boucher 2008, p. 220 ; LESC-CNRS, 2010). Lieu de cérémonies de communication avec les ancêtres.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "symbolique"],
  },
  {
  id: "source-des-esprits-dlo-zotrey-pet",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source des Esprits (Dlo Zotrey)",
  localisation: "Petit-Bourg, morne Abymes (16.2300° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Source utilisée pour des rituels de communication avec les zotrey. Eau considérée comme sacrée (Hurbon 1972, p. 130 ; INAO, 1987). Lieu de cérémonies de purification et de communication avec les esprits.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "symbolique"],
  },
  {
  id: "source-de-la-fort-de-dubuisson-bas",
  categorie: "SOURCES CACHÉES",
  sousCategorie: "source cachée",
  nom: "Source de la Forêt de Dubuisson",
  localisation: "Basse-Terre, forêt de Dubuisson (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Source discrète utilisée pour des rituels de purification. Eau mélangée à des herbes (archives DASSA, 1835 ; Boucher 2008, p. 200). Lieu de cérémonies de purification et de guérison.",
  tags: ["sources cachées", "source cachée", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cimetire-desclaves-de-sainte-marguerite-le",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière d’Esclaves de Sainte-Marguerite",
  localisation: "Le Moule, Anse Sainte-Marguerite (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Cimetière clandestin d’esclaves. Tombes marquées de coquillages et pierres. Lieu de mémoire et rituels de gadèzafé (archives DASSA, 1835 ; Simpson 1970, p. 156). Utilisé pour des cérémonies de mémoire et de protection des ancêtres.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Cimetière clandestin d’esclaves. Tombes marquées de coquillages et pierres. Lieu de mémoire et rituels de gadèzafé (archives DASSA, 1835 ; Simpson 1970, p. 156). Utilisé pour des cérémonies de mémoire et de protection des ancêtres.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "sacré-cimetière-clandestin-d’esclaves.-tombes-marquées-de-coquillages-et-pierres.-lieu-de-mémoire-et-rituels-de-gadèzafé-(archives-dassa,-1835-;-simpson-1970,-p.-156).-utilisé-pour-des-cérémonies-de-mémoire-et-de-protection-des-ancêtres."],
  },
  {
  id: "cimetire-desclaves-de-saint-franois-sai",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière d’Esclaves de Saint-François",
  localisation: "Saint-François, plage des Raisins Clairs (16.2500° N, 61.5200° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Tombes anonymes d’esclaves noyés. Lieu de rituels de mémoire et offrandes de fleurs (Hurbon 1972, p. 189 ; archives ADG, 1980). Utilisé pour des cérémonies de mémoire et de lien avec les ancêtres.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Tombes anonymes d’esclaves noyés. Lieu de rituels de mémoire et offrandes de fleurs (Hurbon 1972, p. 189 ; archives ADG, 1980). Utilisé pour des cérémonies de mémoire et de lien avec les ancêtres.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "sacré-tombes-anonymes-d’esclaves-noyés.-lieu-de-rituels-de-mémoire-et-offrandes-de-fleurs-(hurbon-1972,-p.-189-;-archives-adg,-1980).-utilisé-pour-des-cérémonies-de-mémoire-et-de-lien-avec-les-ancêtres."],
  },
  {
  id: "carr-des-esclaves-de-la-habitation-la-mahaudire-sai",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Carré des Esclaves de la Habitation La Mahaudière",
  localisation: "Sainte-Rose (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Carré d’esclaves avec tombes alignées. Lieu de rituels de protection des ancêtres (Bangou 1992, p. 62 ; Giberti 1989, p. 145). Utilisé pour des cérémonies de mémoire et de protection familiale.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Carré d’esclaves avec tombes alignées. Lieu de rituels de protection des ancêtres (Bangou 1992, p. 62 ; Giberti 1989, p. 145). Utilisé pour des cérémonies de mémoire et de protection familiale.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "emblématique-carré-d’esclaves-avec-tombes-alignées.-lieu-de-rituels-de-protection-des-ancêtres-(bangou-1992,-p.-62-;-giberti-1989,-p.-145).-utilisé-pour-des-cérémonies-de-mémoire-et-de-protection-familiale."],
  },
  {
  id: "cimetire-des-marrons-de-la-fort-de-dubuisson-bas",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Marrons de la Forêt de Dubuisson",
  localisation: "Basse-Terre, forêt de Dubuisson (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Tombes discrètes marquées de symboles de résistance. Lieu de mémoire des marrons (archives DASSA, 1842 ; Simpson 1970, p. 167). Utilisé pour des cérémonies de mémoire et de résistance.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Tombes discrètes marquées de symboles de résistance. Lieu de mémoire des marrons (archives DASSA, 1842 ; Simpson 1970, p. 167). Utilisé pour des cérémonies de mémoire et de résistance.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "emblématique-tombes-discrètes-marquées-de-symboles-de-résistance.-lieu-de-mémoire-des-marrons-(archives-dassa,-1842-;-simpson-1970,-p.-167).-utilisé-pour-des-cérémonies-de-mémoire-et-de-résistance."],
  },
  {
  id: "cimetire-des-enfants-esclaves-de-la-pointe-noire-bas",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Enfants Esclaves de la Pointe Noire",
  localisation: "Basse-Terre, Pointe Noire (16.1200° N, 61.6600° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Tombes d’enfants esclaves. Lieu de rituels de protection et mémoire (LESC-CNRS, 2005 ; Boucher 2008, p. 230). Utilisé pour des cérémonies de mémoire et de protection des enfants.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cimetire-des-kalinagos-de-la-ravine-claire-le",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Kalinagos de la Ravine Claire",
  localisation: "Le Moule, ravine Claire (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Tombes kalinagos marquées de pierres plates. Lieu de rituels de mémoire (Simpson 1970, p. 78 ; archives INAO, 1999). Utilisé pour des cérémonies de mémoire et de lien avec les ancêtres autochtones.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cimetire-des-arawaks-de-lanse-galets-tro",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Arawaks de l’Anse Galets",
  localisation: "Trois-Rivières, Anse Galets (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Tombes arawaks avec offrandes de poteries. Lieu de mémoire et rituels de protection (Bangou 1992, p. 115 ; Giberti 1989, p. 156). Utilisé pour des cérémonies de mémoire et de protection des ancêtres.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cimetire-des-marrons-de-la-ravine-chaude-gou",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Marrons de la Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Tombes de marrons marquées de pierres. Lieu de mémoire et rituels de protection (Simpson 1970, p. 150 ; LESC-CNRS, 2008). Utilisé pour des cérémonies de mémoire et de résistance.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "cimetire-des-kalinagos-de-la-pointe-allgre-sai",
  categorie: "CIMETIÈRES",
  sousCategorie: "cimetière",
  nom: "Cimetière des Kalinagos de la Pointe Allègre",
  localisation: "Sainte-Rose, Pointe Allègre (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Tombes kalinagos avec offrandes de coquillages. Lieu de rituels de mémoire (Bangou 1992, p. 55 ; Giberti 1989, p. 128). Utilisé pour des cérémonies de mémoire et de lien avec les ancêtres autochtones.",
  tags: ["cimetières", "cimetière", "resistance", "sacré", "symbolique"],
  },
  {
  id: "morne-de-dubuisson-bas",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Morne de Dubuisson",
  localisation: "Basse-Terre, forêt de Dubuisson (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "SACRÉ Zone de refuge pour les marrons. Vestiges de cases et feux rituels. Lieu de résistance et rituels de pwen (archives DASSA, 1832 ; Hurbon 1972, p. 172). Utilisé pour des cérémonies de résistance et de protection.",
  resistanceDescription: undefined,
  sacreSymbolique: "SACRÉ",
  dimensionCulturelle: "Zone de refuge pour les marrons. Vestiges de cases et feux rituels. Lieu de résistance et rituels de pwen (archives DASSA, 1832 ; Hurbon 1972, p. 172). Utilisé pour des cérémonies de résistance et de protection.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "sacré-zone-de-refuge-pour-les-marrons.-vestiges-de-cases-et-feux-rituels.-lieu-de-résistance-et-rituels-de-pwen-(archives-dassa,-1832-;-hurbon-1972,-p.-172).-utilisé-pour-des-cérémonies-de-résistance-et-de-protection."],
  },
  {
  id: "ravine-chaude-gou",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Zone de marronnage avec traces de cultures vivrières. Lieu de rituels de protection (Simpson 1970, p. 95 ; LESC-CNRS, 2001). Utilisé pour des cérémonies de résistance et de survie.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Zone de marronnage avec traces de cultures vivrières. Lieu de rituels de protection (Simpson 1970, p. 95 ; LESC-CNRS, 2001). Utilisé pour des cérémonies de résistance et de survie.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "emblématique-zone-de-marronnage-avec-traces-de-cultures-vivrières.-lieu-de-rituels-de-protection-(simpson-1970,-p.-95-;-lesc-cnrs,-2001).-utilisé-pour-des-cérémonies-de-résistance-et-de-survie."],
  },
  {
  id: "fort-de-la-petite-rivire-sale-sai",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Forêt de la Petite Rivière Salée",
  localisation: "Sainte-Marie, forêt près de la rivière (16.2500° N, 61.6200° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Refuge pour marrons. Traces de sentiers et abris temporaires (Bangou 1992, p. 50 ; archives CRDP, 2003). Utilisé pour des cérémonies de résistance et de protection.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Refuge pour marrons. Traces de sentiers et abris temporaires (Bangou 1992, p. 50 ; archives CRDP, 2003). Utilisé pour des cérémonies de résistance et de protection.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "emblématique-refuge-pour-marrons.-traces-de-sentiers-et-abris-temporaires-(bangou-1992,-p.-50-;-archives-crdp,-2003).-utilisé-pour-des-cérémonies-de-résistance-et-de-protection."],
  },
  {
  id: "morne-louis-pet",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Morne à Louis",
  localisation: "Petit-Bourg, morne à Louis (16.2300° N, 61.6700° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Lieu de résistance marronne. Vestiges de pièges et outils (Giberti 1989, p. 120 ; archives ADG, 1991). Utilisé pour des cérémonies de résistance et de survie.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ravine-malice-cap",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Ravine à Malice",
  localisation: "Capesterre-Belle-Eau, ravine à Malice (16.1000° N, 61.6000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Zone de marronnage avec traces de feux rituels. Lieu de mémoire (Boucher 2008, p. 212 ; LESC-CNRS, 2010). Utilisé pour des cérémonies de mémoire et de résistance.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "fort-de-la-valle-dor-tro",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Forêt de la Vallée d’Or",
  localisation: "Trois-Rivières, vallée d’Or (16.1800° N, 61.6300° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Refuge pour marrons arawaks. Traces de cultures et rituels de protection (Bangou 1992, p. 88 ; CRDP Guadeloupe, 1998). Utilisé pour des cérémonies de résistance et de survie.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "morne-de-la-soufrire-flanc-est-bas",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Morne de la Soufrière (flanc est)",
  localisation: "Basse-Terre, morne de la Soufrière (16.1200° N, 61.6600° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Zone de marronnage avec abris sous roche. Lieu de rituels de résistance (Simpson 1970, p. 142 ; archives DASSA, 1845). Utilisé pour des cérémonies de résistance et de protection.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "fort-de-la-ravine-claire-le",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Forêt de la Ravine Claire",
  localisation: "Le Moule, ravine Claire (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Zone de marronnage avec traces de cases. Lieu de rituels de résistance (archives CRDP, 2003 ; Boucher 2008, p. 225). Utilisé pour des cérémonies de résistance et de mémoire.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "morne-de-la-petite-rivire-sale-sai",
  categorie: "LIEUX DE MARRONNAGE",
  sousCategorie: "lieu de marronnage",
  nom: "Morne de la Petite Rivière Salée",
  localisation: "Sainte-Marie, morne près de la rivière (16.2500° N, 61.6200° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Refuge pour marrons kalinagos. Traces de feux rituels (Hurbon 1972, p. 115 ; LESC-CNRS, 2001). Utilisé pour des cérémonies de résistance et de protection.",
  tags: ["lieux de marronnage", "lieu de marronnage", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ptroglyphes-de-la-ravine-claire-le",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Pétroglyphes de la Ravine Claire",
  localisation: "Le Moule, ravine Claire (16.3200° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Pétroglyphes kalinagos représentant des divinités et animaux. Lieu de rituels de chasse (INAO, 1999 ; Simpson 1970, p. 65). Utilisé pour des cérémonies de préparation des chasseurs.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Pétroglyphes kalinagos représentant des divinités et animaux. Lieu de rituels de chasse (INAO, 1999 ; Simpson 1970, p. 65). Utilisé pour des cérémonies de préparation des chasseurs.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "emblématique-pétroglyphes-kalinagos-représentant-des-divinités-et-animaux.-lieu-de-rituels-de-chasse-(inao,-1999-;-simpson-1970,-p.-65).-utilisé-pour-des-cérémonies-de-préparation-des-chasseurs."],
  },
  {
  id: "habitat-arawak-de-lanse-galets-tro",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Habitat Arawak de l’Anse Galets",
  localisation: "Trois-Rivières, Anse Galets (16.1900° N, 61.6400° W)",
  isResistanceSymbol: true,
  resistanceType: "Emblématique Vestiges d’habitat arawak avec poteries et outils. Lieu de rituels domestiques (Bangou 1992, p. 75 ; Giberti 1989, p. 88). Utilisé pour des cérémonies de protection et de prospérité.",
  resistanceDescription: undefined,
  sacreSymbolique: "Emblématique",
  dimensionCulturelle: "Vestiges d’habitat arawak avec poteries et outils. Lieu de rituels domestiques (Bangou 1992, p. 75 ; Giberti 1989, p. 88). Utilisé pour des cérémonies de protection et de prospérité.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "emblématique-vestiges-d’habitat-arawak-avec-poteries-et-outils.-lieu-de-rituels-domestiques-(bangou-1992,-p.-75-;-giberti-1989,-p.-88).-utilisé-pour-des-cérémonies-de-protection-et-de-prospérité."],
  },
  {
  id: "abri-sous-roche-de-la-pointe-allgre-sai",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Abri sous Roche de la Pointe Allègre",
  localisation: "Sainte-Rose, Pointe Allègre (16.3000° N, 61.7000° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Abri utilisé par les Kalinagos pour des rituels de pêche. Vestiges de coquillages et outils (archives DASSA, 1830 ; Hurbon 1972, p. 125). Utilisé pour des cérémonies de protection des pêcheurs.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ptroglyphes-du-morne-rita-cap",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Pétroglyphes du Morne Rita",
  localisation: "Capesterre de Marie-Galante, morne Rita (16.1800° N, 61.5500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Pétroglyphes arawaks liés aux rituels marins. Représentations de poissons et vagues (Giberti 1989, p. 95 ; INAO, 2005). Utilisé pour des cérémonies de protection et de lien avec les esprits marins.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "vestiges-kalinagos-de-la-ravine-chaude-gou",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Vestiges Kalinagos de la Ravine Chaude",
  localisation: "Gourbeyre, ravine Chaude (16.1500° N, 61.6500° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Vestiges de cases et outils kalinagos. Lieu de rituels de protection (Simpson 1970, p. 85 ; LESC-CNRS, 2008). Utilisé pour des cérémonies de protection et de purification.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "habitat-de-la-petite-rivire-sale-sai",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Habitat de la Petite Rivière Salée",
  localisation: "Sainte-Marie, près de la rivière (16.2500° N, 61.6200° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Vestiges d’habitat kalinago avec traces de feux rituels (Hurbon 1972, p. 110 ; archives CRDP, 2003). Utilisé pour des cérémonies de protection et de lien avec les esprits.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ptroglyphes-de-la-valle-dor-tro",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Pétroglyphes de la Vallée d’Or",
  localisation: "Trois-Rivières, vallée d’Or (16.1800° N, 61.6300° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Pétroglyphes arawaks liés aux rituels agricoles. Motifs de plantes et animaux (Bangou 1992, p. 90 ; Giberti 1989, p. 105). Utilisé pour des cérémonies de fertilité et de prospérité.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "abri-des-esclaves-de-la-pointe-noire-bas",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Abri des Esclaves de la Pointe Noire",
  localisation: "Basse-Terre, Pointe Noire (16.1200° N, 61.6600° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Abri utilisé par les esclaves marrons pour des rituels de protection. Vestiges de poteries (archives DASSA, 1840 ; Boucher 2008, p. 208). Utilisé pour des cérémonies de résistance et de protection.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  },
  {
  id: "ptroglyphes-de-la-fort-de-dubuisson-bas",
  categorie: "SITES ARCHÉOLOGIQUES",
  sousCategorie: "site archéologique",
  nom: "Pétroglyphes de la Forêt de Dubuisson",
  localisation: "Basse-Terre, forêt de Dubuisson (16.2100° N, 61.6800° W)",
  isResistanceSymbol: true,
  resistanceType: "Symbolique",
  resistanceDescription: undefined,
  sacreSymbolique: "Symbolique",
  dimensionCulturelle: "Pétroglyphes kalinagos liés aux rituels de chasse. Motifs d’animaux (Simpson 1970, p. 68 ; archives INAO, 2000). Utilisé pour des cérémonies de préparation des chasseurs et de protection.",
  tags: ["sites archéologiques", "site archéologique", "resistance", "sacré", "symbolique"],
  }
];

// Index pour recherche rapide
export const lieuxIndex: Record<string, LieuEntry> = {
  "la-soufrire-sai": lieuxData.find(p => p.id === "la-soufrire-sai")!,
  "morne-madeleine-morne-louis-sai": lieuxData.find(p => p.id === "morne-madeleine-morne-louis-sai")!,
  "bains-jaunes-bains-chauds-de-la-soufrire-sai": lieuxData.find(p => p.id === "bains-jaunes-bains-chauds-de-la-soufrire-sai")!,
  "bain-des-amours-dol-gou": lieuxData.find(p => p.id === "bain-des-amours-dol-gou")!,
  "sources-de-sofaa-sai": lieuxData.find(p => p.id === "sources-de-sofaa-sai")!,
  "douches-de-matouba-sai": lieuxData.find(p => p.id === "douches-de-matouba-sai")!,
  "bains-chauds-de-bouillante-bou": lieuxData.find(p => p.id === "bains-chauds-de-bouillante-bou")!,
  "chutes-du-carbet-cap": lieuxData.find(p => p.id === "chutes-du-carbet-cap")!,
  "saut-de-la-lzarde-pet": lieuxData.find(p => p.id === "saut-de-la-lzarde-pet")!,
  "cascade-aux-crevisses-pet": lieuxData.find(p => p.id === "cascade-aux-crevisses-pet")!,
  "cascade-kalinago-rivire-du-plessis-bai": lieuxData.find(p => p.id === "cascade-kalinago-rivire-du-plessis-bai")!,
  "grand-tang-sai": lieuxData.find(p => p.id === "grand-tang-sai")!,
  "rivire-du-plessis-bai": lieuxData.find(p => p.id === "rivire-du-plessis-bai")!,
  "embouchures-de-rivires-tou": lieuxData.find(p => p.id === "embouchures-de-rivires-tou")!,
  "parc-national-de-la-guadeloupe-bas": lieuxData.find(p => p.id === "parc-national-de-la-guadeloupe-bas")!,
  "route-de-la-traverse-bas": lieuxData.find(p => p.id === "route-de-la-traverse-bas")!,
  "les-mornes-de-basse-terre-bas": lieuxData.find(p => p.id === "les-mornes-de-basse-terre-bas")!,
  "pointe-des-chteaux-sai": lieuxData.find(p => p.id === "pointe-des-chteaux-sai")!,
  "pointe-de-la-grande-vigie-ans": lieuxData.find(p => p.id === "pointe-de-la-grande-vigie-ans")!,
  "pointe-allgre-sai": lieuxData.find(p => p.id === "pointe-allgre-sai")!,
  "rserve-cousteau-lets-pigeon-bou": lieuxData.find(p => p.id === "rserve-cousteau-lets-pigeon-bou")!,
  "grand-cul-de-sac-marin-sai": lieuxData.find(p => p.id === "grand-cul-de-sac-marin-sai")!,
  "mangrove-de-guadeloupe-tou": lieuxData.find(p => p.id === "mangrove-de-guadeloupe-tou")!,
  "let-macou-mor": lieuxData.find(p => p.id === "let-macou-mor")!,
  "rivire-sale-bai": lieuxData.find(p => p.id === "rivire-sale-bai")!,
  "la-dsirade-dsi": lieuxData.find(p => p.id === "la-dsirade-dsi")!,
  "marie-galante-mar": lieuxData.find(p => p.id === "marie-galante-mar")!,
  "terre-de-haut-les-saintes-les": lieuxData.find(p => p.id === "terre-de-haut-les-saintes-les")!,
  "petite-terre-pet": lieuxData.find(p => p.id === "petite-terre-pet")!,
  "grotte-zimbis-grotte-aux-esprits-pet": lieuxData.find(p => p.id === "grotte-zimbis-grotte-aux-esprits-pet")!,
  "trou-a-diab-bas": lieuxData.find(p => p.id === "trou-a-diab-bas")!,
  "grotte-de-la-petite-rivire-sale-sai": lieuxData.find(p => p.id === "grotte-de-la-petite-rivire-sale-sai")!,
  "abri-sous-roche-de-la-rivire-prou-bas": lieuxData.find(p => p.id === "abri-sous-roche-de-la-rivire-prou-bas")!,
  "grotte-du-morne-rita-cap": lieuxData.find(p => p.id === "grotte-du-morne-rita-cap")!,
  "trou-a-zotrey-tro": lieuxData.find(p => p.id === "trou-a-zotrey-tro")!,
  "grotte-de-la-pointe-allgre-sai": lieuxData.find(p => p.id === "grotte-de-la-pointe-allgre-sai")!,
  "abri-de-la-ravine-chaude-gou": lieuxData.find(p => p.id === "abri-de-la-ravine-chaude-gou")!,
  "grotte-de-la-ravine-malice-cap": lieuxData.find(p => p.id === "grotte-de-la-ravine-malice-cap")!,
  "trou-a-zmis-pet": lieuxData.find(p => p.id === "trou-a-zmis-pet")!,
  "kawoubouy-lam": lieuxData.find(p => p.id === "kawoubouy-lam")!,
  "carrefour-de-la-croix-mission-les": lieuxData.find(p => p.id === "carrefour-de-la-croix-mission-les")!,
  "carrefour-de-la-petite-rivire-sale-sai": lieuxData.find(p => p.id === "carrefour-de-la-petite-rivire-sale-sai")!,
  "carrefour-de-lanse-duqury-tro": lieuxData.find(p => p.id === "carrefour-de-lanse-duqury-tro")!,
  "carrefour-de-morne-leau-mor": lieuxData.find(p => p.id === "carrefour-de-morne-leau-mor")!,
  "carrefour-de-la-ravine-malice-cap": lieuxData.find(p => p.id === "carrefour-de-la-ravine-malice-cap")!,
  "carrefour-de-la-pointe-noire-bas": lieuxData.find(p => p.id === "carrefour-de-la-pointe-noire-bas")!,
  "carrefour-de-la-ravine-claire-le": lieuxData.find(p => p.id === "carrefour-de-la-ravine-claire-le")!,
  "carrefour-de-la-source-pet": lieuxData.find(p => p.id === "carrefour-de-la-source-pet")!,
  "pwaz-lavwa-pierre-de-la-loi-sai": lieuxData.find(p => p.id === "pwaz-lavwa-pierre-de-la-loi-sai")!,
  "roche-grave-de-lanse-galets-tro": lieuxData.find(p => p.id === "roche-grave-de-lanse-galets-tro")!,
  "roche-grave-de-la-valle-dor-tro": lieuxData.find(p => p.id === "roche-grave-de-la-valle-dor-tro")!,
  "menhir-de-la-ravine-claire-le": lieuxData.find(p => p.id === "menhir-de-la-ravine-claire-le")!,
  "roche-cupidon-pet": lieuxData.find(p => p.id === "roche-cupidon-pet")!,
  "pierre-des-esprits-pwaz-zotrey-gou": lieuxData.find(p => p.id === "pierre-des-esprits-pwaz-zotrey-gou")!,
  "roche-du-serment-bas": lieuxData.find(p => p.id === "roche-du-serment-bas")!,
  "roche-des-anctres-bas": lieuxData.find(p => p.id === "roche-des-anctres-bas")!,
  "pierre-du-serment-des-marrons-pet": lieuxData.find(p => p.id === "pierre-du-serment-des-marrons-pet")!,
  "fromager-de-la-case-peser-bas": lieuxData.find(p => p.id === "fromager-de-la-case-peser-bas")!,
  "gommier-de-la-ravine-malice-cap": lieuxData.find(p => p.id === "gommier-de-la-ravine-malice-cap")!,
  "mapou-de-la-source-pet": lieuxData.find(p => p.id === "mapou-de-la-source-pet")!,
  "figuier-maudit-tro": lieuxData.find(p => p.id === "figuier-maudit-tro")!,
  "baobab-de-la-savane-pet": lieuxData.find(p => p.id === "baobab-de-la-savane-pet")!,
  "acoma-de-la-pointe-allgre-sai": lieuxData.find(p => p.id === "acoma-de-la-pointe-allgre-sai")!,
  "cocotier-de-la-plage-des-raisins-clairs-sai": lieuxData.find(p => p.id === "cocotier-de-la-plage-des-raisins-clairs-sai")!,
  "gommier-de-la-fort-de-dubuisson-bas": lieuxData.find(p => p.id === "gommier-de-la-fort-de-dubuisson-bas")!,
  "fromager-de-la-ravine-chaude-gou": lieuxData.find(p => p.id === "fromager-de-la-ravine-chaude-gou")!,
  "mapou-de-la-pointe-allgre-sai": lieuxData.find(p => p.id === "mapou-de-la-pointe-allgre-sai")!,
  "source-de-la-grotte-zimbis-pet": lieuxData.find(p => p.id === "source-de-la-grotte-zimbis-pet")!,
  "source-de-la-ravine-chaude-gou": lieuxData.find(p => p.id === "source-de-la-ravine-chaude-gou")!,
  "source-de-lanse-galets-tro": lieuxData.find(p => p.id === "source-de-lanse-galets-tro")!,
  "source-du-morne-rita-cap": lieuxData.find(p => p.id === "source-du-morne-rita-cap")!,
  "source-de-la-ravine-malice-cap": lieuxData.find(p => p.id === "source-de-la-ravine-malice-cap")!,
  "source-des-esprits-dlo-zotrey-pet": lieuxData.find(p => p.id === "source-des-esprits-dlo-zotrey-pet")!,
  "source-de-la-fort-de-dubuisson-bas": lieuxData.find(p => p.id === "source-de-la-fort-de-dubuisson-bas")!,
  "cimetire-desclaves-de-sainte-marguerite-le": lieuxData.find(p => p.id === "cimetire-desclaves-de-sainte-marguerite-le")!,
  "cimetire-desclaves-de-saint-franois-sai": lieuxData.find(p => p.id === "cimetire-desclaves-de-saint-franois-sai")!,
  "carr-des-esclaves-de-la-habitation-la-mahaudire-sai": lieuxData.find(p => p.id === "carr-des-esclaves-de-la-habitation-la-mahaudire-sai")!,
  "cimetire-des-marrons-de-la-fort-de-dubuisson-bas": lieuxData.find(p => p.id === "cimetire-des-marrons-de-la-fort-de-dubuisson-bas")!,
  "cimetire-des-enfants-esclaves-de-la-pointe-noire-bas": lieuxData.find(p => p.id === "cimetire-des-enfants-esclaves-de-la-pointe-noire-bas")!,
  "cimetire-des-kalinagos-de-la-ravine-claire-le": lieuxData.find(p => p.id === "cimetire-des-kalinagos-de-la-ravine-claire-le")!,
  "cimetire-des-arawaks-de-lanse-galets-tro": lieuxData.find(p => p.id === "cimetire-des-arawaks-de-lanse-galets-tro")!,
  "cimetire-des-marrons-de-la-ravine-chaude-gou": lieuxData.find(p => p.id === "cimetire-des-marrons-de-la-ravine-chaude-gou")!,
  "cimetire-des-kalinagos-de-la-pointe-allgre-sai": lieuxData.find(p => p.id === "cimetire-des-kalinagos-de-la-pointe-allgre-sai")!,
  "morne-de-dubuisson-bas": lieuxData.find(p => p.id === "morne-de-dubuisson-bas")!,
  "ravine-chaude-gou": lieuxData.find(p => p.id === "ravine-chaude-gou")!,
  "fort-de-la-petite-rivire-sale-sai": lieuxData.find(p => p.id === "fort-de-la-petite-rivire-sale-sai")!,
  "morne-louis-pet": lieuxData.find(p => p.id === "morne-louis-pet")!,
  "ravine-malice-cap": lieuxData.find(p => p.id === "ravine-malice-cap")!,
  "fort-de-la-valle-dor-tro": lieuxData.find(p => p.id === "fort-de-la-valle-dor-tro")!,
  "morne-de-la-soufrire-flanc-est-bas": lieuxData.find(p => p.id === "morne-de-la-soufrire-flanc-est-bas")!,
  "fort-de-la-ravine-claire-le": lieuxData.find(p => p.id === "fort-de-la-ravine-claire-le")!,
  "morne-de-la-petite-rivire-sale-sai": lieuxData.find(p => p.id === "morne-de-la-petite-rivire-sale-sai")!,
  "ptroglyphes-de-la-ravine-claire-le": lieuxData.find(p => p.id === "ptroglyphes-de-la-ravine-claire-le")!,
  "habitat-arawak-de-lanse-galets-tro": lieuxData.find(p => p.id === "habitat-arawak-de-lanse-galets-tro")!,
  "abri-sous-roche-de-la-pointe-allgre-sai": lieuxData.find(p => p.id === "abri-sous-roche-de-la-pointe-allgre-sai")!,
  "ptroglyphes-du-morne-rita-cap": lieuxData.find(p => p.id === "ptroglyphes-du-morne-rita-cap")!,
  "vestiges-kalinagos-de-la-ravine-chaude-gou": lieuxData.find(p => p.id === "vestiges-kalinagos-de-la-ravine-chaude-gou")!,
  "habitat-de-la-petite-rivire-sale-sai": lieuxData.find(p => p.id === "habitat-de-la-petite-rivire-sale-sai")!,
  "ptroglyphes-de-la-valle-dor-tro": lieuxData.find(p => p.id === "ptroglyphes-de-la-valle-dor-tro")!,
  "abri-des-esclaves-de-la-pointe-noire-bas": lieuxData.find(p => p.id === "abri-des-esclaves-de-la-pointe-noire-bas")!,
  "ptroglyphes-de-la-fort-de-dubuisson-bas": lieuxData.find(p => p.id === "ptroglyphes-de-la-fort-de-dubuisson-bas")!
};

// Fonction utilitaire
export function getLieuByNom(nom: string): LieuEntry | undefined {
  return lieuxData.find(p => 
    p.nom.toLowerCase() === nom.toLowerCase() ||
    p.nom.toLowerCase().includes(nom.toLowerCase())
  );
}
